### PR TITLE
Reject configuration with unknown fields

### LINKED ISSUE #2663: Reject configuration with unknown fields
https://github.com/nspcc-dev/neo-go/issues/3128 is very cool and saved us time several times already, you immediately see obsolete/wrong configuration and can fix it easily (instead of waiting for the service misbehavior). I want this for IR and SN, but I'm not sure it's gonna be easy.

### PR DESCRIPTION
**Pull request by End-rey**
Closes #2663, #1950.

The problems I have encountered:
- node config: `grpc` section with list of structures and `node` section with unlimited number of attributes.
- `.env` files are not being processed, because of the work of the `viper` package. Should I do it? It might be more difficult.

### CODE REVIEW

**Comment by End-rey** [comment]
There was a problem that the default value of the list was a slice with a length of 0, so I added a check for this. And now my devenv works.
But it seems like automated system tests didn't pass because the `ir` or `node` didn't run well. How can I find out what the error was that caused them to fail? Maybe there is a bad configuration?

File: cmd/internal/configvalidator/validate.go [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+	"errors"
+	"fmt"
+	"reflect"
+	"strings"
+)
+
+// ErrUnknowField returns when an unknown field appears in the config.
+var ErrUnknowField = errors.New("unknown field")
+
+// CheckForUnknownFields validate the config struct for unknown fields with the config map.
```
Comment (roman-khimov) [inline cmd/internal/configvalidator/validate.go:13]: validates

File: cmd/neofs-ir/internal/validate/validate_test.go [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+
+import (
+	"path/filepath"
+	"testing"
+
+	"github.com/spf13/viper"
+	"github.com/stretchr/testify/require"
+)
+
+func TestCheckForUnknownFieldsExample(t *testing.T) {
```
Comment (roman-khimov) [inline cmd/neofs-ir/internal/validate/validate_test.go:11]: Negative test scenarios?

File: cmd/neofs-node/config/config.go [hunk 3]
```diff
@@ -54,6 +55,13 @@ func New(_ Prm, opts ...Option) *Config {
 		}
 	}
 
+	if o.validate {
```
Comment (roman-khimov) [inline cmd/neofs-node/config/config.go:58]: Why conditional?

File: cmd/neofs-ir/internal/validate/config.go [hunk 4]
```diff
@@ -0,0 +1,213 @@
+package validate
+
+import "time"
+
+type validConfig struct {
+	Logger struct {
+		Level string `mapstructure:"level"`
```
Comment (roman-khimov) [inline cmd/neofs-ir/internal/validate/config.go:7]: Can we just name it `level` and not have any `mapstructure` tags?

File: cmd/neofs-ir/defaults.go [hunk 5]
```diff
@@ -60,7 +69,6 @@ func defaultConfiguration(cfg *viper.Viper) {
 	cfg.SetDefault("wallet.address", "")  // account address
 	cfg.SetDefault("wallet.password", "") // password
 
-	cfg.SetDefault("timers.emit", "0")
```
Comment (roman-khimov) [inline cmd/neofs-ir/defaults.go:63]: There has to be some test for default configuration only.

File: cmd/internal/configvalidator/validate.go [hunk 6]
```diff
@@ -0,0 +1,102 @@
...
+// If the field in the config is a map of a key and some value, need to use `mapstructure:,remain` and
+// `prefix` tag with the key prefix, even it is empty string.
+func CheckForUnknownFields(configMap map[string]any, config any, currentPath string) error {
```
Comment (roman-khimov) [inline cmd/internal/configvalidator/validate.go:16]: You better not expose `currentPath` here, it's an implementation detail.

File: cmd/internal/configvalidator/validate.go [hunk 7]
```diff
@@ -0,0 +1,102 @@
...
+		if jsonTag := field.Tag.Get("mapstructure"); jsonTag != "" {
+			fields[jsonTag] = struct{}{}
+		} else {
+			fields[field.Name] = struct{}{}
+		}
+	}
+	return fields
+}
+
+func getStructFieldByTagComparation(config any, tagKey, tagValue string, comparation func(a, b string) bool) string {
```
Comment (roman-khimov) [inline cmd/internal/configvalidator/validate.go:93]: `getStructFieldByTag` is sufficient and it's `comparison`.

File: cmd/internal/configvalidator/validate.go [hunk 8]
```diff
@@ -0,0 +1,102 @@
...
+// ErrUnknowField returns when an unknown field appears in the config.
+var ErrUnknowField = errors.New("unknown field")
+
+// CheckForUnknownFields validate the config struct for unknown fields with the config map.
+// If the field in the config is a map of a key and some value, need to use `mapstructure:,remain` and
+// `prefix` tag with the key prefix, even it is empty string.
+func CheckForUnknownFields(configMap map[string]any, config any, currentPath string) error {
+	expectedFields := getFieldsFromStruct(config)
+
+	for key, val := range configMap {
```
Comment (roman-khimov) [inline cmd/internal/configvalidator/validate.go:19]: Seems to be _very_ inefficient since you traverse the same items for every key. Maybe it's not a problem given the size of our configuration files, but I'd try flattening (into a slice) and sorting `configMap` which allows to walk by prefixes more effectively then. Still, what's the time we spend here for example config?

File: cmd/neofs-ir/internal/validate/config.go [hunk 9]
```diff
@@ -0,0 +1,213 @@
+package validate
+
+import "time"
+
+type validConfig struct {
```
Comment (roman-khimov) [inline cmd/neofs-ir/internal/validate/config.go:5]: What bugs me is that we have this structure used just for validation while in fact we also have similar structures in various subcomponents. Can those be reused here to avoid duplication? I mean we can _always_ parse into this config and then operate with components (just like NeoGo does).

**Review by roman-khimov — COMMENTED** [review]
Can this be solved with https://pkg.go.dev/github.com/spf13/viper#UnmarshalExact?

File: cmd/neofs-ir/internal/validate/config.go (hunk 4 above)
Comment (End-rey) [reply cmd/neofs-ir/internal/validate/config.go:7]: We can't because the fields of the structure must be exported for `Unmarshal`.

**Comment by End-rey** [comment]
> Can this be solved with https://pkg.go.dev/github.com/spf13/viper#UnmarshalExact?

Partially it can, but there are such fields in the config, for example, `node.attribute_*` and there can be as many as you like, so the tag `,remain` is used, because of which any incorrect fields will fall into this field and then validation will be successful, although in fact there will be an error. I tried this method and it didn't pass my tests.

File: cmd/internal/configvalidator/validate.go (hunk 8 above)
Comment (End-rey) [reply cmd/internal/configvalidator/validate.go:19]: For `ir` example config, the execution time of this function is 192 microseconds, for `node` - 197 microseconds. 
It's going to be a little difficult considering `,remain` case and not so necessary now.

File: cmd/neofs-node/config/config.go (hunk 3 above)
Comment (End-rey) [reply cmd/neofs-node/config/config.go:58]: It's made for `call_test` and `cast_test` tests that check the correct parsing of values, and there is separate configuration for tests.

**Review by roman-khimov — APPROVED** [review]
