### PR TITLE
engine: make more detailed removal of the split object

### LINKED ISSUE #3629: Object is stuck in GC cycle
## Expected Behavior
GC drops the expired object, it's gone.

## Current Behavior
```
Oct 09 16:09:05 titan4 neofs-node[717444]: info        log/log.go:12        local object storage operation        {"shard_id": "FvTvbcGePikfcYZGLPsfJe", "address": "754iyTDY8xUtZJZfheSYLUn7jvCkxr79RcbjMt81QykC/96bCoxn8XorTQmVMDrMfi5afmXFSUKUjSGbFGcDUuRaJ", "op": "metabase DELETE"}
Oct 09 16:10:05 titan4 neofs-node[717444]: info        log/log.go:12        local object storage operation        {"shard_id": "FvTvbcGePikfcYZGLPsfJe", "address": "754iyTDY8xUtZJZfheSYLUn7jvCkxr79RcbjMt81QykC/96bCoxn8XorTQmVMDrMfi5afmXFSUKUjSGbFGcDUuRaJ", "op": "metabase DELETE"}
Oct 09 16:11:05 titan4 neofs-node[717444]: info        log/log.go:12        local object storage operation        {"shard_id": "FvTvbcGePikfcYZGLPsfJe", "address": "754iyTDY8xUtZJZfheSYLUn7jvCkxr79RcbjMt81QykC/96bCoxn8XorTQmVMDrMfi5afmXFSUKUjSGbFGcDUuRaJ", "op": "metabase DELETE"}
Oct 09 16:12:05 titan4 neofs-node[717444]: info        log/log.go:12        local object storage operation        {"shard_id": "FvTvbcGePikfcYZGLPsfJe", "address": "754iyTDY8xUtZJZfheSYLUn7jvCkxr79RcbjMt81QykC/96bCoxn8XorTQmVMDrMfi5afmXFSUKUjSGbFGcDUuRaJ", "op": "metabase DELETE"}
Oct 09 16:13:05 titan4 neofs-node[717444]: info        log/log.go:12        local object storage operation        {"shard_id": "FvTvbcGePikfcYZGLPsfJe", "address": "754iyTDY8xUtZJZfheSYLUn7jvCkxr79RcbjMt81QykC/96bCoxn8XorTQmVMDrMfi5afmXFSUKUjSGbFGcDUuRaJ", "op": "metabase DELETE"}
```

## Possible Solution
Fix something.

## Steps to Reproduce (for bugs)
Put an object with expiration, see how it goes after the epoch change.

## Context
Testnet. New epoch ticks do not affect the behavior. A restarted node doesn't have this.

## Regression
Looks like, #3522.

## Your Environment
* Version used: 0.49.0
* Server setup and configuration:
```
    gc:
      remover_batch_size: 100
      remover_sleep_interval: 1m
```
* Operating System and version (`uname -a`): Debian oldstable

### PR DESCRIPTION
**Pull request by End-rey**
Closes #3629.

### CODE REVIEW

File: pkg/local_object_storage/engine/inhume.go [hunk 1]
```diff
@@ -241,6 +252,64 @@ func (e *StorageEngine) processAddrDelete(addr oid.Address, deleteFunc func(*sha
...
 
+func (e *StorageEngine) processSplitObjectWithNoLink(addr oid.Address, si *objectSDK.SplitInfo) []oid.Address {
+	var children []oid.Address
+	e.log.Info("root object has no link object in split upload",
+		zap.Stringer("addrBeingInhumed", addr))
+
+	var (
+		fs        objectSDK.SearchFilters
+		newCursor []byte
+		count     = uint16(10)
```
Comment (roman-khimov) [inline pkg/local_object_storage/engine/inhume.go]: Doesn't make much sense limiting to 10 here, we need all elements anyway so you can use 1000 which is a normal search limit.

**Review by roman-khimov — APPROVED** [review]

File: pkg/local_object_storage/engine/inhume.go [hunk 2]
```diff
@@ -241,6 +252,67 @@ func (e *StorageEngine) processAddrDelete(addr oid.Address, deleteFunc func(*sha
 	return retErr
 }
 
+func (e *StorageEngine) processSplitObjectWithNoLink(addr oid.Address, si *objectSDK.SplitInfo) []oid.Address {
+	var children []oid.Address
```
Comment (cthulhu-rider) [inline pkg/local_object_storage/engine/inhume.go]: merge into var block

File: pkg/local_object_storage/engine/inhume.go [hunk 3]
```diff
@@ -241,6 +252,67 @@ func (e *StorageEngine) processAddrDelete(addr oid.Address, deleteFunc func(*sha
 	return retErr
 }
 
+func (e *StorageEngine) processSplitObjectWithNoLink(addr oid.Address, si *objectSDK.SplitInfo) []oid.Address {
```
Comment (cthulhu-rider) [inline pkg/local_object_storage/engine/inhume.go]:
```suggestion
func (e *StorageEngine) collectChildrenWithoutLink(addr oid.Address, si *objectSDK.SplitInfo) []oid.Address {
```
to be more specific

File: pkg/local_object_storage/engine/inhume.go [hunk 4]
```diff
@@ -241,6 +252,67 @@ func (e *StorageEngine) processAddrDelete(addr oid.Address, deleteFunc func(*sha
...
+		if err != nil {
+			e.log.Error("cannot preprocess search query for split-chain",
+				zap.Stringer("firstID", firstID),
+				zap.Stringer("addrBeingInhumed", addr),
+				zap.Error(err))
+			break
+		}
+		res, newCursor, err = e.Search(cnr, fss, nil, cursor, count)
+		if err != nil {
+			e.log.Error("cannot search for first part of split-chain",
```
Comment (cthulhu-rider) [inline pkg/local_object_storage/engine/inhume.go]: we can search by split ID
