### PR TITLE
cli: fix timeout can expire before RPC

### LINKED ISSUE #3279: neofs-cli starts keeping track of time before RPC is done
neofs-cli has a timeout for almost every operation, it is supposed to be a remote execution timeout. However timer starts ticking as the first operation in the cli: https://github.com/nspcc-dev/neofs-node/blob/69ee0fec4f94402198fd8ff408a18634ba2ab8d5/cmd/neofs-cli/modules/object/get.go#L46 makes reading password, files from FS, etc part of the execution. As a result, RPC may start with already expired context, exiting cli with a confusing message (it has not even tried to make RPC): `can't create API client: can't init SDK client: write request: open gRPC connection: gRPC dial: context deadline exceeded`

## Expected Behavior
Timeout is for operation being transferred to remote server.

## Current Behavior
Timeout may expire even if a user is only preparing cli for making RPC.

## Possible Solution
Read state first, init context with deadline then.

## Steps to Reproduce (for bugs)
Do not provide timeout flag, do not enter password for 15+ seconds, press enter, see message (and do not see if enter is pressed earlier that 15s).

### PR DESCRIPTION
**Pull request by End-rey**
Closes #3279.

### CODE REVIEW

File: cmd/neofs-cli/modules/accounting/balance.go [hunk 1]
```diff
@@ -42,6 +40,7 @@ var accountingBalanceCmd = &cobra.Command{
 			return fmt.Errorf("can't decode owner ID wallet address: %w", idUser.DecodeString(balanceOwner))
 		}
 
+		ctx := context.Background()
```
Comment (roman-khimov) [inline cmd/neofs-cli/modules/accounting/balance.go:43]: No timeout for this command?

Comment (End-rey) [reply cmd/neofs-cli/modules/accounting/balance.go:43]: It wasn't there initially. Add it?

Comment (roman-khimov) [reply cmd/neofs-cli/modules/accounting/balance.go:43]: Yeah, it's an additional fix in its essence, but it'd be nice to do while we're here.

File: cmd/neofs-cli/modules/accounting/balance.go [hunk 2]
```diff
@@ -40,7 +39,9 @@ var accountingBalanceCmd = &cobra.Command{
 			return fmt.Errorf("can't decode owner ID wallet address: %w", idUser.DecodeString(balanceOwner))
 		}
 
-		ctx := context.Background()
+		ctx, cancel := commonflags.GetCommandContext(cmd)
```
Comment (roman-khimov) [inline cmd/neofs-cli/modules/accounting/balance.go:42]: Needs to be mentioned in changelog as well.

**Review by roman-khimov — COMMENTED** [review]
OK otherwise
