### PR TITLE
Fix bugs with removing split objects

### LINKED ISSUE #3026: Expired lock test fails occasionaly
## Expected Behavior
Green.

## Current Behavior
https://rest.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/2136-1732220712/index.html#suites/295ed2e000f8fa6f3ade59cc13b98615/6deb00ef86b7dc66/
https://rest.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/2136-1732221029/index.html#suites/295ed2e000f8fa6f3ade59cc13b98615/c49306c8063b4d85/

It fails at the waiting stage, all iterations returns the object.

## Possible Solution
Needs to be investigated, either it's a test issue (not giving enough time for things to settle) or it's a bug. From the first glance it looks as a bug.

## Steps to Reproduce (for bugs)
Run tests.object.test_object_lock.TestObjectLockWithGrpc#test_expired_object_should_be_deleted_after_locks_are_expired 

## Your Environment
* Version used: any recent master
* Server setup and configuration:
* Operating System and version (`uname -a`):

### PR DESCRIPTION
**Pull request by End-rey**
Fix #3026.

For bug about expired objects that aren't deleted after locks expire, there's also a simpler solution - [here](https://github.com/nspcc-dev/neofs-node/blob/8b65833d3651185fd9078e36b5acac73b1eaf762/pkg/local_object_storage/shard/gc.go#L121) make it consistently: handle expired locks and then handle expired objects. But really I don't like this, because the parallelism in the calculations is lost, and the logic for deleting the locks may still be wrong.

### CODE REVIEW

File: pkg/local_object_storage/engine/inhume.go [hunk 1]
```diff
@@ -264,14 +265,24 @@ func (e *StorageEngine) processExpiredObjects(addrs []oid.Address) {
 }
 
 func (e *StorageEngine) processExpiredLocks(lockers []oid.Address) {
+	var unlocked []oid.Address
 	for _, sh := range e.unsortedShards() {
-		sh.HandleExpiredLocks(lockers)
+		unlocked = append(unlocked, sh.HandleExpiredLocks(lockers)...)
```
Comment (roman-khimov) [inline pkg/local_object_storage/engine/inhume.go:270]: Can be a huge list IIUC.

File: pkg/local_object_storage/engine/inhume.go [hunk 2]
```diff
@@ -300,3 +311,28 @@ func oIDsToAddresses(cID cid.ID, oo []oid.ID) []oid.Address {
...
+
+// handleUnlockedObjects filters out unlocked objects by lockers for expiration
+// and marks them for removal.
+func (e *StorageEngine) handleUnlockedObjects(unlocked []oid.Address) error {
+	var expired []oid.Address
+	for _, sh := range e.unsortedShards() {
+		expired = append(expired, sh.FilterExpired(unlocked)...)
+	}
+
+	addrs := util.SliceToMap(expired)
```
Comment (roman-khimov) [inline pkg/local_object_storage/engine/inhume.go:323]: Why do you need a map here?

File: pkg/local_object_storage/engine/inhume.go [hunk 3]
```diff
@@ -300,3 +311,28 @@ func oIDsToAddresses(cID cid.ID, oo []oid.ID) []oid.Address {
...
+
+	for addr := range addrs {
+		ok, err := e.inhumeAddr(addr, false, nil, 0)
+		if err != nil {
+			e.log.Warn("could not inhume object in shard", zap.Error(err))
+			return err
```
Comment (roman-khimov) [inline pkg/local_object_storage/engine/inhume.go:329]: Save error, continue looping?

**Review by roman-khimov — COMMENTED** [review]
Looks legit.

File: pkg/local_object_storage/engine/inhume.go (hunk 2 above)
Comment (End-rey) [reply pkg/local_object_storage/engine/inhume.go:323]: I thought there would be repetitions.

File: pkg/local_object_storage/engine/inhume.go (hunk 1 above)
Comment (End-rey) [reply pkg/local_object_storage/engine/inhume.go:270]: So, do we need to filter this right away? I can do an internal loop on the shards for filtering. Can there be many shards?

File: pkg/local_object_storage/engine/inhume.go (hunk 3 above)
Comment (End-rey) [reply pkg/local_object_storage/engine/inhume.go:329]: I did the same like here:
https://github.com/nspcc-dev/neofs-node/blob/8b65833d3651185fd9078e36b5acac73b1eaf762/pkg/local_object_storage/engine/inhume.go#L54-L60

File: pkg/local_object_storage/engine/inhume.go (hunk 2 above)
Comment (roman-khimov) [reply pkg/local_object_storage/engine/inhume.go:323]: Shouldn't be, I think. But you can sort it in-place and skip duplicates as well, should be a little cheaper than creating a new map.

Comment (carpawell) [reply pkg/local_object_storage/engine/inhume.go]: in fact i looked at `lockSingle` and it really looks like repetitions should appear

File: pkg/local_object_storage/engine/inhume.go [hunk 4]
```diff
@@ -264,14 +264,35 @@ func (e *StorageEngine) processExpiredObjects(addrs []oid.Address) {
...
 	for _, sh := range e.unsortedShards() {
-		sh.HandleExpiredLocks(lockers)
+		unlocked = sh.HandleExpiredLocks(lockers)
+		for _, sh2 := range e.unsortedShards() {
+			expired = append(expired, sh2.FilterExpired(unlocked)...)
+		}
+	}
+	ss := []string{}
+	for _, addr := range expired {
+		ss = append(ss, addr.String())
```
Comment (carpawell) [inline pkg/local_object_storage/engine/inhume.go:276]: `zap.Stringers`?

File: pkg/local_object_storage/engine/inhume.go [hunk 5]
```diff
@@ -264,14 +264,35 @@ func (e *StorageEngine) processExpiredObjects(addrs []oid.Address) {
...
+	}
+	e.log.Debug("expired objects", zap.Strings("addrs", ss))
```
Comment (carpawell) [inline pkg/local_object_storage/engine/inhume.go:278]: can we extend the message a little? i would like to know that we are handling "new" expired objects after some locks were dropped

**Comment by End-rey** [comment]
Improved the debug message, added the removal of repetitions.

**Review by carpawell — APPROVED** [review]
