### PR TITLE
[SUPPORT] Fix/Helper object broadcasting

### LINKED ISSUE #1972: unexpected message when trying to delete locked object
When I am trying to delete locked object getting unexpected message:
`rpc error: remove object via client: status: code = 1024 message = incomplete object PUT by placement: could not close object stream: (*putsvc.remoteTarget) could not put object to [/dns4/node1.neofs/tcp/8080]: write object via client: status: code = 2050 message = object is locked`

When trying to rerun the command getting the different error message:
`rpc error: remove object via client: status: code = 2052 message = object already removed`

## Expected Behavior
The following message should be displayed while the object is locked:
`rpc error: remove object via client: status: code = 2050 message = object is locked`

## Steps to Reproduce (for bugs)

1. Create  container
 `neofs-cli container create --basic-acl public-read-write  -r node1.neofs:8080 -w /etc/neofs/storage/wallet.json -p "REP 1"`
2. allocate 500m object and put to the container:
`neofs-cli --rpc-endpoint node1.neofs:8080 -w /etc/neofs/storage/wallet.json object put --file /etc/neofs/storage/object1 --cid 32nNgCJCG6e3aZX178oWVYAJvpHiZ2XP8wkN6msrtujT`
3. Issue container nodes command: `neofs-cli container nodes --cid 32nNgCJCG6e3aZX178oWVYAJvpHiZ2XP8wkN6msrtujT -r node1.neofs:8080 -w /etc/neofs/storage/wallet.json`
  Output:
```
Rep 1
        Node 1: 02df711d9f69027f4e299fa64fa87e984435d36eb5076146d9677ecd1d1d7cfe2f ONLINE /dns4/node4.neofs/tcp/8080
                Continent: Europe
                Country: Finland
                CountryCode: FI
                Deployed: YACZROKH
                Location: Helsinki (Helsingfors)
                Node: node4
                Price: 10
                SubDiv: Uusimaa
                SubDivCode: 18
                UN-LOCODE: FI HEL
        Node 2: 03de248780d29f80cb15418822ef206e6acae22c50d9428172376cbb9768594b37 ONLINE /dns4/node3.neofs/tcp/8080
                Continent: Europe
                Country: Sweden
                CountryCode: SE
                Deployed: YACZROKH
                Location: Stockholm
                Node: node3
                Price: 10
                SubDiv: Stockholms l�n
                SubDivCode: AB
                UN-LOCODE: SE STO
        Node 3: 02665dba76c7326948536ff98bdf936ebf7e8f7fe5f35622e40ace93ea48775836 ONLINE /dns4/node1.neofs/tcp/8080
                Continent: Europe
                Country: Russia
                CountryCode: RU
                Deployed: YACZROKH
                Location: Moskva
                Node: node1
                Price: 10
                SubDiv: Moskva
                SubDivCode: MOW
                UN-LOCODE: RU MOW
```
5. Issue object lock: 
```
neofs-cli object lock -r node1.neofs:8080 -w /etc/neofs/storage/wallet.json --expire-at 38 32nNgCJCG6e3aZX178oWVYAJvpHiZ2XP8wkN6msrtujT EfTM8kj1JkFwJqvCsruo1DFKKMBBhg5RsW6HZSEf8sXq
    Lock object ID: CBZ5DUVJNsVN7qvBewNkoYT8gN9yfn8Fn3QfK8WMvoi1
    Objects successfully locked.
```
6.  Try to issue "object delete" to node1 (got the expected result):
```
root@az:/etc/neofs/storage/tatlin-object-sber-tfstate/vkarakozov# neofs-cli --rpc-endpoint node1.neofs:8080 -w /etc/neofs/storage/wallet.json object delete --cid 32nNgCJCG6e3aZX178oWVYAJvpHiZ2XP8wkN6msrtujT --oid EfTM8kj1JkFwJqvCsruo1DFKKMBBhg5RsW6HZSEf8sXq
Enter password >
rpc error: remove object via client: status: code = 2050 message = object is locked

```
7. Try to issue "object delete" to node2 (**fails with unexpected message**):
```
root@az:/etc/neofs/storage/tatlin-object-sber-tfstate/vkarakozov# neofs-cli --rpc-endpoint node2.neofs:8080 -w /etc/neofs/storage/wallet.json object delete --cid 32nNgCJCG6e3aZX178oWVYAJvpHiZ2XP8wkN6msrtujT --oid EfTM8kj1JkFwJqvCsruo1DFKKMBBhg5RsW6HZSEf8sXq
Enter password >
rpc error: remove object via client: status: code = 1024 message = incomplete object PUT by placement: could not close object stream: (*putsvc.remoteTarget) could not put object to [/dns4/node3.neofs/tcp/8080]: write object via client: status: code = 2050 message = object is locked
```
8. Try to issue one more time the command in step7:
```
root@az:/etc/neofs/storage/tatlin-object-sber-tfstate/vkarakozov# neofs-cli --rpc-endpoint node2.neofs:8080 -w /etc/neofs/storage/wallet.json object delete --cid 32nNgCJCG6e3aZX178oWVYAJvpHiZ2XP8wkN6msrtujT --oid EfTM8kj1JkFwJqvCsruo1DFKKMBBhg5RsW6HZSEf8sXq
Enter password >
rpc error: remove object via client: status: code = 2052 message = object already removed

```
9. Try to issue "object delete" to node3 / node4 (got the expected results):
```
root@az:/etc/neofs/storage/tatlin-object-sber-tfstate/vkarakozov# neofs-cli --rpc-endpoint node3.neofs:8080 -w /etc/neofs/storage/wallet.json object delete --cid 32nNgCJCG6e3aZX178oWVYAJvpHiZ2XP8wkN6msrtujT --oid EfTM8kj1JkFwJqvCsruo1DFKKMBBhg5RsW6HZSEf8sXq
Enter password >
rpc error: remove object via client: status: code = 2050 message = object is locked
root@az:/etc/neofs/storage/tatlin-object-sber-tfstate/vkarakozov# neofs-cli --rpc-endpoint node4.neofs:8080 -w /etc/neofs/storage/wallet.json object delete --cid 32nNgCJCG6e3aZX178oWVYAJvpHiZ2XP8wkN6msrtujT --oid EfTM8kj1JkFwJqvCsruo1DFKKMBBhg5RsW6HZSEf8sXq
Enter password >
rpc error: remove object via client: status: code = 2050 message = object is locked
```
[Attached logs](https://github.com/nspcc-dev/neofs-node/files/9862482/locked_object_delete.zip)

## Your Environment

NeoFS Storage node
Version: v0.33.0-31-ge1be0180
GoVersion: go1.18.4

### PR DESCRIPTION
**Pull request by carpawell**
Closes #1972.

Includes:
1. CLI `object lock`'s `lifetime` flag fix;
2. Changing broadcasting logic: a node does not save object relations if it is not in the object's container. I did not find any usage of that, but it disallows correct object handling: putting a TS record to a storage of a node that does not belong to the container skips any lock object checks (it just does not have any helper objects of the container) and does not have any reasons. @fyrchik, @cthulhu-rider, please, double-check that.

### CODE REVIEW

**Comment by acid-ant** [comment]
I've tested scenario from #1973 with your changes and it seems to fix it. But when I tried to delete locked object from node2, which stored on node1, in error message we have only status code which indicates that object locked instead of human readable message:
```
@:~/workspace/neofs-dev-env$ neofs-cli --rpc-endpoint s02.neofs.devenv:8080 --wallet wallets/wallet.json object delete --cid 3kAdxaa5zPXFoXM1vkC6NhFzDwoBYPUY4r6Sw1YtRXuo --oid 5fvMyXMThjGckucKzZuADkeGSmMcoPn8eepXZdL6f4bZ
Enter password > 
rpc error: remove object via client: status: code = 1024 message = incomplete object PUT by placement: could not close object stream: (*putsvc.remoteTarget) could not put object to [/dns4/s01.neofs.devenv/tcp/8080]: write object via client: status: code = 1024 message = incomplete object PUT by placement: could not close object stream: could not delete objects from tombstone locally: status: code = 2050
```

File: pkg/core/object/fmt_test.go [hunk 1]
```diff
@@ -133,31 +135,40 @@ func TestFormatValidator_Validate(t *testing.T) {
...
 		data, err = content.Marshal()
 		require.NoError(t, err)
 
 		obj.SetPayload(data)
 
-		require.NoError(t, v.ValidateContent(obj)) // all good
+		contentGot, err := v.ValidateContent(obj)
+		require.NoError(t, err) // all good
+
+		require.EqualValues(t, []oid.ID{id}, contentGot.Objects())
```
Comment (fyrchik) [inline pkg/core/object/fmt_test.go:152]: Also check type?

**Review by fyrchik — DISMISSED** [review]

File: pkg/core/object/fmt_test.go (hunk 1 above)
Comment (carpawell) [reply pkg/core/object/fmt_test.go:152]: added

**Review by fyrchik — APPROVED** [review]
