### PR TITLE
Fix/Do not require MainNet attributes in `WITHOUT_MAINNET` mode

### LINKED ISSUE #663: Inner Ring requires neofs and processing contracts when running without main chain
## Expected Behavior
NeoFS Inner Ring node does not require NeoFS and Processing contract hashes when running in `WITHOUT_MAINNET` mode.

## Current Behavior
```
$ docker logs ir01 -f
ir: can't read neofs script-hash: expected string size of 40 got 0
```

## Steps to Reproduce (for bugs)

1. Disable main chain in Inner Ring config: `NEOFS_IR_WITHOUT_MAINNET=true`
2. Remove `NEOFS_IR_CONTRACTS_NEOFS` and `NEOFS_IR_CONTRACTS_PROCESSING` from config.

## Your Environment
neofs-node v0.22.0

### PR DESCRIPTION
**Pull request by carpawell**
If `WITHOUT_MAINNET` environmental variable is
`true`:
- Do not read `NeoFS` and `processing`
script-hashes from envs;
- Do not init Governance processor;
- Do not init NeoFS processor.

Clarify tag section in release instruction.

Closes #663.

### CODE REVIEW

File: pkg/innerring/innerring.go [hunk 1]
```diff
@@ -828,19 +830,29 @@ func createClient(ctx context.Context, p *chainParams, notaryOpts ...client.Nota
 	)
 }
 
-func parseContracts(cfg *viper.Viper) (*contracts, error) {
+func parseContracts(cfg *viper.Viper, withOutMainNet bool) (*contracts, error) {
```
Comment (alexvanin) [inline pkg/innerring/innerring.go:833]: without is a single word, not withOut :smiley:

**Review by alexvanin — APPROVED** [review]

File: pkg/innerring/innerring.go (hunk 1 above)
Comment (carpawell) [reply pkg/innerring/innerring.go:833]: wow, a strange reflex of my fingers

fixed
