### PR TITLE
object/acl: check session token verb

### LINKED ISSUE #1191: Verb of object session token is not checked
_Originally posted by @KirillovDenis_

Verb of the session token attached to the object request should correspond to  the operation.

## Expected Behavior
Storage nodes denies request with wrong token verb.

## Current Behavior
Request is processed.

## Possible solution
Node can:

1. Deny the request.
2. Ignore session token and process the request without it.

IMO 1. is more clear.

## Steps to Reproduce (for bugs)

1. Attach session token with verb other than the object request one.
2. Send the request.
3. Receive `OK` status.

## Your Environment

* Version used: v0.27.5

### PR DESCRIPTION
**Pull request by fyrchik**
Close #1191 .
Signed-off-by: Evgenii Stratonikov <evgeniy@nspcc.ru>

### CODE REVIEW

File: pkg/services/object/acl/acl.go [hunk 1]
```diff
@@ -459,8 +460,12 @@ func (b Service) findRequestInfo(
 		return info, ErrUnknownRole
 	}
 
-	// find verb from token if it is present
-	verb := sourceVerbOfRequest(req, op)
+	// Check if session token verb is equal to the current operation.
+	// Unknown means everything is allowed.
+	verb := sourceVerbOfRequest(req.token, op)
+	if verb != op {
```
Comment (alexvanin) [inline pkg/services/object/acl/acl.go:466]: Unfortunately, we can't simply compare op and value from token. One request type can produce requests of other type. During the tests, I logged such errors:
```
token: DELETE  op: PUT
token: DELETE  op: HEAD
token: GETRANGEHASH  op: GETRANGE
```

We also have this table in [spec](https://nspcc.ru/upload/neofs-spec-latest.pdf#page=28) of produced request types.
| Base/Gen | PUT | DELETE | HEAD | RANGE | GET | HASH | SEARCH |
|----------|:---:|:------:|:----:|:-----:|:---:|:----:|:------:|
| PUT      | +   | -      | -    | -     | -   | -    | -      |
| DELETE   | +   | -      | +    | -     | -   | -    | +      |
| HEAD     | -   | -      | +    | -     | -   | -    | -      |
| RANGE    | -   | -      | +    | +     | -   | -    | -      |
| GET      | -   | -      | +    | -     | +   | -    | -      |
| HASH     | -   | -      | +    | +     | -   | -    | -      |
| SEARCH   | -   | -      | -    | -     | -   | -    | +      |

**Review by alexvanin — CHANGES_REQUESTED** [review]

File: pkg/services/object/acl/acl.go [hunk 2]
```diff
@@ -459,8 +460,12 @@ func (b Service) findRequestInfo(
 		return info, ErrUnknownRole
 	}
 
-	// find verb from token if it is present
-	verb := sourceVerbOfRequest(req, op)
+	// Check if session token verb is equal to the current operation.
+	// Unknown means everything is allowed.
```
Comment (alexvanin) [inline pkg/services/object/acl/acl.go:464]: Also, can you fix API spec and mention such behavior [there](https://github.com/nspcc-dev/neofs-api/blob/650c367529c6fe6b215ea8d5f183b07b4ac8f9a9/session/types.proto#L40)?

File: pkg/services/object/acl/acl.go (hunk 1 above)
Comment (fyrchik) [reply pkg/services/object/acl/acl.go:466]: Fixed.

**Review by alexvanin — APPROVED** [review]
