### PR TITLE
object: Allow self-signed session tokens

### LINKED ISSUE #2288: TestNet replication fails
TestNet nodes couldn't replicate following object from public container:
```
`error replicator/process.go:62 could not replicate object {"component": "Object Replicator", "node": "03000a222431891c481f2fbce61297547e816e164750f5ea94e2831c219bbe3504", "object": "GqNR1XtkucMcxE86FtALjVUSFVREa9ZMF2fbmeXEffJV/JDbZcmiZWCXRocjHU6i9ZHqJZzTDrhk2HEET33vxJJ6s", "error": "(*putsvc.RemoteSender) could not send object: (*putsvc.remoteTarget) could not put object to [/dns4/st4.t5.fs.neo.org/tcp/8080]: write object via client: status: code = 1024 message = (*object.FormatValidator) different owner identifiers NfFA5g92e32YvraVmipA9oY8AjvbdgFdjY/NTBbJxp2PrPXS7XyhKVqroifvsp1QCttif"}`
```

* related to #2226
* related to #2228

### PR DESCRIPTION
**Pull request by cthulhu-rider**
* related #2226
* closes #2288

This should fix TestNet replication problem.

### CODE REVIEW

File: pkg/core/object/fmt.go [hunk 1]
```diff
@@ -147,28 +145,11 @@ func (v *FormatValidator) validateSignatureKey(obj *object.Object) error {
 		return fmt.Errorf("decode public key: %w", err)
 	}
 
-	token := obj.SessionToken()
-
-	if token == nil || !token.AssertAuthKey(&key) {
-		return v.checkOwnerKey(*obj.OwnerID(), key)
```
Comment (roman-khimov) [inline pkg/core/object/fmt.go:153]: This raises two questions:
 * when objects in a public container are replicated, we routinely have signatures from different keys (not container owner key), how this is controlled wrt EACL? One object can be created when this is allowed to happen (EACL rule allowing PUT for a key exists), then rules might change. We want to replicate the first object, but if a malicious node creates an object signed by some random keys and tries to replicate it this shouldn't be possible. Granted, this is not exactly a session token problem, but it's related.
 * won't this change break `token == nil` case? random keys signing objects are not good, maybe we have a private container.

**Comment by roman-khimov** [comment]
CHANGELOG conflict, rebase pls.

File: pkg/core/object/fmt.go (hunk 1 above)
Comment (cthulhu-rider) [reply pkg/core/object/fmt.go:153]: One big pile of problems is that NeoFS doesn't distinguish object creation and regular transmission like replication. Such a division of operations would clearly improve access management and prevent potential vulnerabilities in the form of malicious data generation by storage nodes.

`token == nil` condition removal doesn't break IAM since it is contolled on the other layer. Technically, object owner may be any according to the protocol and specification.

**Review by roman-khimov — APPROVED** [review]
