### PR TITLE
object/put: fix concurrent PUT data corruption

### LINKED ISSUE #2978: Panic in binary replication
```
окт 23 14:47:46 metis3 neofs-node[2911]: 2024/10/23 14:47:46.517936 [ants]: worker exits from panic: runtime error: slice bounds out of range [109:0]
окт 23 14:47:46 metis3 neofs-node[2911]: goroutine 340953791 [running]:
окт 23 14:47:46 metis3 neofs-node[2911]: runtime/debug.Stack()
окт 23 14:47:46 metis3 neofs-node[2911]:         runtime/debug/stack.go:24 +0x5e
окт 23 14:47:46 metis3 neofs-node[2911]: github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
окт 23 14:47:46 metis3 neofs-node[2911]:         github.com/panjf2000/ants/v2@v2.9.0/worker.go:56 +0x85
окт 23 14:47:46 metis3 neofs-node[2911]: panic({0x1102a00?, 0xc02d60d9c8?})
окт 23 14:47:46 metis3 neofs-node[2911]:         runtime/panic.go:770 +0x132
окт 23 14:47:46 metis3 neofs-node[2911]: github.com/nspcc-dev/neofs-node/pkg/services/object/put.putObjectLocally({0x13fc108, 0xc00033e930}, 0xc072bb18c0, {0x12827d10?, {0x0?, 0xc00d581d30?, 0xc>
окт 23 14:47:46 metis3 neofs-node[2911]:         github.com/nspcc-dev/neofs-node/pkg/services/object/put/local.go:80 +0x34d
окт 23 14:47:46 metis3 neofs-node[2911]: github.com/nspcc-dev/neofs-node/pkg/services/object/put.(*localTarget).Close(0xc0331a59d0)
окт 23 14:47:46 metis3 neofs-node[2911]:         github.com/nspcc-dev/neofs-node/pkg/services/object/put/local.go:51 +0x4f
окт 23 14:47:46 metis3 neofs-node[2911]: github.com/nspcc-dev/neofs-node/pkg/services/object/put.(*distributedTarget).sendObject(0xc03357a800, {0x1, {{0xc032dfb7b0, 0x1, 0x1}, {0x0, 0x0, 0x0}, {>
окт 23 14:47:46 metis3 neofs-node[2911]:         github.com/nspcc-dev/neofs-node/pkg/services/object/put/distributed.go:208 +0x162
окт 23 14:47:46 metis3 neofs-node[2911]: github.com/nspcc-dev/neofs-node/pkg/services/object/put.(*distributedTarget).iteratePlacement.func1()
окт 23 14:47:46 metis3 neofs-node[2911]:         github.com/nspcc-dev/neofs-node/pkg/services/object/put/distributed.go:250 +0x11c
окт 23 14:47:46 metis3 neofs-node[2911]: github.com/panjf2000/ants/v2.(*goWorker).run.func1()
окт 23 14:47:46 metis3 neofs-node[2911]:         github.com/panjf2000/ants/v2@v2.9.0/worker.go:67 +0x8d
окт 23 14:47:46 metis3 neofs-node[2911]: created by github.com/panjf2000/ants/v2.(*goWorker).run in goroutine 340954422
окт 23 14:47:46 metis3 neofs-node[2911]:         github.com/panjf2000/ants/v2@v2.9.0/worker.go:48 +0x5c
```

## Expected Behavior
No panic

## Current Behavior
Panic

## Possible Solution
Do not do out of range?

## Steps to Reproduce (for bugs)
Not sure, some high load with blocks that @AnnaShaleva and @AliceInHunterland usually do.

## Context
Loading neo-go blocks to NeoFS.

## Your Environment
NeoFS Storage node
Version: 0.43.0 
GoVersion: go1.22.6

### PR DESCRIPTION
**Pull request by carpawell**
If ants pool is busy and cannot take task, early `return` without `wg.Wait()`
leads to `iterateNodesForObject`'s `return` and all the buffers for binary
replication from now may be reused while are still in use by the other routines
inside the pool. Wait for WG before any `return` is called. Closes https://github.com/nspcc-dev/neofs-node/issues/2978, https://github.com/nspcc-dev/neofs-node/issues/2988,
https://github.com/nspcc-dev/neofs-node/issues/2975, https://github.com/nspcc-dev/neofs-node/issues/2971.

### CODE REVIEW

**Comment by carpawell** [comment]
Also we can try node one more time (`j--`).

File: pkg/services/object/put/distributed.go [hunk 1]
```diff
@@ -331,7 +331,7 @@ func (x placementIterator) iterateNodesForObject(obj oid.ID, f func(nodeDesc) er
 					if e, _ := lastRespErr.Load().(error); e != nil {
 						err = fmt.Errorf("%w (last node error: %w)", err, e)
 					}
-					return errIncompletePut{singleErr: err}
+					wg.Wait()
```
Comment (roman-khimov) [inline pkg/services/object/put/distributed.go:334]: So we'll always return `nil` here? This doesn't seem to be correct.

**Review by roman-khimov — COMMENTED** [review]
For now let's just fix the bug without any behavioral changes. This code can and will be improved, but that's a bit different story.

**Comment by roman-khimov** [comment]
Also, be more aggressive with "close XXX", we have a number of issues here.

File: pkg/services/object/put/distributed.go (hunk 1 above)
Comment (cthulhu-rider) [reply pkg/services/object/put/distributed.go:334]: 2 changes are mixed in one. Wait to fix data race - ok, but cotinuing the loop changes the behavior

**Comment by carpawell** [comment]
@roman-khimov, added issues for my taste.

File: pkg/services/object/put/distributed.go (hunk 1 above)
Comment (roman-khimov) [reply pkg/services/object/put/distributed.go:334]: Looks like we can omit the `return` really, this will be handled. And not mess with `err` here as well.

Comment (roman-khimov) [reply pkg/services/object/put/distributed.go:334]: We can even not `wg.Wait()` then (it's done below anyway).

Comment (carpawell) [reply pkg/services/object/put/distributed.go:334]: > we can omit the return really

i need a final solution. you refused mine (or not?), then what should we do here?

> We can even not wg.Wait() then (it's done below anyway).

yes but then we immediately try the next node, which i probably useless since i expect pool overload with disk operations to be longer than the next `for` iteration

**Review by roman-khimov — APPROVED** [review]

**Comment by roman-khimov** [comment]
Test needs to be fixed.

**Comment by carpawell** [comment]
Also, added one more test.

**Review by roman-khimov — APPROVED** [review]
