### PR TITLE
(SUPPORT) FIx object GET_RANGE panic

### LINKED ISSUE #2007: get_range/get_range_hash with out of bounds throws file_not_found or EOF exceptions instead of out of range
Sometimes get_range and get_range_hash requests with out of bounds --range parameter returns "object not found" exception instead of "out of range"

## Expected Behavior
```
neofs-cli --config wallet_config.yml object hash --wallet 'fb0a1cf9-62d8-462d-a73e-f5718599b15d.json' --cid '4zMtoHgPnFe2fhfj2BqWyJus9N49Zta3hHZLYgtJuZY9' --oid 'A4j6bdbQeLX6gzjZFdVRcLiWvS8fNAKbPe3vofCLUkhf' --range '1001:10'
Error:
return code: 1
output: rpc error: read payload hashes via client: status: code = 2053 message = out of range
```

## Current Behavior
File not found:
```
neofs-cli --config wallet_config.yml object hash --wallet 'fb0a1cf9-62d8-462d-a73e-f5718599b15d.json' --cid '4zMtoHgPnFe2fhfj2BqWyJus9N49Zta3hHZLYgtJuZY9' --oid 'A4j6bdbQeLX6gzjZFdVRcLiWvS8fNAKbPe3vofCLUkhf' --range '1001:10'
Error:
return code: 1
output: rpc error: read payload hashes via client: status: code = 2049 message = object not found
```
EOF:
```
neofs-cli --config wallet_config.yml object hash --wallet '385f73fa-5d6a-41e2-b356-203e5e1e9150.json' --cid '5azT2GeRKLzGrnVmQ4z3vxSKayeQLbgmQM9aKV6r57CR' --oid '2K3qkKk8k2tNvisz8qbS8sgQ7bhpXk9hmLJPaDKRedKe' --range '10:18446744073709551615'
RETCODE: 1

STDOUT:
rpc error: read payload hashes via client: write request: rpc error: code = Unavailable desc = error reading from server: EOF
STDERR:
```

Failures:
EOF:
https://obj-jenkins.spb.yadro.com/view/Ready%20to%20use/job/sbercloud_test/147/allure/#suites/1aa4749d1babf458baceeb848afce143/9bbe35f376020bb7/

FILE_NOT_FOUND:
https://obj-jenkins.spb.yadro.com/view/Ready%20to%20use/job/sbercloud_test/144/allure/#suites/1aa4749d1babf458baceeb848afce143/388134d232b14b9a/
Passes:
https://obj-jenkins.spb.yadro.com/view/Ready%20to%20use/job/sbercloud_test/142/allure/#suites/1aa4749d1babf458baceeb848afce143/e7686ec36972e23e/

## Steps to Reproduce (for bugs)
1. Put file
2. Get_range with out_of_bounds --range param

## Your Environment
Sber-cloud: v0.1.1-nb-20221024.1

### PR DESCRIPTION
**Pull request by fyrchik**
Close #2007

### CODE REVIEW

File: pkg/services/object/internal/client/client.go [hunk 1]
```diff
@@ -316,6 +317,10 @@ func (x PayloadRangeRes) PayloadRange() []byte {
 	return x.data
 }
 
+// maxInitialBufferSize is the maximum initial buffer size for PayloadRange result.
+// On one side we don't want to reallocate a lot, on the other --
```
Comment (carpawell) [inline pkg/services/object/internal/client/client.go:321]: what does `--` mean?

Comment (fyrchik) [reply pkg/services/object/internal/client/client.go:321]: It is a dash.

Comment (fyrchik) [reply pkg/services/object/internal/client/client.go]: Forgot another line, fixed the description.
