### PR TITLE
writecache: make migration on init

### LINKED ISSUE #3185: SIGSEGV
```
Feb 28 05:30:09 titan2 systemd[1]: Started neofs-storage.service - NeoFS Storage node.
Feb 28 05:30:12 titan2 neofs-node[733758]: info        client/multi.go:53        connection to RPC node has been established        {"endpoint": "wss://rpc.morph.t5.fs.neo.org/ws"}
Feb 28 05:30:14 titan2 neofs-node[733758]: info        neofs-node/main.go:81        initializing prometheus service...
Feb 28 05:30:14 titan2 neofs-node[733758]: info        neofs-node/main.go:94        prometheus service is initialized
Feb 28 05:30:14 titan2 neofs-node[733758]: info        neofs-node/main.go:81        initializing pprof service...
Feb 28 05:30:14 titan2 neofs-node[733758]: info        neofs-node/main.go:157        starting prometheus service...
Feb 28 05:30:14 titan2 neofs-node[733758]: info        neofs-node/main.go:94        pprof service is initialized
Feb 28 05:30:14 titan2 neofs-node[733758]: info        neofs-node/main.go:118        initializing control service...
Feb 28 05:30:14 titan2 neofs-node[733758]: info        neofs-node/main.go:157        starting pprof service...
Feb 28 05:30:14 titan2 neofs-node[733758]: info        neofs-node/main.go:120        control service has been successfully initialized
Feb 28 05:30:14 titan2 neofs-node[733758]: info        neofs-node/main.go:157        starting control service...
Feb 28 05:30:14 titan2 neofs-node[733758]: info        neofs-node/storage.go:55        shard attached to engine        {"id": "3epiyqEtrw5AB2v8NJV7mD"}
Feb 28 05:30:14 titan2 neofs-node[733758]: info        neofs-node/main.go:118        initializing gRPC service...
Feb 28 05:30:14 titan2 neofs-node[733758]: info        neofs-node/main.go:120        gRPC service has been successfully initialized
Feb 28 05:30:14 titan2 neofs-node[733758]: info        neofs-node/main.go:118        initializing container service...
Feb 28 05:30:14 titan2 neofs-node[733758]: info        neofs-node/main.go:120        container service has been successfully initialized
Feb 28 05:30:14 titan2 neofs-node[733758]: info        neofs-node/main.go:118        initializing storage engine service...
Feb 28 05:30:14 titan2 neofs-node[733758]: info        writecache/writecache.go:202        migrating database        {"shard_id": "3epiyqEtrw5AB2v8NJV7mD", "path": "/srv/neofs/meta/writecache/small.bolt"}
Feb 28 05:30:14 titan2 neofs-node[733758]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 28 05:30:14 titan2 neofs-node[733758]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xcd0412]
Feb 28 05:30:14 titan2 neofs-node[733758]: goroutine 1 [running]:
Feb 28 05:30:14 titan2 neofs-node[733758]: github.com/klauspost/compress/zstd.(*Encoder).MaxEncodedSize(0x18?, 0xc0002becc0?)
Feb 28 05:30:14 titan2 neofs-node[733758]:         github.com/klauspost/compress@v1.17.9/zstd/encoder.go:591 +0x12
Feb 28 05:30:14 titan2 neofs-node[733758]: github.com/nspcc-dev/neofs-node/pkg/local_object_storage/blobstor/compression.(*Config).Compress(0xc000227c00, {0x7f25f2f26089, 0x483, 0x483})
Feb 28 05:30:14 titan2 neofs-node[733758]:         github.com/nspcc-dev/neofs-node/pkg/local_object_storage/blobstor/compression/compress.go:99 +0x45
Feb 28 05:30:14 titan2 neofs-node[733758]: github.com/nspcc-dev/neofs-node/pkg/local_object_storage/blobstor/fstree.(*FSTree).Put(0xc000227b90, {{0x16, 0x84, 0xa3, 0x9c, 0x5e, 0x60, 0xf2, 0xba, 0x26, ...}, ...}, ...)
Feb 28 05:30:14 titan2 neofs-node[733758]:         github.com/nspcc-dev/neofs-node/pkg/local_object_storage/blobstor/fstree/fstree.go:337 +0x186
Feb 28 05:30:14 titan2 neofs-node[733758]: github.com/nspcc-dev/neofs-node/pkg/local_object_storage/blobstor.(*BlobStor).Put(0xc000227c00, {{0x16, 0x84, 0xa3, 0x9c, 0x5e, 0x60, 0xf2, 0xba, 0x26, ...}, ...}, ...)
Feb 28 05:30:14 titan2 neofs-node[733758]:         github.com/nspcc-dev/neofs-node/pkg/local_object_storage/blobstor/put.go:40 +0x315
Feb 28 05:30:14 titan2 neofs-node[733758]: github.com/nspcc-dev/neofs-node/pkg/local_object_storage/writecache.(*cache).flushObject(0xc0016a77a0, 0xc00016a600, {0x7f25f2f26089?, 0x483?, 0xc00016a600?})
Feb 28 05:30:14 titan2 neofs-node[733758]:         github.com/nspcc-dev/neofs-node/pkg/local_object_storage/writecache/flush.go:152 +0x1d0
Feb 28 05:30:14 titan2 neofs-node[733758]: github.com/nspcc-dev/neofs-node/pkg/local_object_storage/writecache.(*cache).migrate.func1.1({0x7f25f2f26030?, 0x10?, 0x10?}, {0x7f25f2f26089, 0x483, 0x483})
Feb 28 05:30:14 titan2 neofs-node[733758]:         github.com/nspcc-dev/neofs-node/pkg/local_object_storage/writecache/writecache.go:233 +0xd5
Feb 28 05:30:14 titan2 neofs-node[733758]: go.etcd.io/bbolt.(*Bucket).ForEach(0xc00177a018?, 0xc0002bf798)
Feb 28 05:30:14 titan2 neofs-node[733758]:         go.etcd.io/bbolt@v1.3.11/bucket.go:397 +0x90
Feb 28 05:30:14 titan2 neofs-node[733758]: github.com/nspcc-dev/neofs-node/pkg/local_object_storage/writecache.(*cache).migrate.func1(0xca?)
Feb 28 05:30:14 titan2 neofs-node[733758]:         github.com/nspcc-dev/neofs-node/pkg/local_object_storage/writecache/writecache.go:219 +0x9b
Feb 28 05:30:14 titan2 neofs-node[733758]: go.etcd.io/bbolt.(*DB).View(0xc0017423c0?, 0xc0002bf940)
Feb 28 05:30:14 titan2 neofs-node[733758]:         go.etcd.io/bbolt@v1.3.11/db.go:917 +0x72
Feb 28 05:30:14 titan2 neofs-node[733758]: github.com/nspcc-dev/neofs-node/pkg/local_object_storage/writecache.(*cache).migrate(0xc0016a77a0)
Feb 28 05:30:14 titan2 neofs-node[733758]:         github.com/nspcc-dev/neofs-node/pkg/local_object_storage/writecache/writecache.go:212 +0x276
Feb 28 05:30:14 titan2 neofs-node[733758]: github.com/nspcc-dev/neofs-node/pkg/local_object_storage/writecache.(*cache).Open(0xc0016a77a0, 0x0)
Feb 28 05:30:14 titan2 neofs-node[733758]:         github.com/nspcc-dev/neofs-node/pkg/local_object_storage/writecache/writecache.go:154 +0x106
Feb 28 05:30:14 titan2 neofs-node[733758]: github.com/nspcc-dev/neofs-node/pkg/local_object_storage/shard.(*Shard).Open(0xc00175c000)
Feb 28 05:30:14 titan2 neofs-node[733758]:         github.com/nspcc-dev/neofs-node/pkg/local_object_storage/shard/control.go:53 +0x194
Feb 28 05:30:14 titan2 neofs-node[733758]: github.com/nspcc-dev/neofs-node/pkg/local_object_storage/engine.(*StorageEngine).open(0xc000227b20)
Feb 28 05:30:14 titan2 neofs-node[733758]:         github.com/nspcc-dev/neofs-node/pkg/local_object_storage/engine/control.go:23 +0x10e
Feb 28 05:30:14 titan2 neofs-node[733758]: github.com/nspcc-dev/neofs-node/pkg/local_object_storage/engine.(*StorageEngine).Open(...)
Feb 28 05:30:14 titan2 neofs-node[733758]:         github.com/nspcc-dev/neofs-node/pkg/local_object_storage/engine/control.go:15
Feb 28 05:30:14 titan2 neofs-node[733758]: main.initApp.func1(0xc00035a008)
Feb 28 05:30:14 titan2 neofs-node[733758]:         github.com/nspcc-dev/neofs-node/cmd/neofs-node/main.go:130 +0x26
Feb 28 05:30:14 titan2 neofs-node[733758]: main.initAndLog(0xc00035a008, {0x11871fa, 0xe}, 0x12927d8)
Feb 28 05:30:14 titan2 neofs-node[733758]:         github.com/nspcc-dev/neofs-node/cmd/neofs-node/main.go:119 +0x9c
Feb 28 05:30:14 titan2 neofs-node[733758]: main.initApp(0xc00035a008)
Feb 28 05:30:14 titan2 neofs-node[733758]:         github.com/nspcc-dev/neofs-node/cmd/neofs-node/main.go:129 +0x90
Feb 28 05:30:14 titan2 neofs-node[733758]: main.main()
Feb 28 05:30:14 titan2 neofs-node[733758]:         github.com/nspcc-dev/neofs-node/cmd/neofs-node/main.go:62 +0x32f
```

### PR DESCRIPTION
**Pull request by End-rey**
Closes #3185.

I checked and in this case `encoder` is not nil.

### CODE REVIEW

File: pkg/local_object_storage/writecache/writecache.go [hunk 1]
```diff
@@ -146,26 +146,26 @@ func (c *cache) Open(readOnly bool) error {
...
+}
+
+// Init runs necessary services. No-op in read-only mode.
+func (c *cache) Init() error {
+	c.modeMtx.Lock()
+	defer c.modeMtx.Unlock()
+
 	// Migration part
-	if readOnly {
+	if c.readOnly() {
```
Comment (cthulhu-rider) [inline pkg/local_object_storage/writecache/writecache.go:158]: two `if` conditions are about the same, lets merge

**Review by cthulhu-rider — APPROVED** [review]

File: pkg/local_object_storage/writecache/writecache.go [hunk 2]
```diff
@@ -146,26 +146,26 @@ func (c *cache) Open(readOnly bool) error {
 	}
 	c.modeMtx.Unlock()
 
+	return c.initCounters()
```
Comment (cthulhu-rider) [inline pkg/local_object_storage/writecache/writecache.go:149]: do counters needed before `Init`?

File: CHANGELOG.md [hunk 3]
```diff
@@ -7,6 +7,7 @@ Changelog for NeoFS Node
 
 ### Fixed
 - Zero range denial by `neofs-cli object range|hash` commands (#3182)
+- Not all the components needed for migration were initialized (#3186)
```
Comment (roman-khimov) [inline CHANGELOG.md:10]: write cache migration
