### PR TITLE
Fix/drop control call

### LINKED ISSUE #2822: Dropping object via control service leaves traces in the metabase
## Expected Behavior
`neofs-cli control drop-objects` removing all data about the object from the node.

## Current Behavior
Apparently, some traces are still left in the metabase after it, this:
```
Apr 20 04:09:14 titan4 neofs-node[420363]: 2024-04-20T04:09:14.760Z warn shard/gc.go:339 iterator over expired locks failed {"shard_id": "2N1drpyfAuTXes7ShXUAF4", "error": "could not parse expiration epoch: strconv.ParseUint: parsing "'or'1'='1": invalid syntax"}
```
only ends with metabase resync (broken object is deleted via drop-objects).

## Possible Solution
Clean up _all_ metabase data on `drop-objects`.

## Steps to Reproduce (for bugs)
Add some broken object (likely not that easy now), delete it, see that GC is still broken.

## Context
Testnet.

## Your Environment
* Version used: 0.41.0

### PR DESCRIPTION
**Pull request by carpawell**
Overall, should close #2822, hard to say, there were many commits merged about it, and "problem" objects are already dropped.

### CODE REVIEW

File: pkg/local_object_storage/engine/delete.go [hunk 1]
```diff
@@ -58,102 +55,25 @@ func (e *StorageEngine) delete(prm DeletePrm) (DeleteRes, error) {
...
-		if err != nil {
-			e.log.Warn("error during searching for object children",
-				zap.Stringer("addr", addr),
-				zap.String("error", err.Error()))
-			return false
-		}
-
-		for _, addr := range res.AddressList() {
-			inhumePrm.MarkAsGarbage(addr)
+	_, err := e.inhumeAddr(prm.addr, inhumePrm)
```
Comment (roman-khimov) [inline pkg/local_object_storage/engine/delete.go:76]: Looks like it was a bit more efficient previously with _sorted_ shards.

File: pkg/local_object_storage/engine/delete.go [hunk 2]
```diff
@@ -58,102 +55,25 @@ func (e *StorageEngine) delete(prm DeletePrm) (DeleteRes, error) {
...
-
-		resExists, err := sh.Exists(existsPrm)
-		if err != nil {
-			if shard.IsErrRemoved(err) || shard.IsErrObjectExpired(err) {
-				return true
-			}
-
-			var splitErr *objectSDK.SplitInfoError
-			if !errors.As(err, &splitErr) {
-				if !shard.IsErrNotFound(err) {
```
Comment (roman-khimov) [inline pkg/local_object_storage/engine/delete.go:82]: This one differs from the two implementations.

File: pkg/local_object_storage/metabase/delete.go [hunk 3]
```diff
@@ -141,25 +130,15 @@ func (db *DB) deleteGroup(tx *bbolt.Tx, addrs []oid.Address, sizes []uint64) (ui
...
-			}
-		}
-	}
-
 	return rawDeleted, availableDeleted, nil
 }
 
-// delete removes object indexes from the metabase. Counts the references
-// of the object that is being removed.
+// delete removes object indexes from the metabase.
```
Comment (roman-khimov) [inline pkg/local_object_storage/metabase/delete.go:138]: So, you're relying on engine to drop every object from the metabase now, right?

File: pkg/local_object_storage/engine/delete.go (hunk 1 above)
Comment (carpawell) [reply pkg/local_object_storage/engine/delete.go:76]: why do you think it is unsorted now?

File: pkg/local_object_storage/engine/delete.go (hunk 2 above)
Comment (carpawell) [reply pkg/local_object_storage/engine/delete.go:82]: yes, that is the key of my suggestion: why do we differ this logic? we do the same things (and one may always have more or less num of bugs) when delete/inhume objects, why some of them should be collected (if an object is a big one) one way while the other should be handled differently? about this PR: i have improved and fixed a little `Inhume` some time ago and could not understand why i had do it again one more time when looking at `Delete`

File: pkg/local_object_storage/metabase/delete.go [hunk 4]
```diff
@@ -103,7 +104,8 @@ func (db *DB) deleteGroup(tx *bbolt.Tx, addrs []oid.Address, sizes []uint64) (ui
 	for i := range addrs {
 		removed, available, size, err := db.delete(tx, addrs[i], currEpoch)
 		if err != nil {
-			return 0, 0, err // maybe log and continue?
+			db.log.Warn("failed to delete object", zap.Error(err), zap.Stringer("addr", addrs[i]))
+			return 0, 0, nil
```
[the remark this answers is not in the document]
Comment (carpawell) [reply pkg/local_object_storage/metabase/delete.go:108]: sounds reasonable, will change

File: pkg/local_object_storage/metabase/delete.go (hunk 3 above)
Comment (carpawell) [reply pkg/local_object_storage/metabase/delete.go:138]: yes, that is the point. i started to think that "complex" logic should be done on the engine level and that is why the engine exists. If a metabase is trying to handle parts/parents that it may lose (resync or it just never saw any part with parent header), there are always some problems. that is what i want to discuss and open another issue if any needed

File: pkg/local_object_storage/engine/delete.go (hunk 1 above)
Comment (roman-khimov) [reply pkg/local_object_storage/engine/delete.go:76]:
```
        e.iterateOverUnsortedShards(func(sh hashedShard) (stop bool) {
```
in `inhumeAddr`

Comment (carpawell) [reply pkg/local_object_storage/engine/delete.go:76]: you mean [this](https://github.com/nspcc-dev/neofs-node/blob/0e4f7c919e712ca77e7ce15140599de0e644bb69/pkg/local_object_storage/engine/inhume.go#L150)? it is root object handling, there is no information about link and last objects that can be acquired via root object's ID

File: pkg/local_object_storage/metabase/delete.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (roman-khimov) [reply pkg/local_object_storage/metabase/delete.go:108]: Anything changed here?

[the remark this answers is not in the document]
Comment (carpawell) [reply pkg/local_object_storage/metabase/delete.go:108]: a regular simple change, the other threads worries me more. but ok, fixed

File: pkg/local_object_storage/metabase/delete.go [hunk 5]
```diff
@@ -116,6 +127,12 @@ func (db *DB) deleteGroup(tx *bbolt.Tx, addrs []oid.Address, sizes []uint64) (ui
 		}
 	}
 
+	if firstErr != nil {
+		all := uint64(len(addrs))
+		success := all - errorCount
+		return 0, 0, fmt.Errorf("deleted %d out of %d objects, first error: %w", success, all, firstErr)
```
Comment (cthulhu-rider) [inline pkg/local_object_storage/metabase/delete.go:133]: lets mention best effort also in `Delete` docs?

File: pkg/local_object_storage/engine/delete.go [hunk 6]
```diff
@@ -58,102 +55,25 @@ func (e *StorageEngine) delete(prm DeletePrm) (DeleteRes, error) {
...
-
-		var shPrm shard.InhumePrm
-		shPrm.MarkAsGarbage(prm.addr)
-		if prm.forceRemoval {
-			shPrm.ForceRemoval()
-		}
-
-		_, err = sh.Inhume(shPrm)
+	if !prm.forceRemoval {
+		locked, err := e.IsLocked(prm.addr)
```
Comment (cthulhu-rider) [inline pkg/local_object_storage/engine/delete.go:59]:
```suggestion
		locked, err := e.isLocked(prm.addr)
```
no need to acquire `blockExec` mutex again

File: pkg/local_object_storage/metabase/delete.go [hunk 7]
```diff
@@ -105,16 +96,25 @@ func (db *DB) Delete(prm DeletePrm) (DeleteRes, error) {
...
+	var errorCount uint64
+	var firstErr error
 
 	for i := range addrs {
-		removed, available, size, err := db.delete(tx, addrs[i], refCounter, currEpoch)
+		removed, available, size, err := db.delete(tx, addrs[i], currEpoch)
 		if err != nil {
-			return 0, 0, err // maybe log and continue?
+			errorCount++
+			err = fmt.Errorf("%s object delete fail: %w", addrs[i], err)
```
Comment (cthulhu-rider) [inline pkg/local_object_storage/metabase/delete.go:110]: this makes no sense for errors after the 1st: only needed for the log, and it will contain a tautology then. Suggest
```
db.log.Warn("failed to delete object", zap.Stringer("addr", addres[i]), zap.Error(err))
if firstErr == nil {
  err = fmt.Errorf("%s object delete fail: %w", addrs[i], err)
}
```

File: pkg/local_object_storage/metabase/delete.go [hunk 8]
```diff
@@ -127,6 +127,12 @@ func (db *DB) deleteGroup(tx *bbolt.Tx, addrs []oid.Address, sizes []uint64) (ui
 		}
 	}
 
+	if firstErr != nil {
+		all := uint64(len(addrs))
```
Comment (cthulhu-rider) [inline pkg/local_object_storage/metabase/delete.go:131]: `var errorCount int` and no cast and temp vars  needed

**Review by cthulhu-rider — COMMENTED** [review]
5b6b5a4ad54abe224a88fdc16c6fae07d665a3e2 explains its changes by 6bf698489acc1313eafffb189ea13e2ef7e5ac55, maybe just squash them then?

**Comment by carpawell** [comment]
> 5b6b5a4 explains its changes by 6bf6984, maybe just squash them then?

I prefer a couple of commits. The first one makes `Delete` work as `Inhume`, and the second drops no-op code since the previous change. IMO, they are read better this way.

**Comment by cthulhu-rider** [comment]
> the second drops no-op code

i thought that `Delete` code became less optimal after the 1st. If just no-op, then yeah - separate commits are much better

File: pkg/local_object_storage/engine/delete.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (cthulhu-rider) [reply pkg/local_object_storage/engine/delete.go:76]: >  i could not recall why we have them separated

no reason mentioned #1461

> it scares me

on the contrary, this inspires me to break duality and merge them

[the remark this answers is not in the document]
Comment (carpawell) [reply pkg/local_object_storage/engine/delete.go:76]: > this inspires me to break duality and merge them

me too. consider the whole PR as a suggestion, the PR can be extended, more issues can be opened, etc. an option (`force`) looks more reliable than having two methods

> no reason mentioned #1461

it was always like `Delete` + `Inhume` and a lot of changes were made, so i think it is a little complex to find a reason (and it is not worth it, imo)

**Review by cthulhu-rider — APPROVED** [review]

**Comment by carpawell** [comment]
> @carpawell worth changelog? the issue occurred in the pub network

Not sure I can find correct words about the whole PR. But if you are about the original issue, we may add it, yes.
