### PR TITLE
object/get: fix that object can't be got without a link object

### LINKED ISSUE #3275: Object can't be constructed without a corresponding link object
https://github.com/nspcc-dev/neofs-testcases/pull/1015 (test_object_can_be_get_without_link_object)

1. Upload a complex object
2. Get a corresponding link object
3. Remove the link object via `neofs-cli control drop-objects` from all SNs
4. Try to get the original complex object - expect success, got failure.

This is the flipping failure, locally always passes, in github - 50/50.

### PR DESCRIPTION
**Pull request by End-rey**
Closes #3275.

Is it a proper decision?

### CODE REVIEW

File: pkg/services/object/get/get.go [hunk 1]
```diff
@@ -110,6 +112,9 @@ func (exec *execCtx) analyzeStatus(execCnr bool) {
 	case statusVIRTUAL:
 		exec.log.Debug("requested object is virtual")
 		exec.assemble()
+		if errors.Is(exec.err, apistatus.ErrObjectNotFound) {
+			exec.analyzeStatus(execCnr)
```
Comment (roman-khimov) [inline pkg/services/object/get/get.go:116]: This can lead to infinite recursion, suppose you can't get some object's part -- you'd get the same "not found" error and will retry indefinitely.

File: pkg/services/object/get/assembly_v2.go [hunk 2]
```diff
@@ -57,6 +57,8 @@ func (exec *execCtx) processV2Link(linkID oid.ID) bool {
 	linkObj, ok := exec.getChild(linkID, nil, true)
 	if !ok {
 		exec.log.Debug("failed to read link object")
+		exec.status = statusNotFound
+		exec.err = apistatus.ErrObjectNotFound
 		return false
```
Comment (roman-khimov) [inline pkg/services/object/get/assembly_v2.go:62]: But why `processV2Split()` doesn't handle this `false` correctly already? It's supposed to handle link object problems, `true` is returned when the status from `processV2Link` is final and `false` is returned when we should fallback to chain processing.

**Comment by End-rey** [comment]
I didn't find any other good way to get the last part, except through the `executeOnContainer`, because the part lies on one of the nodes. Is there any other way?

File: pkg/services/object/get/get.go [hunk 3]
```diff
@@ -110,6 +111,11 @@ func (exec *execCtx) analyzeStatus(execCnr bool) {
 	case statusVIRTUAL:
 		exec.log.Debug("requested object is virtual")
 		exec.assemble()
+		if errors.Is(exec.err, errNoLinkNoLastPart) && execCnr {
+			exec.err = nil
```
Comment (cthulhu-rider) [inline pkg/services/object/get/get.go:115]: does this instruction affect anything?

Comment (roman-khimov) [reply pkg/services/object/get/get.go:115]: I think it can be relevant for the next execute/analyze cycle. In successful case `errNoLinkNoLastPart` can remain there.

Comment (carpawell) [reply pkg/services/object/get/get.go:115]: tbh, i would expect to keep this err as a local result and be overwritten by remote results if any

Comment (End-rey) [reply pkg/services/object/get/get.go:115]: Initially, it was supposed to save from endless execution, but now it's not so important.

Comment (carpawell) [reply pkg/services/object/get/get.go:115]: > In successful case errNoLinkNoLastPart can remain there.

every successful case should overwrite status and nils the error: https://github.com/nspcc-dev/neofs-node/blob/4ab3a9a5c8183d65c7a0086748b889f3ca32957b/pkg/services/object/get/remote.go#L37-L38

Comment (cthulhu-rider) [reply pkg/services/object/get/get.go:115]: i think we should not do this. `execCnr` operand prevent endless looping, while

> In successful case errNoLinkNoLastPart can remain there.

must never happen cuz this would be a problem to me, and this line must not hide it

**Review by cthulhu-rider — APPROVED** [review]

**Review by carpawell — APPROVED** [review]
