### PR TITLE
Fix/Do not return expired objects

### LINKED ISSUE #1617: Check expiration on `Get`/`GetRange`/etc
Now there is a gap b/w `NewEpoch` event and an object expiration (marking with GCMark). It leads to confusing behavior: the object is expired but still available until GC comes and marks it as garbage.

We could check the expiration on every "get" request.

### PR DESCRIPTION
**Pull request by carpawell**
Closes #1617.

### CODE REVIEW

File: pkg/local_object_storage/metabase/exists.go [hunk 1]
```diff
@@ -52,7 +57,7 @@ func (db *DB) Exists(prm ExistsPrm) (res ExistsRes, err error) {
 
 func (db *DB) exists(tx *bbolt.Tx, addr oid.Address) (exists bool, err error) {
 	// check graveyard first
-	switch inGraveyard(tx, addr) {
+	switch objectStatus(tx, addr, db.epochState.CurrentEpoch()) {
```
Comment (fyrchik) [inline pkg/local_object_storage/metabase/exists.go:60]: Calling this inside the transaction can introduce unexpected logical errors: `CurrentEpoch` can return different values inside a single transaction. Can we provide this as a parameter instead?

File: pkg/local_object_storage/metabase/exists.go [hunk 2]
```diff
@@ -86,14 +93,50 @@ func (db *DB) exists(tx *bbolt.Tx, addr oid.Address) (exists bool, err error) {
...
+
+	// bucket with objects that have expiration attr
+	expirationBucket := tx.Bucket(attributeBucketName(addr.Container(), objectV2.SysAttributeExpEpoch))
+	if expirationBucket != nil {
+		// bucket that contains objects that expire in the current epoch
+		currEpochBkt := expirationBucket.Bucket([]byte(strconv.FormatUint(currEpoch, 10)))
+		if currEpochBkt != nil {
+			// we can do nothing with errors from db
+			// => consider object as not expired
+			_ = currEpochBkt.ForEach(func(k, _ []byte) error {
```
Comment (fyrchik) [inline pkg/local_object_storage/metabase/exists.go:120]: Why simple `Get` doesn't work?

File: pkg/local_object_storage/metabase/exists.go [hunk 3]
```diff
@@ -86,14 +93,50 @@ func (db *DB) exists(tx *bbolt.Tx, addr oid.Address) (exists bool, err error) {
...
+
+	if expired {
+		return 3
+	}
+
 	graveyardBkt := tx.Bucket(graveyardBucketName)
 	garbageBkt := tx.Bucket(garbageBucketName)
+
 	addrKey := addressKey(addr)
+
```
Comment (fyrchik) [inline pkg/local_object_storage/metabase/exists.go:139]: unrelated to the commit

File: pkg/local_object_storage/metabase/exists.go (hunk 2 above)
Comment (fyrchik) [reply pkg/local_object_storage/metabase/exists.go:120]: Also, storage errors _should_ be returned to the caller.

File: pkg/local_object_storage/metabase/exists.go [hunk 4]
```diff
@@ -86,14 +93,50 @@ func (db *DB) exists(tx *bbolt.Tx, addr oid.Address) (exists bool, err error) {
...
+	// expired previously for less than the one epoch duration
+
+	rawOID := []byte(addr.Object().EncodeToString())
+	var expired bool
+
+	// bucket with objects that have expiration attr
+	expirationBucket := tx.Bucket(attributeBucketName(addr.Container(), objectV2.SysAttributeExpEpoch))
+	if expirationBucket != nil {
+		// bucket that contains objects that expire in the current epoch
+		currEpochBkt := expirationBucket.Bucket([]byte(strconv.FormatUint(currEpoch, 10)))
```
Comment (fyrchik) [inline pkg/local_object_storage/metabase/exists.go:116]: What about the objects that expired in the previous epoch?

File: pkg/local_object_storage/writecache/init.go [hunk 5]
```diff
@@ -63,7 +67,15 @@ func (c *cache) isFlushed(addr oid.Address) bool {
 	existsPrm.SetAddress(addr)
 
 	mRes, err := c.metabase.Exists(existsPrm)
-	if err != nil || !mRes.Exists() {
+	if err != nil {
+		if errors.Is(err, object.ErrObjectIsExpired) || errors.As(err, new(apistatus.ObjectAlreadyRemoved)) {
+			return true
+		}
+
+		return false
```
Comment (fyrchik) [inline pkg/local_object_storage/writecache/init.go:75]: `return errors.Is ...` ?

File: pkg/local_object_storage/metabase/db.go [hunk 6]
```diff
@@ -322,3 +322,10 @@ func WithMaxBatchDelay(d time.Duration) Option {
 		}
 	}
 }
+
+// WithEpochState return option to specify a source of current epoch height.
```
[the remark this answers is not in the document]
Comment (carpawell) [reply pkg/local_object_storage/metabase/db.go:326]: moved that change to the previous commit

File: pkg/local_object_storage/metabase/exists.go (hunk 1 above)
Comment (carpawell) [reply pkg/local_object_storage/metabase/exists.go]: sure, fixed (although it required many changes in private methods)

File: pkg/local_object_storage/metabase/exists.go (hunk 2 above)
Comment (carpawell) [reply pkg/local_object_storage/metabase/exists.go]: > Why simple Get doesn't work?

no idea, fixed

> Also, storage errors should be returned to the caller.

yes, but that func returns just `uint8`. fixed to `Get` call anyway

File: pkg/local_object_storage/metabase/exists.go (hunk 3 above)
Comment (carpawell) [reply pkg/local_object_storage/metabase/exists.go]: ok, removed that new lines

File: pkg/local_object_storage/metabase/exists.go (hunk 4 above)
Comment (carpawell) [reply pkg/local_object_storage/metabase/exists.go:115]: i've added comment to that func:

```
// we check only if the object is expired in the current
// epoch since it is considered the only corner case: the
// GC is expected to collect all the objects that have
// expired previously for less than the one epoch duration
```

i expect that GC is able to collect all the expired objects in one epoch (one hour currently), so the only problem objects are the object that expire in the current epoch but have not been collected by the GC yet. theoretically, we could check more than one epoch (we do not have index that could say what objects are expired, only the objects that has *exact* expiration epoch), so we should know how deep to check OR we should add new expiration index

i thought about force new epoch event that could lead to some problems. we may add some threshold for that cases (e.g. check if an object was not expired in the last `5` epoch)

what do you think?

File: pkg/local_object_storage/metabase/delete.go [hunk 7]
```diff
@@ -89,7 +90,7 @@ func (db *DB) delete(tx *bbolt.Tx, addr oid.Address, refCounter referenceCounter
 	}
 
 	// unmarshal object, work only with physically stored (raw == true) objects
-	obj, err := db.get(tx, addr, false, true)
+	obj, err := db.get(tx, addr, false, true, currEpoch)
```
Comment (fyrchik) [inline pkg/local_object_storage/metabase/delete.go:93]: How do we ever delete expired object from the metabase?

Comment (carpawell) [reply pkg/local_object_storage/metabase/delete.go:93]: third arg (`false` here) controls checking object status. if an object is presented, it will be deleted, despite its status

**Comment by KirillovDenis** [comment]
Resolve conflicts please

File: pkg/local_object_storage/metabase/db.go [hunk 8]
```diff
@@ -311,3 +322,10 @@ func WithMaxBatchDelay(d time.Duration) Option {
...
+func WithEpochState(s epochState) Option {
```
Comment (cthulhu-rider) [inline pkg/local_object_storage/metabase/db.go:327]: `epochState` is needed to be exported.

**Review by cthulhu-rider — DISMISSED** [review]

File: pkg/local_object_storage/metabase/db.go (hunk 8 above)
Comment (carpawell) [reply pkg/local_object_storage/metabase/db.go]: fixed

**Review by cthulhu-rider — APPROVED** [review]
