### PR TITLE
Set CreationEpoch field value for new objects

### LINKED ISSUE #60: Object pipeline doesn't set creation_epoch field in object.
## Expected Behavior
New objects have non zero `creation_epoch` field. 

## Current Behavior
Objects have zero in `creation_epoch` field.

## Steps to Reproduce
1. Put object.
2. Head object.
3. Check `creation_epoch` field.

### PR DESCRIPTION
**Pull request by cthulhu-rider**
Closes #60.

### CODE REVIEW

File: cmd/neofs-node/netmap.go [hunk 1]
```diff
@@ -29,6 +50,11 @@ func initNetmapService(c *cfg) {
 			),
 		),
 	)
+
+	c.cfgNetmap.state = newNetworkState()
+	addNewEpochNotificationHandler(c, func(ev event.Event) {
+		c.cfgNetmap.state.setCurrentEpoch(ev.(netmapEvent.NewEpoch).EpochNumber())
+	})
```
Comment (alexvanin) [inline cmd/neofs-node/netmap.go:57]: One more thing: update network state with epoch value from sidechain at `bootstrapNode()` function. This way node will be ready to create objects right from the start.

Comment (cthulhu-rider) [reply cmd/neofs-node/netmap.go:57]: What component and function should I use in `bootstrapNode`?

Comment (alexvanin) [reply cmd/neofs-node/netmap.go:57]: I think network map wrapper missing `Epoch` method implementation to get current epoch value. Fix it and then invoke this method in `bootstrapNode()`. 

```go
epoch := c.cfgNetmap.wrapper.Epoch()
c.cfgNetmap.state.setCurrentEpoch(epoch)
```

**Review by alexvanin — APPROVED** [review]
