### PR TITLE
fix/Restart SN services after `neo-go` is down

### LINKED ISSUE #1337: Restart services after switching to another neo-go RPC node
After #1170 node connects to the Morph via WS connection only and it supports node switching without application restart. However, during the switching process, it could lose some notifications that may change the node's state. We can implement some syncing callback [call](https://github.com/nspcc-dev/neofs-node/blob/v0.28.0-rc.3/pkg/morph/client/multi.go#L142) but it is not fully clear what that callback should do and do we really need that sync (may the node be placed in a totally incorrect state because of losing some morph notifications?).

### PR DESCRIPTION
**Pull request by carpawell**
Closes #1337. The https://github.com/nspcc-dev/neofs-node/pull/2406 but for SN. Also tested with https://github.com/notimetoname/neofs-dev-env/tree/local/add-rpc-morph-node.

### CODE REVIEW

File: cmd/neofs-node/main.go [hunk 1]
```diff
@@ -152,3 +152,37 @@ func shutdown(c *cfg) {
...
+		return nil
+	}
+
+	err = c.bootstrap()
+	if err != nil {
+		c.log.Warn("can't send re-bootstrap tx", zap.Error(err))
+	}
+
+	// drop expired sessions if any has appeared while node was sleeping
+	c.shared.privateTokenStore.RemoveOld(epoch)
```
Comment (cthulhu-rider) [inline cmd/neofs-node/main.go:183]: looks very specific, are you sure that this is and will be the only part that needs to be updated? to me `start` and `restart` aren't so different: `start` starts from "undefined" epoch while `restart` from the cached one.

File: cmd/neofs-node/main.go [hunk 2]
```diff
@@ -152,3 +152,37 @@ func shutdown(c *cfg) {
...
+	// way to make a heartbeat so nothing is wrong in the making sure a
+	// node is online (if it should be)
+
+	if !c.needBootstrap() || c.cfgNetmap.reBoostrapTurnedOff.Load() {
+		return nil
+	}
+
+	err = c.bootstrap()
+	if err != nil {
+		c.log.Warn("can't send re-bootstrap tx", zap.Error(err))
```
Comment (cthulhu-rider) [inline cmd/neofs-node/main.go:179]: `failed to re-bootstrap`, specific reason is in the `err` context i hope

File: cmd/neofs-node/main.go (hunk 1 above)
Comment (carpawell) [reply cmd/neofs-node/main.go:183]: can you elaborate on your thoughts?

i look through the whole code and there is not that much code that caches smth. every other client user (in the node, i mean) just calls the methods and does everything it needs without caching

there are not that many "services" in the node in fact. storage is the main but [we cannot stop](https://github.com/nspcc-dev/neofs-node/issues/1337#issuecomment-1514791288) it, cause it would be like restarting the whole node

Comment (cthulhu-rider) [reply cmd/neofs-node/main.go:183]: i imagine any component (e.g. not yet added) which reacts the epoch change. Don't we forget to pass `epoch` to this component here? 

talking about `privateTokenStore`: we have this logical binding
https://github.com/nspcc-dev/neofs-node/blob/e5ac376c7081669fbb59c79e68cfd8eb208ccc2a/cmd/neofs-node/session.go#L49-L51

and u add new case when we handle exact epoch. Don't u think it'd be nice to have single binding of `privateTokenStore`  and new epochs?

**Review by roman-khimov — APPROVED** [review]

File: cmd/neofs-node/main.go (hunk 1 above)
Comment (cthulhu-rider) [reply cmd/neofs-node/main.go:183]: okay, lets leave it as it is for now

and i'd think about single epoch controller for the node as a possible enhancement (smart controller orchestrating ordinary components)

**Review by cthulhu-rider — APPROVED** [review]

**Review by cthulhu-rider — APPROVED** [review]
