### PR TITLE
Do not require shard config in relay mode

### LINKED ISSUE #969: doesn't work wo shards in relay mode
```
panic: no shard configured
goroutine 1 [running]:
github.com/nspcc-dev/neofs-node/cmd/neofs-node/config/engine.IterateShards(0xc00006ff00, 0xc0002c1b38)
        github.com/nspcc-dev/neofs-node/cmd/neofs-node/config/engine/config.go:28 +0x569
main.initShardOptions(0xc000246000)
        github.com/nspcc-dev/neofs-node/cmd/neofs-node/config.go:359 +0x77
main.initLocalStorage(0xc000246000)
        github.com/nspcc-dev/neofs-node/cmd/neofs-node/config.go:319 +0x45
main.initCfg(0x7ffd7da0feef, 0x1e, 0x2)
        github.com/nspcc-dev/neofs-node/cmd/neofs-node/config.go:309 +0xe8a
main.main()
        github.com/nspcc-dev/neofs-node/cmd/neofs-node/main.go:52 +0x14f
```

### PR DESCRIPTION
**Pull request by cthulhu-rider**
Closes #969.

### CODE REVIEW

**Review by 532910 — APPROVED** [review]

**Review by alexvanin — APPROVED** [review]

File: cmd/neofs-node/config.go [hunk 1]
```diff
@@ -367,7 +367,9 @@ func initLocalStorage(c *cfg) {
 func initShardOptions(c *cfg) {
 	var opts [][]shard.Option
 
-	engineconfig.IterateShards(c.appCfg, func(sc *shardconfig.Config) {
+	require := !nodeconfig.Relay(c.appCfg) // relay node does not require shards
+
+	engineconfig.IterateShards(c.appCfg, require, func(sc *shardconfig.Config) {
```
Comment (fyrchik) [inline cmd/neofs-node/config.go:372]: Wy don't we just skip the whole iteration?

Comment (cthulhu-rider) [reply cmd/neofs-node/config.go:372]: For now there is no need to completely skip the section. Perhaps this will change with a more detailed study of the relay mode.
