### PR TITLE
fix/Do not treat `EOF` as a network error

### LINKED ISSUE #2502: Invalid error output when other role sending a request with prohibited headers
```
COMMAND: neofs-cli --config /home/runner/work/neofs-node/neofs-node/neofs-testcases/wallet_config.yml object put --rpc-endpoint 's03.neofs.devenv:8080' --wallet '/home/runner/work/neofs-node/neofs-node/neofs-testcases/TemporaryDir/35f9b04a-bd7a-49ca-8cf9-87ba2f3fa5ed.json' --cid '3Ycb48kajSy8LSgyLTSSh3CKDL7k6trkpmsGUs2ocXLd' --file '/home/runner/work/neofs-node/neofs-node/neofs-testcases/TemporaryDir/TestFilesDir/27500f3b-c150-4c04-89f7-bd6a373455a9' --no-progress --xhdr 'check_key=other_value'
RETCODE: 1

STDOUT:
rpc error: copy data into object stream: EOF

STDERR:

Start / End / Elapsed	 08:58:55.583929 / 08:58:56.097062 / 0:00:00.513133
```

See:
https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/490-1692002283/index.html#suites/526197b5274bae768c0a631fa726cb06/493b4e3adb61f806/

## Expected Behavior
We expect an error message like this:
`rpc error: read object header via client: status: code = 2049 message = object not found`

## Current Behavior
`rpc error: copy data into object stream: EOF`

## Steps to Reproduce (for bugs)
Run `test_extended_acl_filters_request` or `test_extended_acl_filters_request` test.

## Regression
Yes
https://github.com/nspcc-dev/neofs-node/pull/2493
https://github.com/nspcc-dev/neofs-node/actions/runs/5831023199
@cthulhu-rider 

## Your Environment
neo-go 0.101.1
neofs-s3-authmate 0.27.1
neofs-cli 86c5d3b7
neofs-adm 86c5d3b7
AWS aws-cli/2.13.7 Python/3.11.4 Linux/5.15.0-1042-azure exe/x86_64.ubuntu.22 prompt/off

### LINKED ISSUE #2513: Unexpected error returned on object put into RO container
## Expected Behavior
"object put" into RO (basic ACL) container -> 2048, access denied.

## Current Behavior
EOF, as in https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/521-1692114704/index.html#suites/fdd01b21ba45a24279d113673232977a/45816f158f6f8704/

# Context
Can be related to #2502.

### PR DESCRIPTION
**Pull request by carpawell**
That is the only possible way `client.Client` can say stream has been closed (because of internal logic, not the network/unexpected errors) in the current API. It returned `bool` in the previous versions.
Closes #2513, closes #2502.

### CODE REVIEW

**Comment by carpawell** [comment]
I was surprised a little when I figured out that _every_ API status _always_ returns `io.EOF` from our `io.Writer`. IMO, that is not a good API and smth should be done (at least, document it).

**Comment by carpawell** [comment]
I will recheck other streams later.

**Comment by roman-khimov** [comment]
Likely an SDK fix would be more appropriate. But it'll have to `Close()` to get a real error. At the same time this stream is not very useful after `Write()` failure anyway.

File: cmd/neofs-cli/internal/client/client.go [hunk 1]
```diff
@@ -439,7 +440,7 @@ func PutObject(ctx context.Context, prm PutObjectPrm) (*PutObjectRes, error) {
 		buf := make([]byte, sz)
 
 		_, err = io.CopyBuffer(wrt, prm.rdr, buf)
-		if err != nil {
+		if err != nil && !errors.Is(err, io.EOF) {
```
Comment (cthulhu-rider) [inline cmd/neofs-cli/internal/client/client.go:443]: this obviously cannot be accepted as working fix w/o SDK doc changes at least. Lets wait for SDK changes and base on them

**Comment by carpawell** [comment]
@cthulhu-rider, @roman-khimov but RC10 is RC10 and failed tests were and are failing tests. What it the difference b/w this PR and that series of commits: https://github.com/nspcc-dev/neofs-node/pull/2346/commits/bc167ac3636d02a1f0c408bdb5b027414b6097b2.

**Comment by roman-khimov** [comment]
There is a difference in SDK state, it was changing like crazy back then, now it's calm there. At the same time we can have this as an intermediary fix for 0.38.0, then have an issue for SDK (that would certainly require additional testing) and then drop this code after SDK is fixed.

**Review by roman-khimov — APPROVED** [review]

**Comment by cthulhu-rider** [comment]
lets create an issue and tag it in code, then merge

**Review by cthulhu-rider — APPROVED** [review]
