### PR TITLE
Fix/Add immediate object notifications

### LINKED ISSUE #1228: SN does not notify about objects with 0 `__NEOFS__TICK_EPOCH`
In #1183 object notification retrieving was added but not handling object with zero `__NEOFS__TICK_EPOCH` attribute value. Such objects must produce notifications immediately after creation according to spec.

### PR DESCRIPTION
**Pull request by carpawell**
Closes #1228.

### CODE REVIEW

File: pkg/services/object/put/local.go [hunk 1]
```diff
@@ -3,13 +3,20 @@ package putsvc
...
 
-	"github.com/nspcc-dev/neofs-node/pkg/local_object_storage/engine"
 	"github.com/nspcc-dev/neofs-node/pkg/services/object_manager/transformer"
 	"github.com/nspcc-dev/neofs-sdk-go/object"
+	objectSDK "github.com/nspcc-dev/neofs-sdk-go/object"
 )
 
+// ObjectStorage is an object storage interface.
+type ObjectStorage interface {
+	// Put must save passed object to the local disk
```
Comment (cthulhu-rider) [inline pkg/services/object/put/local.go:13]: IMO `local disk` is too strong requirement since `Service` doesn't care about what type of storage is used.

File: cmd/neofs-node/object.go [hunk 2]
```diff
@@ -522,3 +537,40 @@ func (c *reputationClientConstructor) Get(info coreclient.NodeInfo) (coreclient.
...
+	e  *engine.StorageEngine
+	nw notificationWriter
+	ns netmap.State
+
+	defaultTopic string
+}
+
+func (e engineWithNotifications) Put(o *objectSDK.Object) error {
+	if err := engine.Put(e.e, o); err != nil {
+		return err
```
[the remark this answers is not in the document]
Comment (alexvanin) [reply cmd/neofs-node/object.go:551]: Other notifications are triggered by iterating over objects stored in engine. It will be consistent to produce those immediate notifications on the same basis.

But it is really good question, though. /cc @realloc

[the remark this answers is not in the document]
Comment (carpawell) [reply cmd/neofs-node/object.go:551]: > is it correct?

used a rule "notify only if I managed to store the object", thought that it was expected behavior

[the remark this answers is not in the document]
Comment (carpawell) [reply cmd/neofs-node/object.go:551]: btw, i thought that the main idea about notifications is to say that some node successfully stored the object

File: cmd/neofs-node/object.go [hunk 3]
```diff
@@ -327,7 +327,7 @@ func initObjectService(c *cfg) {
 	)
 
 	// build service pipeline
-	// grpc | <metrics> | acl | signature | response | split
```
Comment (fyrchik) [inline cmd/neofs-node/object.go:330]: Could you explain why this change?
It seems like the previous order was correct.

File: pkg/services/notificator/nats/service.go [hunk 4]
```diff
@@ -38,12 +38,12 @@ type Option func(*opts)
 var errConnIsClosed = errors.New("connection to the server is closed")
 
 // Notify sends object address's string representation to the provided topic.
-// Uses first 4 bytes of object ID as a message ID to support 'exactly once message'
-// delivery.
+// Uses first 4 bytes of object ID as a message ID to support 'exactly-once'
```
Comment (fyrchik) [inline pkg/services/notificator/nats/service.go:41]: It is exactly once QoS in NATS documentation.

File: cmd/neofs-node/object.go [hunk 5]
```diff
@@ -522,3 +537,40 @@ func (c *reputationClientConstructor) Get(info coreclient.NodeInfo) (coreclient.
...
+	defaultTopic string
+}
+
+func (e engineWithNotifications) Put(o *objectSDK.Object) error {
+	if err := engine.Put(e.e, o); err != nil {
+		return err
+	}
+
+	ni, err := o.NotificationInfo()
+	if err == nil {
```
Comment (fyrchik) [inline cmd/neofs-node/object.go:555]: Log the error if non-nil?

**Review by fyrchik — APPROVED** [review]

File: cmd/neofs-node/object.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (realloc) [reply cmd/neofs-node/object.go:551]: The notification must be issued only for successfully stored the object. Otherwise, the actions following the notification will have no sense.

File: cmd/neofs-node/object.go (hunk 5 above)
Comment (alexvanin) [reply cmd/neofs-node/object.go:555]: Debug logs, perhaps. Log records produced by individual objects tend to consume all free space, unfortunately.

File: cmd/neofs-node/config.go [hunk 6]
```diff
@@ -185,6 +187,13 @@ type cfgObject struct {
 	cfgLocalStorage cfgLocalStorage
 }
 
+type cfgNotifications struct {
+	enabled bool
+	nw      notificationWriter
+
```
Comment (cthulhu-rider) [inline cmd/neofs-node/config.go:193]: Could you please sync linebreaks between fields?

File: cmd/neofs-node/object.go (hunk 3 above)
Comment (carpawell) [reply cmd/neofs-node/object.go:330]: maybe i'm wrong, did not look deeply, just saw the order of wrapping and saw this commits:

1. that comment [appeared](https://github.com/nspcc-dev/neofs-node/commit/534ce034217d3d4bd623484309340998e1a76408);
2. then the order was [changed](https://github.com/nspcc-dev/neofs-node/commit/e74ff7c15a770570ae8318399de1b8c35fc8f384) without fixing the comment

**Review by cthulhu-rider — APPROVED** [review]

File: pkg/services/notificator/nats/service.go (hunk 4 above)
Comment (carpawell) [reply pkg/services/notificator/nats/service.go:41]: fixed

File: cmd/neofs-node/object.go (hunk 5 above)
Comment (carpawell) [reply cmd/neofs-node/object.go:555]: it could contain two types of errors:
1. notification is not set for the object (unfortunately, `sdk` does not have dedicated err for that, only `api`; will add), we do not need to log that
2. parsing errors that are not expected since it was received from the node that approved it

File: cmd/neofs-node/object.go (hunk 3 above)
Comment (cthulhu-rider) [reply cmd/neofs-node/object.go:330]: I don't think this comment is really useful.

File: cmd/neofs-node/config.go (hunk 6 above)
Comment (carpawell) [reply cmd/neofs-node/config.go:193]: sure
