### PR TITLE
morph/client: sync subs restoration with main notify cycle

### LINKED ISSUE #3292: mainnet.endpoints is not functional
It so happened that due to incorrect network configuration the first endpoint is not accessible.

While some nodes succeed with the second one:

tenes6:
```
mainnet:
  endpoints:
  - wss://rpc6.t5.n3.nspcc.ru:21331/ws
  - wss://rpc7.t5.n3.nspcc.ru:21331/ws
  - wss://rpc1.t5.n3.nspcc.ru:21331/ws
  - wss://rpc2.t5.n3.nspcc.ru:21331/ws
  - wss://rpc3.t5.n3.nspcc.ru:21331/ws
  - wss://rpc4.t5.n3.nspcc.ru:21331/ws
  - wss://rpc5.t5.n3.nspcc.ru:21331/ws
```
```
warn        client/multi.go:43        could not establish connection to RPC node        {"endpoint": "wss://rpc6.t5.n3.nspcc.ru:21331/ws", "error": "WS client creation: dial tcp 170.64.152.72:21331: connect: connection refused"}
info        client/multi.go:53        connection to RPC node has been established        {"endpoint": "wss://rpc7.t5.n3.nspcc.ru:21331/ws"}
info        innerring/innerring.go:648        notary support        {"mainchain_enabled": false}
```

tenes7 loops only through the first and the second one:

```
fschain:
  endpoints:
  - wss://rpc7.morph.t5.fs.neo.org:51331/ws
  - wss://rpc1.morph.t5.fs.neo.org:51331/ws
  - wss://rpc2.morph.t5.fs.neo.org:51331/ws
  - wss://rpc3.morph.t5.fs.neo.org:51331/ws
  - wss://rpc4.morph.t5.fs.neo.org:51331/ws
  - wss://rpc5.morph.t5.fs.neo.org:51331/ws
  - wss://rpc6.morph.t5.fs.neo.org:51331/ws
```

```
warn        client/multi.go:43        could not establish connection to RPC node        {"endpoint": "wss://rpc7.morph.t5.fs.neo.org:51331/ws", "error": "WS client creation: dial tcp 167.71.212.120:51331: connect: connection refused"}
info        client/multi.go:53        connection to RPC node has been established        {"endpoint": "wss://rpc1.morph.t5.fs.neo.org:51331/ws"}
info        innerring/innerring.go:1219        restarting internal services because of RPC connection loss...
info        innerring/innerring.go:1166        read config from blockchain        {"active": true, "alphabet": true, "epoch": 21440, "precision": 12, "last epoch tick block": 13062131, "current chain height": 13063788, "next epoch tick after (blocks)": 1943}
info        innerring/innerring.go:1233        internal services have been restarted after RPC connection loss...
info        client/notifications.go:230        RPC connection lost, attempting reconnect
error        client/notifications.go:270        could not restore block subscription        {"error": "connection lost: before registering response channel"}
warn        client/multi.go:43        could not establish connection to RPC node        {"endpoint": "wss://rpc7.morph.t5.fs.neo.org:51331/ws", "error": "WS client creation: dial tcp 167.71.212.120:51331: connect: connection refused"}
info        client/multi.go:53        connection to RPC node has been established        {"endpoint": "wss://rpc1.morph.t5.fs.neo.org:51331/ws"}
info        innerring/innerring.go:1219        restarting internal services because of RPC connection loss...
info        innerring/innerring.go:1166        read config from blockchain        {"active": true, "alphabet": true, "epoch": 21440, "precision": 12, "last epoch tick block": 13062131, "current chain height": 13063790, "next epoch tick after (blocks)": 1941}
info        innerring/innerring.go:1233        internal services have been restarted after RPC connection loss...
info        client/notifications.go:230        RPC connection lost, attempting reconnect
error        client/notifications.go:270        could not restore block subscription        {"error": "connection lost: before registering response channel"}
warn        client/multi.go:43        could not establish connection to RPC node        {"endpoint": "wss://rpc7.morph.t5.fs.neo.org:51331/ws", "error": "WS client creation: dial tcp 167.71.212.120:51331: connect: connection refused"}
info        client/multi.go:53        connection to RPC node has been established        {"endpoint": "wss://rpc1.morph.t5.fs.neo.org:51331/ws"}
info        innerring/innerring.go:1219        restarting internal services because of RPC connection loss... 
```

% neofs-ir --version
NeoFS Inner Ring node
Version: 0.45.2 
GoVersion: go1.24.1

### PR DESCRIPTION
**Pull request by carpawell**
If connection was lost quite fast after the previous reconnection, a separate restoration routine may decline `for`'s next reconnection iteration and lead to reconnection deadlock. Do not reuse restoration channel b/w iterations. Closes #3292.

### CODE REVIEW

**Comment by carpawell** [comment]
Let it close #3292. Once repeated, it can be reopened. I am still not sure it may deadlock for hours, but I don't know what else can happen.
Started full tests run: https://github.com/nspcc-dev/neofs-node/actions/runs/14533811514

**Review by roman-khimov — APPROVED** [review]
Changelog

File: pkg/morph/client/notifications.go [hunk 1]
```diff
@@ -220,7 +220,7 @@ type subscriptions struct {
 
 func (c *Client) routeNotifications() {
 	var (
-		restoreCh = make(chan bool)
+		restoreCh = make(chan struct{})
```
Comment (cthulhu-rider) [inline pkg/morph/client/notifications.go:223]:
```suggestion
		restoreCh chan struct{}
```

**Review by cthulhu-rider — APPROVED** [review]
