### PR TITLE
Don't connect storage node to main chain

### LINKED ISSUE #863: Issue with panic on attemp to update node up to 0.25.0
Error in the log:
```
neofs-storage[15888]: 2021-09-29T09:08:44.031Z        info        neofs-node/config.go:334        shard attached to engine        {"id": "M37cZnWHfb2gbagAEBH6zd"}
neofs-storage[15888]: panic: runtime error: slice bounds out of range [1:0]
neofs-storage[15888]: goroutine 1 [running]:
neofs-storage[15888]: main.initMorphComponents.func1(0x0, 0x0, 0x0, 0x12a05f200, 0xc0002a3d28)
neofs-storage[15888]:         github.com/nspcc-dev/neofs-node/cmd/neofs-node/morph.go:48 +0x57c
neofs-storage[15888]: main.initMorphComponents(0xc000106300)
neofs-storage[15888]:         github.com/nspcc-dev/neofs-node/cmd/neofs-node/morph.go:66 +0x11b
neofs-storage[15888]: main.initNetmapService(0xc000106300)
neofs-storage[15888]:         github.com/nspcc-dev/neofs-node/cmd/neofs-node/netmap.go:88 +0x75c
neofs-storage[15888]: main.initApp(0xc000106300)
neofs-storage[15888]:         github.com/nspcc-dev/neofs-node/cmd/neofs-node/main.go:74 +0xe9
neofs-storage[15888]: main.main()
neofs-storage[15888]:         github.com/nspcc-dev/neofs-node/cmd/neofs-node/main.go:54 +0x165
```

### PR DESCRIPTION
**Pull request by cthulhu-rider**
Closes #863.

### CODE REVIEW

File: cmd/neofs-node/morph.go [hunk 1]
```diff
@@ -37,6 +36,10 @@ func initMorphComponents(c *cfg) {
 	var err error
 
 	fn := func(addresses []string, dialTimeout time.Duration, handler func(*client.Client)) {
```
Comment (carpawell) [inline cmd/neofs-node/morph.go:38]: isnt the `fn` var redundant now?

**Review by carpawell — APPROVED** [review]

File: cmd/neofs-node/morph.go (hunk 1 above)
Comment (cthulhu-rider) [reply cmd/neofs-node/morph.go:38]: A little bit, but I left the option to easily revert connection to mainchain. For the same reason, the values in the config have not yet been cut.

**Review by alexvanin — APPROVED** [review]
