### PR TITLE
Fix/Remove object upon tombstone

### LINKED ISSUE #1226: Node can store potentially undead objects
## Context
Object removal in NeoFS is performed using special objects of type [TOMBSTONE](https://github.com/nspcc-dev/neofs-api/blob/650c367529c6fe6b215ea8d5f183b07b4ac8f9a9/object/types.proto#L25). These objects are stored physically just like all other objects. In order to solve some issues related to object removal in distributed systems, tombstones they are initially broadcast throughout the container. Nodes from a primary placement store tombstones physically, while all others only record a note that they learned about the intention to delete the object. These removal records are written in local object storage:
https://github.com/nspcc-dev/neofs-node/blob/14ea7b2c473a7be1f249225fad9f789cbd32971f/pkg/local_object_storage/metabase/inhume.go#L72

## Overview
In the current implementation, the storage node may miss the death of the object and continue to store it locally, and later distribute it throughout the container. This could be due to two reasons:

1. the node missed the appearance of the tombstone in the container (primarily due to network problems)
2. the node has marked the object as removed (`Inhume` operation mentioned above) and this entry will never expire

While `1` can't be completely solved in distributed container, `2` is caused by the loss of expiration date in local record.

## Proposed solution
We need to extend logic of local object storage and GC.  First of all we need to track expiration dates of tombstones in local object storage:
```
func (*InhumePrm) ExpiresAfter(epoch uint64)
```
After removal records became limited in lifetime, we need to be able to process expiration dates:
```
// method to be implemented
func (Grave) ExpiresAfter() uint64

// the method's usage
func (*DB) IterateOverGraveyard(h GraveHandler) error
```
These changes will allow `GC` to process grave expiration timestamps
https://github.com/nspcc-dev/neofs-node/blob/14ea7b2c473a7be1f249225fad9f789cbd32971f/pkg/local_object_storage/shard/gc.go#L185

As a consequence, an additional improvement will be the separation of expired tombstones as objects and expired grave records.

### Other objects
[LOCK](https://github.com/nspcc-dev/neofs-api/blob/650c367529c6fe6b215ea8d5f183b07b4ac8f9a9/object/types.proto#L31) objects behave similar to `TOMBSTONE` ones (except to prevent deletion), so we need to process them almost the same. We've encountered same problems in 
* https://github.com/nspcc-dev/neofs-node/pull/1181

### PR DESCRIPTION
**Pull request by carpawell**
Based on #1321, will rebase after its merge.

Key changes:
- `Graveyard` was separated on `Graveyard` and `Garbage` buckets since now it is possible to have an object which has both graveyard and GC records.
- When TS is received, the object covered with that TS is marked with GC immediately.
- TS info is kept in the `Graveyard` bucket once it appeared on a node.
- Every epoch all the tombstones are checked for their presence in the NeoFS network and TSs that have not been found are deleted from the `Graveyard`.
- Strange get service [initialization](https://github.com/nspcc-dev/neofs-node/pull/1318/files#diff-c9453c121fb79a56f041a2bd8b9f327c6c898ae5ce7be9db49a714446fdbdc5bR356): a get service needs a storage engine for initialization and a storage engine needs a get service.

Closes #1226.

TODO: add more tests to the engine/shard after approving the main idea of the PR.

### CODE REVIEW

File: pkg/local_object_storage/metabase/inhume.go [hunk 1]
```diff
@@ -73,6 +73,11 @@ var errBreakBucketForEach = errors.New("bucket ForEach break")
 // if at least one object is locked.
 func (db *DB) Inhume(prm *InhumePrm) (res *InhumeRes, err error) {
 	err = db.boltDB.Update(func(tx *bbolt.Tx) error {
+		garbageBKT, err := tx.CreateBucketIfNotExists(garbageBucketName)
```
Comment (fyrchik) [inline pkg/local_object_storage/metabase/inhume.go:76]: Do this in `Init`?

File: pkg/local_object_storage/metabase/graveyard.go [hunk 2]
```diff
@@ -229,3 +229,25 @@ func graveFromKV(k, v []byte) (TombstonedObject, error) {
 		tomb: tomb,
 	}, nil
 }
+
+// DropGraves deleted Tombstoned objects from the
```
Comment (fyrchik) [inline pkg/local_object_storage/metabase/graveyard.go:233]: `s/deleted/deletes/`

File: pkg/services/object_manager/tombstone/getter.go [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+}
+
+// Getter is a tombstone source wrapper.
+// It checks tombstones presence via tombstone
+// source, caches it checks its expiration.
+//
+// Must be created via NewGetter function. `var` and
+// `Getter{}` declarations leads to undefined behaviour
+// and may lead to panics.
+type Getter struct {
```
Comment (fyrchik) [inline pkg/services/object_manager/tombstone/getter.go:33]: Why is it `Getter` and not `LRUCache` or sth similar?

File: pkg/services/object_manager/tombstone/getter.go [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+}
+
+// GetTombstone checks the tombstone presence in the system in the
+// following order:
+//  * 1. Local LRU cache;
+//  * 2. Tombstone source.
+//
+// If a tombstone was successfully fetched (regardless of its expiration)
+// it is cached in the LRU cache.
+func (g *Getter) GetTombstone(ctx context.Context, a *addressSDK.Address, epoch uint64) bool {
```
Comment (fyrchik) [inline pkg/services/object_manager/tombstone/getter.go:48]: Why is it called `GetTombstone`, but returns `bool`?

File: pkg/local_object_storage/metabase/delete_test.go [hunk 5]
```diff
@@ -57,13 +55,13 @@ func TestDB_Delete(t *testing.T) {
 	require.NoError(t, err)
 	require.Len(t, l, 0)
 
-	// check if they removed from graveyard
+	// check if they marked as already removed
```
[the remark this answers is not in the document]
Comment (carpawell) [reply pkg/local_object_storage/metabase/delete_test.go:58]: child and parent objects (the only tested objects in that test)

originally "they" was added not by me, added a new line after that comment (usually i do that to highlight that comment is not only for the next line)

File: pkg/local_object_storage/metabase/graveyard_test.go [hunk 6]
```diff
@@ -46,21 +54,46 @@ func TestDB_IterateOverGraveyard(t *testing.T) {
...
 
-	require.Equal(t, 2, counterAll)
-	require.Equal(t, []*addressSDK.Address{object.AddressOf(obj1)}, buriedTS)
-	require.Equal(t, []*addressSDK.Address{object.AddressOf(obj2)}, buriedGC)
+	require.Equal(t, 4, counterAll)
+	require.True(t, equalAddresses([]*addressSDK.Address{object.AddressOf(obj1), object.AddressOf(obj2)}, buriedTS))
+	require.True(t, equalAddresses([]*addressSDK.Address{object.AddressOf(obj3), object.AddressOf(obj4)}, buriedGC))
+}
+
+func equalAddresses(aa1 []*addressSDK.Address, aa2 []*addressSDK.Address) bool {
```
[the remark this answers is not in the document]
Comment (carpawell) [reply pkg/local_object_storage/metabase/graveyard_test.go:424]: wow, thx, did not know that such exists, used it

File: pkg/local_object_storage/metabase/util.go [hunk 7]
```diff
@@ -21,7 +21,14 @@ bytes. Check it later.
 const invalidBase58String = "_"
 
 var (
-	graveyardBucketName       = []byte(invalidBase58String + "Graveyard")
+	// graveyardBucketName keeps rows with the objects that have been
```
[the remark this answers is not in the document]
Comment (carpawell) [reply pkg/local_object_storage/metabase/util.go:24]: you mean change it to smth like "stores"?

File: pkg/local_object_storage/metabase/inhume.go (hunk 1 above)
Comment (carpawell) [reply pkg/local_object_storage/metabase/inhume.go:76]: if fact it is already [called](https://github.com/nspcc-dev/neofs-node/pull/1318/files#diff-1ff37983e3b5b6c80d5873c9922f36816780fb8cfbd693b52aa539543864da52R57); changed to just `Bucket`

File: pkg/services/object_manager/tombstone/getter.go (hunk 3 above)
Comment (carpawell) [reply pkg/services/object_manager/tombstone/getter.go:33]: i designed `Getter` as a component that wraps _something_ that could provide info about tombstones. in the first implementation, it contained `local` and `remote` TSSource interfaces: a storage engine and a wrapper over an API client but then it has changed to reusing one object service, and only after that, i added an LRU cache. so I want it to be as abstract as possible

btw, I agree that naming is awful, just could not think of something better, will be happy to hear some suggestions from you

File: pkg/services/object_manager/tombstone/getter.go (hunk 4 above)
Comment (carpawell) [reply pkg/services/object_manager/tombstone/getter.go:48]: one more awful naming. `TombstoneIsAvailable`, `IsAvailable`, `TobmstoneIsExpired`?

File: pkg/local_object_storage/metabase/util.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (fyrchik) [reply pkg/local_object_storage/metabase/util.go:24]: yes

File: pkg/services/object_manager/tombstone/getter.go (hunk 4 above)
Comment (fyrchik) [reply pkg/services/object_manager/tombstone/getter.go:48]: `IsTombstoneAvailable`, `IsTombsoneAlive` look good to me.

File: pkg/services/object_manager/tombstone/getter.go (hunk 3 above)
Comment (fyrchik) [reply pkg/services/object_manager/tombstone/getter.go:33]: `tombstone.HealthChecker`, `tombstone.ExpirationChecker`, `tombstone.Validator`, `tombstone.ExpirationCache`?

File: pkg/services/object_manager/tombstone/source/source.go [hunk 8]
```diff
@@ -0,0 +1,89 @@
...
+// Must be created via NewSource function. `var` and `Source{}`
+// declarations leads to undefined behaviour and may lead
+// to panics.
+type Source struct {
+	s *getsvc.Service
+}
+
+var (
+	errNotFound apistatus.ObjectNotFound
+	errRemoved  apistatus.ObjectNotFound
```
Comment (cthulhu-rider) [inline pkg/services/object_manager/tombstone/source/source.go:29]:
```suggestion
	errRemoved  apistatus.ObjectAlreadyRemoved
```

File: pkg/services/object_manager/tombstone/source/source.go [hunk 9]
```diff
@@ -0,0 +1,89 @@
...
+	var hr headerWriter
+
+	var headPrm getsvc.HeadPrm
+	headPrm.WithAddress(a)
+	headPrm.SetHeaderWriter(&hr)
+	headPrm.SetCommonParameters(&util.CommonPrm{}) //default values are ok for that operation
+
+	err := s.s.Head(ctx, headPrm)
+	switch {
+	case errors.As(err, &errNotFound) || errors.As(err, &errRemoved):
```
Comment (cthulhu-rider) [inline pkg/services/object_manager/tombstone/source/source.go:77]: What about multi-routine access?

File: pkg/services/object_manager/tombstone/getter.go (hunk 3 above)
Comment (carpawell) [reply pkg/services/object_manager/tombstone/getter.go:33]: i have chosen `tombstone.ExpirationChecker`

File: pkg/services/object_manager/tombstone/getter.go (hunk 4 above)
Comment (carpawell) [reply pkg/services/object_manager/tombstone/getter.go:48]: i have chosen `IsTombstoneAvailable`

File: pkg/local_object_storage/metabase/exists.go [hunk 10]
```diff
@@ -101,24 +100,37 @@ func (db *DB) exists(tx *bbolt.Tx, addr *addressSDK.Address) (exists bool, err e
...
-//  * 0 if object is not in graveyard;
-//  * 1 if object is in graveyard with GC mark;
-//  * 2 if object is in graveyard with tombstone.
+//  * 0 if object is not marked for deletion;
+//  * 1 if object with GC mark;
+//  * 2 if object is covered with tombstone.
 func inGraveyard(tx *bbolt.Tx, addr *addressSDK.Address) uint8 {
 	graveyard := tx.Bucket(graveyardBucketName)
 	if graveyard == nil {
+		// incorrect node state, does not make
```
[the remark this answers is not in the document]
Comment (carpawell) [reply pkg/local_object_storage/metabase/exists.go:109]: i meant that node that has been inited with some shard that has a metabase without some core bucket

changed to "metabase"

File: pkg/local_object_storage/metabase/graveyard.go [hunk 11]
```diff
@@ -9,70 +9,245 @@ import (
...
+// GarbageObject represents descriptor of the
+// object that has been marked with GC.
+type GarbageObject struct {
 	addr *addressSDK.Address
 }
 
-// WithGCMark returns true if grave marked for GC to be removed.
-func (g *Grave) WithGCMark() bool {
-	return g.gcMark
+// Address returns buried object address.
```
[the remark this answers is not in the document]
Comment (carpawell) [reply pkg/local_object_storage/metabase/graveyard.go:18]: in fact, took that term from the tests' comments (and started to name all GCed/ TSed objects as "buried"/"deleted" and the file is still named as "graveyard" cause all those objects gonna "die" anyway). do not have my own terminology but agree that it would be better to name objects with GC as "garbage" and objects with TS as "tombstoned" everywhere in the repo

changed

File: pkg/local_object_storage/metabase/graveyard.go [hunk 12]
```diff
@@ -9,70 +9,245 @@ import (
...
+	if err != nil {
+		return fmt.Errorf("could not parse grave: %w", err)
+	}
+
+	return g.h(o)
+}
+
+func (db *DB) iterateDeletedObj(tx *bbolt.Tx, h kvHandler, offset *addressSDK.Address) error {
+	var bkt *bbolt.Bucket
+	switch t := h.(type) {
```
[the remark this answers is not in the document]
Comment (carpawell) [reply pkg/local_object_storage/metabase/graveyard.go:162]: i tried that before and found that it is redundantly (IMO): 
1. handler contains info about bucket it could handle;
2. with an explicit parameter it could be possible to pass `garbage` bucket with `graveyardHandler`. that is totally incorrect but does not lead to panic or any other explicit errors => hard to debug

also, I think that sharing iteration logic is still good but I did not find any ways to do that without a type switch (btw, is a type switch that bad? maybe I do not know smth about it)

File: pkg/local_object_storage/metabase/graveyard.go [hunk 13]
```diff
@@ -9,70 +9,245 @@ import (
...
+		return TombstonedObject{}, err
+	}
+
+	return TombstonedObject{
+		addr: target,
+		tomb: tomb,
+	}, nil
+}
+
+// DropGraves deletes Tombstoned objects from the
```
[the remark this answers is not in the document]
Comment (carpawell) [reply pkg/local_object_storage/metabase/graveyard.go:233]: choose the first one

File: pkg/local_object_storage/shard/control.go [hunk 14]
```diff
@@ -62,8 +62,8 @@ func (s *Shard) Init() error {
 				cancelFunc: func() {},
 				handlers: []eventHandler{
 					s.collectExpiredObjects,
-					s.collectExpiredTombstones,
 					s.collectExpiredLocks,
+					s.collectExpiredTombstones,
```
[the remark this answers is not in the document]
Comment (carpawell) [reply pkg/local_object_storage/shard/control.go:66]: no, was made by a mistake, returned the order

File: pkg/local_object_storage/shard/gc.go [hunk 15]
```diff
@@ -238,17 +247,54 @@ func (s *Shard) collectExpiredObjects(ctx context.Context, e Event) {
...
+		if len(tss) == tssDeleteBatch {
+			return meta.ErrInterruptIterator
+		}
+
+		return nil
 	})
-	if err != nil || len(expired) == 0 {
+
+	for {
+		log.Debug("iterating tombstones")
```
[the remark this answers is not in the document]
Comment (carpawell) [reply pkg/local_object_storage/shard/gc.go:270]: it was added explicitly not for tests

think I could help sometimes: it will be printed every iteration so at least it may say about a number of tombstones

File: pkg/services/object_manager/tombstone/constructor.go [hunk 16]
```diff
@@ -0,0 +1,84 @@
...
+
+	tsSource Source
+}
+
+// Option is an option of Getter's constructor.
+type Option func(*cfg)
+
+func defaultCfg() *cfg {
+	return &cfg{
+		log:       zap.L(),
```
[the remark this answers is not in the document]
Comment (carpawell) [reply pkg/services/object_manager/tombstone/constructor.go:25]: changed but note: all other components in the repo use ` zap.L()` as a default logger (that was the only reason for me to do that the same and not with `NewNop`)

File: pkg/services/object_manager/tombstone/getter.go [hunk 17]
```diff
@@ -0,0 +1,94 @@
...
+	lru "github.com/hashicorp/golang-lru"
+	objectV2 "github.com/nspcc-dev/neofs-api-go/v2/object"
+	"github.com/nspcc-dev/neofs-sdk-go/object"
+	addressSDK "github.com/nspcc-dev/neofs-sdk-go/object/address"
+	"go.uber.org/zap"
+)
+
+// Source is a tombstone source interface.
+type Source interface {
+	// Tombstone must return tombstone from the source it was
```
[the remark this answers is not in the document]
Comment (carpawell) [reply pkg/services/object_manager/tombstone/getter.go:16]: changed and added some words to the last sentence: 
```
Tombstone MUST return (nil, nil) if requested tombstone is
missing in the storage for the provided epoch.
```

File: pkg/services/object_manager/tombstone/source/source.go (hunk 9 above)
Comment (carpawell) [reply pkg/services/object_manager/tombstone/source/source.go:77]: did not get: what problems could appear?

Comment (carpawell) [reply pkg/services/object_manager/tombstone/source/source.go:77]: got it, messed `Is` and `As`, deleted global vars, and added creating a new one on every `Tombstone` call

File: pkg/local_object_storage/metabase/graveyard.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (cthulhu-rider) [reply pkg/local_object_storage/metabase/graveyard.go:162]: No, type-switch is okay, just mentioned that it's needed only for bucket selection.

**Review by cthulhu-rider — APPROVED** [review]

**Review by fyrchik — APPROVED** [review]
