### PR TITLE
Fix nil pointer error for `neofs-lens storage sanity` command

### LINKED ISSUE #3136: neofs-lens storage sanity SIGSEGV
```
[root@titan1:~]# ./neofs-lens --config /etc/neofs/storage/config.yml storage sanity
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa3c549]

goroutine 1 [running]:
github.com/nspcc-dev/neofs-node/pkg/local_object_storage/blobstor/peapod.(*Peapod).Open(0x0, 0x1)
	github.com/nspcc-dev/neofs-node/pkg/local_object_storage/blobstor/peapod/peapod.go:201 +0x29
github.com/nspcc-dev/neofs-node/cmd/neofs-lens/internal/storage.sanityCheck.func2(0xc0002b6ff0)
	github.com/nspcc-dev/neofs-node/cmd/neofs-lens/internal/storage/sanity.go:103 +0xcaf
github.com/nspcc-dev/neofs-node/cmd/neofs-node/config/engine.IterateShards(0xc0002b6820, 0x0, 0xc0001e1ca0)
	github.com/nspcc-dev/neofs-node/cmd/neofs-node/config/engine/config.go:58 +0xbcc
github.com/nspcc-dev/neofs-node/cmd/neofs-lens/internal/storage.sanityCheck(0x12c1e00, {0xc0001633a0?, 0x4?, 0xbe75f3?})
	github.com/nspcc-dev/neofs-node/cmd/neofs-lens/internal/storage/sanity.go:59 +0x12a
github.com/spf13/cobra.(*Command).execute(0x12c1e00, {0xc000163380, 0x2, 0x2})
	github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0x12be480)
	github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.1/command.go:1041
main.main()
	github.com/nspcc-dev/neofs-node/cmd/neofs-lens/root.go:54 +0x1a
zsh: exit 2     ./neofs-lens --config /etc/neofs/storage/config.yml storage sanity
```

### PR DESCRIPTION
**Pull request by End-rey**
Closes #3136.

### CODE REVIEW

File: cmd/neofs-lens/internal/storage/sanity.go [hunk 1]
```diff
@@ -195,9 +207,13 @@ func checkShard(cmd *cobra.Command, sh storageShard) (int, error) {
 
 			switch id := string(sid); id {
 			case "":
-				err = checkObject(*header, sh.fsT)
+				if sh.fsT != nil {
```
Comment (roman-khimov) [inline cmd/neofs-lens/internal/storage/sanity.go:210]: Seems to be somewhat inconsistent here when `== nil`. If we have no FSTree we should have no objects with "" ID, same goes for peapod type. This can happen only if metabase is incorrect. So we need to handle `== nil` case with an error as well.

**Review by roman-khimov — APPROVED** [review]
