### PR TITLE
engine: fix split object stuck in GC cycle

### LINKED ISSUE #3641: Split object stuck in GC cycle
## Expected Behavior
Objects deleted and never returning again.

## Current Behavior
```
Oct 20 20:20:55 metis1 neofs-node[2740175]: error        engine/inhume.go:159        inhuming root object but no link object is found        {"linkAddr": "HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/3fLGesRxQuCwVPH1aBJ4EWdkqqYtMdv1i8Xh1i6ZuHwi", "addrBeingInhumed": "HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/PfHyJiXB9AshvvKmp1eKvGNYWNG8sRELXkMULs8rXRC", "error": "status: code = 2049 message = object not found"}
Oct 20 20:20:55 metis1 neofs-node[2740175]: error        engine/inhume.go:159        inhuming root object but no link object is found        {"linkAddr": "HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/3DVHf4Nmkc41NiHXx1YmJiRCCmoFeLPLNuXvsyS7DtKr", "addrBeingInhumed": "HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/jPPUX7xHJkoLmPFdM74WgQrmgLxAG7b3byi6NkgWnmJ", "error": "status: code = 2049 message = object not found"}
Oct 20 20:20:55 metis1 neofs-node[2740175]: error        engine/inhume.go:159        inhuming root object but no link object is found        {"linkAddr": "HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/58oAuA2naNiaJMdTtnYaWpMVtFNaXbw387yS6teQJDeE", "addrBeingInhumed": "HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/HZnpp3Aiv6EPdYUPiq6BbQJu4RZuNXJHVYi51w9xJ4zf", "error": "status: code = 2049 message = object not found"}
```

## Possible Solution
Fix something

## Steps to Reproduce (for bugs)
Not really known.

## Context
Mainnet.

## Regression
Kinda. #3633 fixed a similar thing, but it looks like the case of completely missing data can still be improved by just dropping the big object from the DB.

## Your Environment
* Version used: 0.49.1
* Server setup and configuration: mainnet
* Operating System and version (`uname -a`): Debian bookworm

### PR DESCRIPTION
**Pull request by End-rey**
Closes #3641.

### CODE REVIEW

File: pkg/local_object_storage/engine/gc_test.go [hunk 1]
```diff
@@ -384,6 +387,114 @@ func TestSplitObjectExpirationWithoutLink(t *testing.T) {
...
+		for _, sh := range e.sortedShards(parentAddr) {
+			_, err = sh.Get(parentAddr, false)
+			if errors.Is(err, statusSDK.ErrObjectNotFound) {
+				return true
+			}
+		}
+		return false
+	}, 1*time.Second, 100*time.Millisecond)
+
+	logBuf.AssertContainsMsg(zapcore.DebugLevel, "inhuming root object but no link object is found")
```
Comment (cthulhu-rider) [inline pkg/local_object_storage/engine/gc_test.go]:
```suggestion
	logBuf.AssertContainsMsg(zap.DebugLevel, "inhuming root object but no link object is found")
```
and below so `zapcore` pkg wont be needed

**Review by cthulhu-rider — APPROVED** [review]
