### PR TITLE
shard: Turn `ModeDegraded` on metabase opening failure

### LINKED ISSUE #1549: Initialize shards properly
During node start we currently fail if the metabase cannot be initialized.
The behaviour should be the following:
1. Try opening the metabase. On failure start shard in the degraded mode.
2. Try initializing blobovniczas. On failure:
2.1. If there is only 1 shard, shutdown the node.
2.2. If there are more shards, start as usual with the shard disabled.

### PR DESCRIPTION
**Pull request by cthulhu-rider**
Make `Shard` to work in degraded mode if metabase is unavailable on
opening stage.

Signed-off-by: Leonard Lyubich <leonard@nspcc.ru>

* closes #1549

About 9bf46d99818bf6f5218535fb9f555e48356d9cab: I don't think it makes sense to define `ModeDisabled` shard mode now since `StorageEngine` can't work with it. Maybe we can implement private behavior on `Shard` side when it fails all the calls if `Init` was failed, smth like `errNotInitialized`.

### CODE REVIEW

File: pkg/local_object_storage/shard/control.go [hunk 1]
```diff
@@ -26,7 +26,17 @@ func (s *Shard) Open() error {
 			return fmt.Errorf("could not open %T: %w", component, err)
 		}
 	}
-	return nil
+
+	return s.openMetabase()
```
Comment (fyrchik) [inline pkg/local_object_storage/shard/control.go:30]: It changes the order of opening, can we just check whether `component == s.metaBase` in cycle?
The `SetMode` could be done separately in the end.

Also, same applies to `Init`.

File: pkg/local_object_storage/shard/control.go [hunk 2]
```diff
@@ -26,7 +26,17 @@ func (s *Shard) Open() error {
...
+}
+
+func (s *Shard) openMetabase() error {
+	err := s.metaBase.Open()
+	if err != nil {
+		err = s.SetMode(ModeDegraded)
```
Comment (fyrchik) [inline pkg/local_object_storage/shard/control.go:36]: I think we need to log the old error too.

**Comment by cthulhu-rider** [comment]
Some tests currently panic because `ModeDegraded` mode doesn't completely prevent operations with metabase. @fyrchik is gonna fix this.

File: pkg/local_object_storage/shard/control.go [hunk 3]
```diff
@@ -23,32 +39,67 @@ func (s *Shard) Open() error {
...
-		fMetabase = s.metaBase.Init
+	type initializer interface {
+		Init() error
 	}
 
-	components := []func() error{
-		s.blobStor.Init, fMetabase, s.pilorama.Init,
+	var components []initializer
+
+	if s.GetMode() == ModeDegraded {
```
Comment (fyrchik) [inline pkg/local_object_storage/shard/control.go:72]: shouldn't it be `!=`?

File: pkg/local_object_storage/shard/control.go [hunk 4]
```diff
@@ -127,7 +178,11 @@ func (s *Shard) Close() error {
 		components = append(components, s.writeCache)
 	}
 
-	components = append(components, s.pilorama, s.blobStor, s.metaBase)
+	components = append(components, s.pilorama, s.blobStor)
+
+	if s.GetMode() != ModeDegraded {
+		components = append(components, s.metaBase)
```
Comment (fyrchik) [inline pkg/local_object_storage/shard/control.go:184]: We should still close it if the error was durieng `Init` stage, can we check if db is `nil` in `Close`?

**Review by fyrchik — APPROVED** [review]
