### PR TITLE
Fix potential data loss in `Policer`

### LINKED ISSUE #1453: Remove redundant local copies by `Replicator` not `Policer`
Can potentially lead to copy loss.
TBD

### LINKED ISSUE #2267: Object loss: (not so) redundant local copy removed on all machines
## Expected Behavior
Object storage system should store objects. I mean, you put them and then get them back at any time until you delete them.

## Current Behavior
So we have a four-node network with `Hw57cmN31gCrqyEyKL5km31TFYETzQa3qk8DNECk6a4H` container using this policy:
```
REP 2 IN X
CBF 2
SELECT 2 FROM F AS X
FILTER Deployed EQ NSPCC AS F
```

An `AV3Z7kpn8hxnaWWB2QRZUF9x8YhnyuB5ntC5fX6PRhz1` object was uploaded into this container some (pretty long) time ago. It's stored on nodes 3 and 4 (there were some movements before the incident, but it's not relevant) until this happens:
```
Feb 15 17:25:49 node3 neofs-node[9352]: 2023-02-15T17:25:49.912Z        error        replicator/process.go:62        could not replicate object        {"component": "Object Replicator", "node": "029538f2e2de2beff5a380e672732461ccac0f1c6c255fc2c364dfc0356f7f5bd3", "object": "Hw57cmN31gCrqyEyKL5km31TFYETzQa3qk8DNECk6a4H/AV3Z7kpn8hxnaWWB2QRZUF9x8YhnyuB5ntC5fX6PRhz1", "error": "(*putsvc.RemoteSender) could not send object: (*putsvc.remoteTarget) could not put object to [/dns4/st1.t5.fs.neo.org/tcp/8080]: write object via client: status: code = 2048 message = access to object operation denied"}
Feb 15 17:25:50 node3 neofs-node[9352]: 2023-02-15T17:25:50.139Z        error        replicator/process.go:62        could not replicate object        {"component": "Object Replicator", "node": "024cda0e7f60284295101465fc47e8a324da994b1cb39ba56825550025c9e9598b", "object": "Hw57cmN31gCrqyEyKL5km31TFYETzQa3qk8DNECk6a4H/AV3Z7kpn8hxnaWWB2QRZUF9x8YhnyuB5ntC5fX6PRhz1", "error": "(*putsvc.RemoteSender) could not send object: (*putsvc.remoteTarget) could not put object to [/dns4/st2.t5.fs.neo.org/tcp/8080]: write object via client: status: code = 2048 message = access to object operation denied"}
Feb 15 17:25:50 node3 neofs-node[9352]: 2023-02-15T17:25:50.163Z        info        policer/check.go:129        redundant local object copy detected        {"component": "Object Policer", "object": "Hw57cmN31gCrqyEyKL5km31TFYETzQa3qk8DNECk6a4H/AV3Z7kpn8hxnaWWB2QRZUF9x8YhnyuB5ntC5fX6PRhz1"}
Feb 15 17:25:50 node3 neofs-node[9352]: 2023-02-15T17:25:50.164Z        info        log/log.go:13        local object storage operation        {"shard_id": "Bcd5yGWeVfJgj2iKLdPiQC", "address": "Hw57cmN31gCrqyEyKL5km31TFYETzQa3qk8DNECk6a4H/AV3Z7kpn8hxnaWWB2QRZUF9x8YhnyuB5ntC5fX6PRhz1", "op": "db DELETE"}
```
and
```
Feb 15 17:25:51 node4 neofs-node[9802]: 2023-02-15T17:25:51.424Z        error        replicator/process.go:62        could not replicate object        {"component": "Object Replicator", "node": "029538f2e2de2beff5a380e672732461ccac0f1c6c255fc2c364dfc0356f7f5bd3", "object": "Hw57cmN31gCrqyEyKL5km31TFYETzQa3qk8DNECk6a4H/AV3Z7kpn8hxnaWWB2QRZUF9x8YhnyuB5ntC5fX6PRhz1", "error": "(*putsvc.RemoteSender) could not send object: (*putsvc.remoteTarget) could not put object to [/dns4/st1.t5.fs.neo.org/tcp/8080]: write object via client: status: code = 2048 message = access to object operation denied"}
Feb 15 17:25:51 node4 neofs-node[9802]: 2023-02-15T17:25:51.603Z        error        replicator/process.go:62        could not replicate object        {"component": "Object Replicator", "node": "024cda0e7f60284295101465fc47e8a324da994b1cb39ba56825550025c9e9598b", "object": "Hw57cmN31gCrqyEyKL5km31TFYETzQa3qk8DNECk6a4H/AV3Z7kpn8hxnaWWB2QRZUF9x8YhnyuB5ntC5fX6PRhz1", "error": "(*putsvc.RemoteSender) could not send object: (*putsvc.remoteTarget) could not put object to [/dns4/st2.t5.fs.neo.org/tcp/8080]: write object via client: status: code = 2048 message = access to object operation denied"}
Feb 15 17:25:51 node4 neofs-node[9802]: 2023-02-15T17:25:51.604Z        info        policer/check.go:129        redundant local object copy detected        {"component": "Object Policer", "object": "Hw57cmN31gCrqyEyKL5km31TFYETzQa3qk8DNECk6a4H/AV3Z7kpn8hxnaWWB2QRZUF9x8YhnyuB5ntC5fX6PRhz1"}
Feb 15 17:25:51 node4 neofs-node[9802]: 2023-02-15T17:25:51.605Z        info        log/log.go:13        local object storage operation        {"shard_id": "2xcLzuvvNzKg8jELk1mn4q", "address": "Hw57cmN31gCrqyEyKL5km31TFYETzQa3qk8DNECk6a4H/AV3Z7kpn8hxnaWWB2QRZUF9x8YhnyuB5ntC5fX6PRhz1", "op": "db DELETE"}
Feb 15 17:26:35 node4 neofs-node[9802]: 2023-02-15T17:26:35.502Z        info        log/log.go:13        local object storage operation        {"shard_id": "2xcLzuvvNzKg8jELk1mn4q", "address": "Hw57cmN31gCrqyEyKL5km31TFYETzQa3qk8DNECk6a4H/AV3Z7kpn8hxnaWWB2QRZUF9x8YhnyuB5ntC5fX6PRhz1", "op": "metabase DELETE"}
```
Nodes 3 and 4 (holding the object) decide to move it to 1 and 2 at around the same time. Both fail to do so for some reason (which is not really important, replication can fail for a number of reasons). Both then delete their local copies. Object is gone. Forever.

## Possible Solution
Looks like something is wrong in the logic ensuring a proper number of copies exists before deleting local one.

## Context
Yeah, it's T5 testnet.

## Your Environment
Node version 0.34.0.

### PR DESCRIPTION
**Pull request by cthulhu-rider**
* closes #2267
* closes #1453

I decided to not directly implement #1453 proposal:
* out-of-container (netmap) cases are handled in a special way
* insta replica removal after successful replication doesn't seem very good behavior: some nodes have been already violated storage policy and lost the object, therefore, it is worth waiting for some time interval, and make a decision already at the next check

### CODE REVIEW

File: pkg/services/policer/check.go [hunk 1]
```diff
@@ -127,6 +127,13 @@ func (p *Policer) processObject(ctx context.Context, addrWithType objectcore.Add
 		p.processNodes(c, addrWithType, nn[i], policy.ReplicaNumberByIndex(i), checkedNodes)
 	}
 
+	// if context is done, needLocalCopy might not be able to calculate
```
Comment (roman-khimov) [inline pkg/services/policer/check.go:136]: How about switching the default? Initializing `needLocalCopy` to `true` above (or switching to `redundantLocalCopy` with `false` default). So we'd have `c.redundantLocalCopy` only when we're sure it's redundant.

File: cmd/neofs-node/netmap.go [hunk 2]
```diff
@@ -315,10 +315,13 @@ func (c *cfg) netmapLocalNodeState(epoch uint64) (*netmapSDK.NodeInfo, error) {
 	nmNodes := nm.Nodes()
 	for i := range nmNodes {
 		if bytes.Equal(nmNodes[i].PublicKey(), c.binPublicKey) {
+			c.localNodeInNetmap.Store(true)
```
Comment (roman-khimov) [inline cmd/neofs-node/netmap.go:318]: Why not doing it in `c.handleLocalNodeInfo()`?

File: pkg/services/policer/policer.go [hunk 3]
```diff
@@ -65,6 +65,14 @@ type Option func(*cfg)
 // the redundant local copy of the object.
 type RedundantCopyCallback func(oid.Address)
 
+// Network provides information about the NeoFS network to Policer for work.
+type Network interface {
```
Comment (roman-khimov) [inline pkg/services/policer/policer.go:69]: Not sure about naming here and below, but we're already using `NodeState` and `NodeInfo`.

File: pkg/services/policer/policer.go [hunk 4]
```diff
@@ -65,6 +65,14 @@ type Option func(*cfg)
...
+	// IsLocalNodeInNetmap checks whether the local node belongs to the current
+	// network map. If it is impossible to check this fact, IsLocalNodeInNetmap
+	// returns false.
+	IsLocalNodeInNetmap() bool
```
Comment (roman-khimov) [inline pkg/services/policer/policer.go:73]: `IsOnMap`? `IsOnline`? Although this one works as well.

File: cmd/neofs-node/netmap.go (hunk 2 above)
Comment (roman-khimov) [reply cmd/neofs-node/netmap.go:318]: BTW, how about officially offline (on a map, but offline) nodes? Will they be able to replicate?

File: pkg/services/policer/policer.go (hunk 3 above)
Comment (roman-khimov) [reply pkg/services/policer/policer.go:69]: Maybe `LocalConfig`, because that's what we have in `shared`.

File: pkg/services/policer/check.go [hunk 5]
```diff
@@ -106,31 +118,65 @@ func (p *Policer) processObject(ctx context.Context, addrWithType objectcore.Add
...
-			zap.Stringer("object", addr),
-		)
+		if !c.localNodeInContainer {
+			// Here we may encounter a special case where the node is not in the network
+			// map. In this scenario, it is impossible to determine whether the local node
+			// will enter the container in the future or not. At the same time, the rest of
+			// the network will perceive local peer as a 3rd party which will cause possible
+			// replication problems. Iin order to avoid the potential loss of a single
+			// replica, it is held.
+			if !p.network.IsLocalNodeInNetmap() {
```
Comment (roman-khimov) [inline pkg/services/policer/check.go:151]: BTW, maybe this logic could reside somewhere in the upper layer (that calls `processObject()` at least), because in this case checking individual objects seems to be useless, we won't touch them anyway.

Comment (cthulhu-rider) [reply pkg/services/policer/check.go:151]: Maybe, but then we won't try to replicate them into the actual container.

File: pkg/services/policer/policer.go (hunk 3 above)
Comment (cthulhu-rider) [reply pkg/services/policer/policer.go:69]: This is a global network state, for example, is node in the network map or not.

File: pkg/services/policer/check.go (hunk 1 above)
Comment (cthulhu-rider) [reply pkg/services/policer/check.go:136]: Thought about that, but this is refactor, don't wanna mix it with the fix. Maybe I'll add it in after processing the main part.

File: cmd/neofs-node/netmap.go (hunk 2 above)
Comment (cthulhu-rider) [reply cmd/neofs-node/netmap.go:318]: Offline nodes don't reside network map. What do you mean by "able to replicate"? Anyone is able to replicate.

Comment (cthulhu-rider) [reply cmd/neofs-node/netmap.go:318]: > Why not doing it in `c.handleLocalNodeInfo()`?

Sure, missed the place.

File: pkg/services/policer/policer.go (hunk 4 above)
Comment (cthulhu-rider) [reply pkg/services/policer/policer.go:73]: Depends on interface name btw.

File: pkg/services/policer/check.go (hunk 5 above)
Comment (roman-khimov) [reply pkg/services/policer/check.go:151]: But we can't replicate anyway unless we're a part of the current netmap?

File: pkg/services/policer/check.go (hunk 1 above)
Comment (roman-khimov) [reply pkg/services/policer/check.go:136]: OK, I'm just thinking that this particular patch in some ways is necessary only because we have this default that is not safe.

File: cmd/neofs-node/netmap.go (hunk 2 above)
Comment (roman-khimov) [reply cmd/neofs-node/netmap.go]: > Anyone is able to replicate.

Nodes that are not a part of the map can't replicate (well, they can try, but their objects are not accepted by other nodes), so my question is can other nodes accept objects from nodes in "offline" state?

Comment (cthulhu-rider) [reply cmd/neofs-node/netmap.go]: There is no special logic for offline nodes.

**Review by roman-khimov — APPROVED** [review]
