### PR TITLE
ir: unify basic income collection and distribution, fix #3338

### LINKED ISSUE #3338: Payment test fails
## Current Behavior
https://rest.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/3166-1745943519/index.html#suites/44e11ced39071e8d0cfc11c5b94622ba/dbc5d8a0a60c31dd/

## Expected Behavior
Green.

## Possible Solution
Fix something.

## Steps to Reproduce
Run testcases with master (pre-0.46.0) node.

## Context
IR does transfers properly:
> debug	innerring/settlement.go:240	basic income: transfer was successfully sent	{"sender": "NZSjjg82QzeSsxtyx3iz6zoRoMijWMcE1U", "recipient": "NL1H4he1ggRajT1ZVqn23zveMRaH9jDvfh", "amount (GASe-12)": "279396772384", "details": "410200000000000000"}
> debug	innerring/settlement.go:240	basic income: transfer was successfully sent	{"sender": "NZSjjg82QzeSsxtyx3iz6zoRoMijWMcE1U", "recipient": "NL1H4he1ggRajT1ZVqn23zveMRaH9jDvfh", "amount (GASe-12)": "1676380634307", "details": "410300000000000000"}

and alike.

Test also check for balances of user wallet ("Ensure the user wallet balance is charged only once per epoch") and there are correct transfers there:
>  COMMAND: ./neofs-cli --config /home/runner/work/neofs-node/neofs-node/neofs-testcases/test-run-2025-04-29-15-00-10-473138/env_files/neofs-env-2025-04-29-15-58-35/cli_config_nodjqxqfeb.yml accounting balance --wallet '/home/runner/work/neofs-node/neofs-node/neofs-testcases/test-run-2025-04-29-15-00-10-473138/env_files/neofs-env-2025-04-29-15-58-35/deposit_withdrawal_test_wallet_kaioqthfes' --rpc-endpoint 'localhost:59203' --address 'NZSjjg82QzeSsxtyx3iz6zoRoMijWMcE1U'
RETCODE: 0
> 
> STDOUT:
> 91.45628714

Then

> COMMAND: ./neofs-cli --config /home/runner/work/neofs-node/neofs-node/neofs-testcases/test-run-2025-04-29-15-00-10-473138/env_files/neofs-env-2025-04-29-15-58-35/cli_config_nodjqxqfeb.yml accounting balance --wallet '/home/runner/work/neofs-node/neofs-node/neofs-testcases/test-run-2025-04-29-15-00-10-473138/env_files/neofs-env-2025-04-29-15-58-35/deposit_withdrawal_test_wallet_kaioqthfes' --rpc-endpoint 'localhost:59203' --address 'NZSjjg82QzeSsxtyx3iz6zoRoMijWMcE1U'
> RETCODE: 0
>
> STDOUT:
> 88.66231942

But for storage node (" Ensure the storage node balance is debited only once per epoch") test seems to be using some wrong address:
> COMMAND: ./neofs-cli --config /home/runner/work/neofs-node/neofs-node/neofs-testcases/test-run-2025-04-29-15-00-10-473138/env_files/neofs-env-2025-04-29-15-58-35/sn_1_gffvdmixws/sn_1_cli_config_irckuusoeh.yml accounting balance --wallet '/home/runner/work/neofs-node/neofs-node/neofs-testcases/test-run-2025-04-29-15-00-10-473138/env_files/neofs-env-2025-04-29-15-58-35/sn_1_gffvdmixws/sn_1_wallet_zfxphluuzo' --rpc-endpoint 'localhost:59203' --address 'NQiRkviaJYi5VeaAqD6pYkh61BWVkqxTuS'
> RETCODE: 0
> 
> STDOUT:
> 0

Theoretically, it can be an IR issue (wrong address there), but it doesn't seem to be likely.

## Regression
Unknown.

### PR DESCRIPTION
**Pull request by roman-khimov**
Distribution is tightly related to collection and if we run them asynchronously we easily end up with

    info	settlement/calls.go:54	start basic income collection	{"epoch": 5}
    info	settlement/calls.go:99	start basic income distribution	{"epoch": 5}
    info	basic/distribute.go:17	zero total size of all estimated containers, skip distribution of funds

Even though there are valid estimations:

    debug	innerring/settlement.go:240	basic income: transfer was successfully sent	{"sender": "NPBzbkvZUcWjyMNmiQr8hXGg1E7jjHxkqe", "recipient": "NL1H4he1ggRajT1ZVqn23zveMRaH9jDvfh", "amount (GASe-12)": "1303851604461", "details": "410500000000000000"}

### CODE REVIEW

**Comment by roman-khimov** [comment]
This certainly works better, but not perfect still: https://rest.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/3230-1747150272/index.html#suites/44e11ced39071e8d0cfc11c5b94622ba/33859e953b337a64/

Distribution phase checks for balance and in the first iteration it can be zero since collection transactions have not been accepted yet.

File: pkg/innerring/processors/settlement/calls.go [hunk 1]
```diff
@@ -72,51 +59,16 @@ func (p *Processor) HandleIncomeCollectionEvent(e event.Event) {
...
-
-	p.contextMu.Lock()
-	defer p.contextMu.Unlock()
-
-	incomeCtx, ok := p.incomeContexts[epoch]
-	delete(p.incomeContexts, epoch)
-
-	if !ok {
-		p.log.Warn("income context distribution does not exists",
+		p.log.Info("start basic income distribution",
```
Comment (carpawell) [inline pkg/innerring/processors/settlement/calls.go:66]: are both logs still necessary?

**Review by carpawell — APPROVED** [review]

File: pkg/innerring/processors/settlement/calls.go (hunk 1 above)
Comment (roman-khimov) [reply pkg/innerring/processors/settlement/calls.go:66]: I think they're still useful. Separate stages of the same process.

**Comment by roman-khimov** [comment]
Finally green: https://rest.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/3239-1747173788/index.html#suites/44e11ced39071e8d0cfc11c5b94622ba/346dd92d00dafb8d/

File: pkg/morph/client/balance/transfer.go [hunk 2]
```diff
@@ -8,24 +8,12 @@ import (
...
-
-	Details []byte
-
-	client.InvokePrmOptional
-}
-
 // TransferX transfers p.Amount of GASe-12 from p.From to p.To
 // with details p.Details through direct smart contract call.
-func (c *Client) TransferX(p TransferPrm) error {
+func (c *Client) TransferX(from user.ID, to user.ID, amount *big.Int, details []byte) error {
```
Comment (cthulhu-rider) [inline pkg/morph/client/balance/transfer.go:13]: docs need to be changed also then

**Review by cthulhu-rider — APPROVED** [review]

**Comment by cthulhu-rider** [comment]
this fixes smth, lets changelog

File: pkg/morph/client/balance/transfer.go (hunk 2 above)
Comment (roman-khimov) [reply pkg/morph/client/balance/transfer.go:13]: Fixed.

**Comment by roman-khimov** [comment]
Sure, I was waiting for test results mostly, now that we're green there is a proper change log as well.
