### PR TITLE
fix/Simplify docker images

### LINKED ISSUE #2379: docker is intendent to run app not OS
neo binaries are static:

```
# ldd /usr/bin/neofs-cli 
	not a dynamic executable
# ldd /usr/bin/neofs-cli 
	not a dynamic executable
```

alpine and bash are not required, please remove them from docker image

### PR DESCRIPTION
**Pull request by carpawell**
Closes #2379. Tested with https://github.com/nspcc-dev/neofs-dev-env/pull/272.

### CODE REVIEW

File: cmd/neofs-cli/modules/control/healthcheck.go [hunk 1]
```diff
@@ -60,8 +61,17 @@ func healthCheck(cmd *cobra.Command, _ []string) {
 
 	verifyResponse(cmd, resp.GetSignature(), resp.GetBody())
 
+	healthStatus := resp.GetBody().GetHealthStatus()
+
 	cmd.Printf("Network status: %s\n", resp.GetBody().GetNetmapStatus())
-	cmd.Printf("Health status: %s\n", resp.GetBody().GetHealthStatus())
+	cmd.Printf("Health status: %s\n", healthStatus)
+
+	switch healthStatus {
```
Comment (roman-khimov) [inline cmd/neofs-cli/modules/control/healthcheck.go:69]: Can be simplified, we don't have many options now.

**Review by 532910 — APPROVED** [review]

**Review by cthulhu-rider — APPROVED** [review]

File: cmd/neofs-cli/modules/control/healthcheck.go (hunk 1 above)
Comment (carpawell) [reply cmd/neofs-cli/modules/control/healthcheck.go]: find `switch` way more explicit for a reader but dont mind

**Review by roman-khimov — APPROVED** [review]
