### PR TITLE
meta: handle case-insensitive address mismatch in resync 

### LINKED ISSUE #3960: After nodes restart with metabase deletion in between objects are not available from all expected nodes
1. Create a locked object and see that it is located on 2 nodes:
```
COMMAND: ./neofs-cli --config /Users/runner/work/neofs-testcases/neofs-testcases/neofs-testcases/test-run-2026-04-20-14-46-29-455129/cli_config_qeygmotnks.yml object put --rpc-endpoint 'localhost:52449' --wallet '/Users/runner/work/neofs-testcases/neofs-testcases/neofs-testcases/test-run-2026-04-20-14-46-29-455129/wallet-fee2ee72-1fa1-40b6-a608-5c78e41b2b86.json' --cid '5aWiCcpCZuyLSzuk4oUaMC1rhSycm4jcBAzv4bir9xhi' --file '/Users/runner/work/neofs-testcases/neofs-testcases/neofs-testcases/test-run-2026-04-20-14-46-29-455129/TestFilesDir/temp_file_b6cd9fe8-0274-4b84-b0e1-7383a8c770a0' --expire-at 88 --no-progress --timeout '180s'
RETCODE: 0

STDOUT:
[/Users/runner/work/neofs-testcases/neofs-testcases/neofs-testcases/test-run-2026-04-20-14-46-29-455129/TestFilesDir/temp_file_b6cd9fe8-0274-4b84-b0e1-7383a8c770a0] Object successfully stored
  OID: 5RzTzLiNAfdhdKj8gTYDTEXxVk315jjSEdU2X6Cf1i4K
  CID: 5aWiCcpCZuyLSzuk4oUaMC1rhSycm4jcBAzv4bir9xhi

STDERR:

Start / End / Elapsed	 15:33:24.990720 / 15:33:25.301155 / 0:00:00.310435
```

Current epoch is 78:
```
COMMAND: ./neofs-cli --config /Users/runner/work/neofs-testcases/neofs-testcases/neofs-testcases/test-run-2026-04-20-14-46-29-455129/env_files/neofs-env-2026-04-20-15-05-48-8541545024/sn_1_rdjicritzr/sn_1_cli_config_lpeokloyte.yml netmap epoch --rpc-endpoint 'localhost:52449' --wallet '/Users/runner/work/neofs-testcases/neofs-testcases/neofs-testcases/test-run-2026-04-20-14-46-29-455129/env_files/neofs-env-2026-04-20-15-05-48-8541545024/sn_1_rdjicritzr/sn_1_wallet_mgwdlykivq'
RETCODE: 0

STDOUT:
78

STDERR:

Start / End / Elapsed	 15:33:24.951249 / 15:33:24.986591 / 0:00:00.035342
```

First node:

```
COMMAND: ./neofs-cli --config /Users/runner/work/neofs-testcases/neofs-testcases/neofs-testcases/test-run-2026-04-20-14-46-29-455129/env_files/neofs-env-2026-04-20-15-05-48-8541545024/sn_2_fgywdhozgk/sn_2_cli_config_xgjnvnanzp.yml object head --rpc-endpoint 'localhost:52453' --wallet '/Users/runner/work/neofs-testcases/neofs-testcases/neofs-testcases/test-run-2026-04-20-14-46-29-455129/env_files/neofs-env-2026-04-20-15-05-48-8541545024/sn_2_fgywdhozgk/sn_2_wallet_uasggufulm' --cid '5aWiCcpCZuyLSzuk4oUaMC1rhSycm4jcBAzv4bir9xhi' --oid '5RzTzLiNAfdhdKj8gTYDTEXxVk315jjSEdU2X6Cf1i4K' --json --ttl 1
RETCODE: 0

STDOUT:
{"objectID":{"value":"QdWp0ooUCe+DvDbM17GwaypPAerzCF8wZ33bIRm+uwQ="}, "signature":{"key":"AjC5Sjioe9zEs+CRRCMIxr05HCQtXpa8FqCuQNtw1tOq", "signature":"BKOy/P7ZsWz9ea/DdPYXu2sVDhx5HgtDuRtym8+GX9MxtbmZa5UQzgseCgrC7WhGA1vd1HDQIr+FCcMRIfZp9l8=", "scheme":"ECDSA_SHA512"}, "header":{"version":{"major":2, "minor":22}, "containerID":{"value":"RASCDJmDXqLdxaIvYVUZFqEODYxMt5msw6YLyYs8euU="}, "ownerID":{"value":"NcYCvPYPUIgjELSU9z8SNaOVoiVFZxjfPA=="}, "creationEpoch":"78", "payloadLength":"1000", "payloadHash":{"type":"SHA256", "sum":"WTbbSzQPD33Y9O+wu5NeRNJgCg6gKOhMVIULC40uHR0="}, "objectType":"REGULAR", "homomorphicHash":{"type":"TZ", "sum":"Bp3FC1Z0o7BeODNqLJ3mVAlSYgIYATcZ3InvYldD1jUkWuRXxKi58EeBmkmgmAZwMj3NeMrzTb3xZyqhguYVow=="}, "sessionToken":null, "attributes":[{"key":"FileName", "value":"temp_file_b6cd9fe8-0274-4b84-b0e1-7383a8c770a0"}, {"key":"Timestamp", "value":"1776699205"}, {"key":"__NEOFS__EXPIRATION_EPOCH", "value":"88"}], "split":null, "sessionTokenV2":{"body":{"version":0, "appdata":"", "issuer":{"value":"NcYCvPYPUIgjELSU9z8SNaOVoiVFZxjfPA=="}, "subjects":[{"ownerID":{"value":"NX7qoNSx9b3dvp6RWHNeMBUgOpZAgms73Q=="}}, {"ownerID":{"value":"NXbKe88cwmknErPCX9mlkNUC1VHVM7A2Eg=="}}], "lifetime":{"exp":"1776735205", "nbf":"1776699175", "iat":"1776699175"}, "contexts":[{"container":{"value":"RASCDJmDXqLdxaIvYVUZFqEODYxMt5msw6YLyYs8euU="}, "verbs":["OBJECT_PUT"]}], "final":true}, "signature":{"key":"A/ogef03h9SKMbW6XdBPulUY2JZ2D0EOiX1/6LURDJkQ", "signature":"BKo9SHDvJQ/I/BvxJ+miJInxSXy90iWFQBnmUGxm8Jcs7oN34svy4EvWLmG+XvtmeoQU6MC6ajEGl13wa8oqjVU=", "scheme":"ECDSA_SHA512"}, "origin":null}}, "payload":""}

STDERR:

Start / End / Elapsed	 15:33:26.930494 / 15:33:27.184071 / 0:00:00.253577
```

Second node:

```
COMMAND: ./neofs-cli --config /Users/runner/work/neofs-testcases/neofs-testcases/neofs-testcases/test-run-2026-04-20-14-46-29-455129/env_files/neofs-env-2026-04-20-15-05-48-8541545024/sn_3_hfqmvghems/sn_3_cli_config_swgzknwlmn.yml object head --rpc-endpoint 'localhost:52457' --wallet '/Users/runner/work/neofs-testcases/neofs-testcases/neofs-testcases/test-run-2026-04-20-14-46-29-455129/env_files/neofs-env-2026-04-20-15-05-48-8541545024/sn_3_hfqmvghems/sn_3_wallet_zcjiikovgm' --cid '5aWiCcpCZuyLSzuk4oUaMC1rhSycm4jcBAzv4bir9xhi' --oid '5RzTzLiNAfdhdKj8gTYDTEXxVk315jjSEdU2X6Cf1i4K' --json --ttl 1
RETCODE: 0

STDOUT:
{"objectID":{"value":"QdWp0ooUCe+DvDbM17GwaypPAerzCF8wZ33bIRm+uwQ="}, "signature":{"key":"AjC5Sjioe9zEs+CRRCMIxr05HCQtXpa8FqCuQNtw1tOq", "signature":"BKOy/P7ZsWz9ea/DdPYXu2sVDhx5HgtDuRtym8+GX9MxtbmZa5UQzgseCgrC7WhGA1vd1HDQIr+FCcMRIfZp9l8=", "scheme":"ECDSA_SHA512"}, "header":{"version":{"major":2, "minor":22}, "containerID":{"value":"RASCDJmDXqLdxaIvYVUZFqEODYxMt5msw6YLyYs8euU="}, "ownerID":{"value":"NcYCvPYPUIgjELSU9z8SNaOVoiVFZxjfPA=="}, "creationEpoch":"78", "payloadLength":"1000", "payloadHash":{"type":"SHA256", "sum":"WTbbSzQPD33Y9O+wu5NeRNJgCg6gKOhMVIULC40uHR0="}, "objectType":"REGULAR", "homomorphicHash":{"type":"TZ", "sum":"Bp3FC1Z0o7BeODNqLJ3mVAlSYgIYATcZ3InvYldD1jUkWuRXxKi58EeBmkmgmAZwMj3NeMrzTb3xZyqhguYVow=="}, "sessionToken":null, "attributes":[{"key":"FileName", "value":"temp_file_b6cd9fe8-0274-4b84-b0e1-7383a8c770a0"}, {"key":"Timestamp", "value":"1776699205"}, {"key":"__NEOFS__EXPIRATION_EPOCH", "value":"88"}], "split":null, "sessionTokenV2":{"body":{"version":0, "appdata":"", "issuer":{"value":"NcYCvPYPUIgjELSU9z8SNaOVoiVFZxjfPA=="}, "subjects":[{"ownerID":{"value":"NX7qoNSx9b3dvp6RWHNeMBUgOpZAgms73Q=="}}, {"ownerID":{"value":"NXbKe88cwmknErPCX9mlkNUC1VHVM7A2Eg=="}}], "lifetime":{"exp":"1776735205", "nbf":"1776699175", "iat":"1776699175"}, "contexts":[{"container":{"value":"RASCDJmDXqLdxaIvYVUZFqEODYxMt5msw6YLyYs8euU="}, "verbs":["OBJECT_PUT"]}], "final":true}, "signature":{"key":"A/ogef03h9SKMbW6XdBPulUY2JZ2D0EOiX1/6LURDJkQ", "signature":"BKo9SHDvJQ/I/BvxJ+miJInxSXy90iWFQBnmUGxm8Jcs7oN34svy4EvWLmG+XvtmeoQU6MC6ajEGl13wa8oqjVU=", "scheme":"ECDSA_SHA512"}, "origin":null}}, "payload":""}

STDERR:

Start / End / Elapsed	 15:33:27.185810 / 15:33:27.440200 / 0:00:00.254390
```

2. Try to delete the locked object:

```
COMMAND: ./neofs-cli --config /Users/runner/work/neofs-testcases/neofs-testcases/neofs-testcases/wallet_config.yml object delete --rpc-endpoint 'localhost:52449' --wallet '/Users/runner/work/neofs-testcases/neofs-testcases/neofs-testcases/test-run-2026-04-20-14-46-29-455129/wallet-fee2ee72-1fa1-40b6-a608-5c78e41b2b86.json' --cid '5aWiCcpCZuyLSzuk4oUaMC1rhSycm4jcBAzv4bir9xhi' --oid '5RzTzLiNAfdhdKj8gTYDTEXxVk315jjSEdU2X6Cf1i4K'
RETCODE: 1

STDOUT:
Error: rpc error: deleting 5RzTzLiNAfdhdKj8gTYDTEXxVk315jjSEdU2X6Cf1i4K object: remove object via client: status: code = 1024 message = incomplete object PUT by placement: number of replicas cannot be met for list #0: 2 required, 0 nodes remaining (last node error: could not close object stream: replicate object to remote node (key=032c3a34759b5b4cdf29545f72a0d67cb90d8fcb6ccddcf8d2daf5872bd96f1586): /dns4/localhost/tcp/52461: status: code = 1024 message = failed to verify and store object locally: could not put object to local storage: failed to broadcast TOMBSTONE object to any shard, last error: could not put object to metabase: status: code = 2050 message = object is locked)

STDERR:

Start / End / Elapsed	 15:33:27.697771 / 15:33:28.011244 / 0:00:00.313473
```

3. Stop nodes and delete metabase files
4. Issue meta resync on all nodes:

```
COMMAND: ./neofs-lens  meta resync --blobstor '/Users/runner/work/neofs-testcases/neofs-testcases/neofs-testcases/test-run-2026-04-20-14-46-29-455129/env_files/neofs-env-2026-04-20-15-05-48-8541545024/shards/shard_fstree_yaekzvtetz' --path '/Users/runner/work/neofs-testcases/neofs-testcases/neofs-testcases/test-run-2026-04-20-14-46-29-455129/env_files/neofs-env-2026-04-20-15-05-48-8541545024/sn_2_fgywdhozgk/shard_metabase_orukhipbhd'
RETCODE: 0

STDOUT:
Iterating over blobstor objects...
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/2AAboZQpMPSZX31AjvPUM6KVkFAWVCYpt81Ft1ndx9SD: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/2aAboZQpMPSZX31AjvPUM6KVkFAWVCYpt81Ft1ndx9SD does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/2AAboZQpMPSZX31AjvPUM6KVkFAWVCYpt81Ft1ndx9SD
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/2eFyvRboXvbNavFpbVVL7wqfbWgGdK777G8i2xjj1Uzp: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/2EFyvRboXvbNavFpbVVL7wqfbWgGdK777G8i2xjj1Uzp does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/2eFyvRboXvbNavFpbVVL7wqfbWgGdK777G8i2xjj1Uzp
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/2eccs7xhuCKQghQtqmiZ6Jfyv8EF8yGCGzXrveRPjd1Y: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/2Eccs7xhuCKQghQtqmiZ6Jfyv8EF8yGCGzXrveRPjd1Y does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/2eccs7xhuCKQghQtqmiZ6Jfyv8EF8yGCGzXrveRPjd1Y
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/3BymqXN7wv5ZbsttjB64j4UdN2qqDyEdBhYAg3e8yJ7N: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/3bymqXN7wv5ZbsttjB64j4UdN2qqDyEdBhYAg3e8yJ7N does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/3BymqXN7wv5ZbsttjB64j4UdN2qqDyEdBhYAg3e8yJ7N
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/3Jaj9iz1N3CPmewhML7Vqo5Cdb5pqpuVJErqfAiR3GqX: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/3jaj9iz1N3CPmewhML7Vqo5Cdb5pqpuVJErqfAiR3GqX does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/3Jaj9iz1N3CPmewhML7Vqo5Cdb5pqpuVJErqfAiR3GqX
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/3sCe8U9cAka65AAakniyTpYztxziMzLmwhnEoX1cnTCr: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/3SCe8U9cAka65AAakniyTpYztxziMzLmwhnEoX1cnTCr does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/3sCe8U9cAka65AAakniyTpYztxziMzLmwhnEoX1cnTCr
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/3vcehVTVZSJnyvToFF9tzms4WVicfZqfysfoZw2LVsN1: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/3VcehVTVZSJnyvToFF9tzms4WVicfZqfysfoZw2LVsN1 does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/3vcehVTVZSJnyvToFF9tzms4WVicfZqfysfoZw2LVsN1
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/4yjTVDaFXKMVc8DWF57f6YNwtmmvXQFb1qoH3RmQHwzn: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/4YjTVDaFXKMVc8DWF57f6YNwtmmvXQFb1qoH3RmQHwzn does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/4yjTVDaFXKMVc8DWF57f6YNwtmmvXQFb1qoH3RmQHwzn
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/6BnLmYogP4qG5iUHFca8vJ1is3nBw4MPhAyWaJv7GsEf: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/6bnLmYogP4qG5iUHFca8vJ1is3nBw4MPhAyWaJv7GsEf does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/6BnLmYogP4qG5iUHFca8vJ1is3nBw4MPhAyWaJv7GsEf
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/7BfkR9g72NwtEN8rAb7knxCNX7NVkhZcST7iRomVoJEw: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/7bfkR9g72NwtEN8rAb7knxCNX7NVkhZcST7iRomVoJEw does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/7BfkR9g72NwtEN8rAb7knxCNX7NVkhZcST7iRomVoJEw
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/7uP3PcqWzHCrVjS8Fgd8gTFdvH5494pyMyjJ85WG5VRg: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/7UP3PcqWzHCrVjS8Fgd8gTFdvH5494pyMyjJ85WG5VRg does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/7uP3PcqWzHCrVjS8Fgd8gTFdvH5494pyMyjJ85WG5VRg
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/7wGY2MTt8AMXE5Z7eM4zvjLMp2Nik7qn1cq5ZjBrnh1c: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/7WGY2MTt8AMXE5Z7eM4zvjLMp2Nik7qn1cq5ZjBrnh1c does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/7wGY2MTt8AMXE5Z7eM4zvjLMp2Nik7qn1cq5ZjBrnh1c
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/8GaxyXro5zbsiezEXTNcMk7gAVu9QVVnh9HiWtvwqGE4: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/8gaxyXro5zbsiezEXTNcMk7gAVu9QVVnh9HiWtvwqGE4 does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/8GaxyXro5zbsiezEXTNcMk7gAVu9QVVnh9HiWtvwqGE4
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/8M6CsZRp5ot5aAkbuGRt56ZeL5g3GekFd1z64o14Rs6q: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/8m6CsZRp5ot5aAkbuGRt56ZeL5g3GekFd1z64o14Rs6q does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/8M6CsZRp5ot5aAkbuGRt56ZeL5g3GekFd1z64o14Rs6q
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/8TH1pDRJATjU4UY5NiEAy2wU8LEThvswcZdWJNbzT3vs: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/8tH1pDRJATjU4UY5NiEAy2wU8LEThvswcZdWJNbzT3vs does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/8TH1pDRJATjU4UY5NiEAy2wU8LEThvswcZdWJNbzT3vs
warn: object GTNq6iPQMUTiQgEkqrwuTSzA9trDa5gyVNNDGMUmz7WT/9ErPDLAsYnn8Kvw5XNrQVV75VgSZzcBwgx16mepixX7F: unmarshalled object address GTNq6iPQMUTiQgEkqrwuTSzA9trDa5gyVNNDGMUmz7WT/9erPDLAsYnn8Kvw5XNrQVV75VgSZzcBwgx16mepixX7F does not match expected address GTNq6iPQMUTiQgEkqrwuTSzA9trDa5gyVNNDGMUmz7WT/9ErPDLAsYnn8Kvw5XNrQVV75VgSZzcBwgx16mepixX7F
warn: object 4KzLWpknEbL3ifJL8ib1jXFyRp3Bm28N6KPnckTpEYg6/9XurPN32ULtJ4YG2iDMk5HmvKaAhz7bGsLTPrAWVATo9: unmarshalled object address 4KzLWpknEbL3ifJL8ib1jXFyRp3Bm28N6KPnckTpEYg6/9xurPN32ULtJ4YG2iDMk5HmvKaAhz7bGsLTPrAWVATo9 does not match expected address 4KzLWpknEbL3ifJL8ib1jXFyRp3Bm28N6KPnckTpEYg6/9XurPN32ULtJ4YG2iDMk5HmvKaAhz7bGsLTPrAWVATo9
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/9uTFUXGGdXhgXSBxLFwmk1Jdu44eXeUk3PU1dZuWAMpJ: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/9UTFUXGGdXhgXSBxLFwmk1Jdu44eXeUk3PU1dZuWAMpJ does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/9uTFUXGGdXhgXSBxLFwmk1Jdu44eXeUk3PU1dZuWAMpJ
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/BHjSU2aYSebemRfEfuNBdsFrTQbuRekbnVTgf5sF3WuE: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/BhjSU2aYSebemRfEfuNBdsFrTQbuRekbnVTgf5sF3WuE does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/BHjSU2aYSebemRfEfuNBdsFrTQbuRekbnVTgf5sF3WuE
warn: object 5aWiCcpCZuyLSzuk4oUaMC1rhSycm4jcBAzv4bir9xhi/BrsK93wkWCvxfLSpBty2cMKyygyrJoz4m8hhtct64uyW: unmarshalled object address 5aWiCcpCZuyLSzuk4oUaMC1rhSycm4jcBAzv4bir9xhi/BRsK93wkWCvxfLSpBty2cMKyygyrJoz4m8hhtct64uyW does not match expected address 5aWiCcpCZuyLSzuk4oUaMC1rhSycm4jcBAzv4bir9xhi/BrsK93wkWCvxfLSpBty2cMKyygyrJoz4m8hhtct64uyW
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/Bv29cumZ2PifxZi1N3oM8JT1TGvswqq62M3AXHEHKx5i: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/BV29cumZ2PifxZi1N3oM8JT1TGvswqq62M3AXHEHKx5i does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/Bv29cumZ2PifxZi1N3oM8JT1TGvswqq62M3AXHEHKx5i
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/CBXsuz25Vn56FDv61wBJR9rxhycaN5QHZJ58unwUbqd9: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/CbXsuz25Vn56FDv61wBJR9rxhycaN5QHZJ58unwUbqd9 does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/CBXsuz25Vn56FDv61wBJR9rxhycaN5QHZJ58unwUbqd9
warn: object 4vMvZ9aE9uPxN6oYk6QLbwTrbymGMxbMBqZm16Je12Ee/CsV6CShyhaGTyj8NrCXp93dA5aWbpGeJJNvdAXxkuSAm: unmarshalled object address 4vMvZ9aE9uPxN6oYk6QLbwTrbymGMxbMBqZm16Je12Ee/CSV6CShyhaGTyj8NrCXp93dA5aWbpGeJJNvdAXxkuSAm does not match expected address 4vMvZ9aE9uPxN6oYk6QLbwTrbymGMxbMBqZm16Je12Ee/CsV6CShyhaGTyj8NrCXp93dA5aWbpGeJJNvdAXxkuSAm
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/D3oBLoizvHkQwzuoziFLP3Lw4KP9FLnDitVkAdctp5A: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/d3oBLoizvHkQwzuoziFLP3Lw4KP9FLnDitVkAdctp5A does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/D3oBLoizvHkQwzuoziFLP3Lw4KP9FLnDitVkAdctp5A
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/EgSSNnPqH3cyQq2caBp5AxadrKbRcpFhawjoRnbadqMd: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/EGSSNnPqH3cyQq2caBp5AxadrKbRcpFhawjoRnbadqMd does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/EgSSNnPqH3cyQq2caBp5AxadrKbRcpFhawjoRnbadqMd
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/FBy1X1ZuGinNKtvcNvco7oprvq5e5wTRMtBrDj7Q6kwu: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/Fby1X1ZuGinNKtvcNvco7oprvq5e5wTRMtBrDj7Q6kwu does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/FBy1X1ZuGinNKtvcNvco7oprvq5e5wTRMtBrDj7Q6kwu
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/FC4QykqvDTXiMsNzssXJMjcrMTot3u3jDNRJafTUCYf7: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/Fc4QykqvDTXiMsNzssXJMjcrMTot3u3jDNRJafTUCYf7 does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/FC4QykqvDTXiMsNzssXJMjcrMTot3u3jDNRJafTUCYf7
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/FmKCxR7GPvipWog5MbEYVirPZzsDQfJ1oLtcUgN5MSCH: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/FMKCxR7GPvipWog5MbEYVirPZzsDQfJ1oLtcUgN5MSCH does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/FmKCxR7GPvipWog5MbEYVirPZzsDQfJ1oLtcUgN5MSCH
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/GHaUziwHFgGTLjzu39k8z4MWKcLgnpUFaUyRysuNWRD: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/ghaUziwHFgGTLjzu39k8z4MWKcLgnpUFaUyRysuNWRD does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/GHaUziwHFgGTLjzu39k8z4MWKcLgnpUFaUyRysuNWRD
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/GSiZXQV7aK6Yv7eWk9pHRgshpncG5Pv8EsQxYU3GxMPX: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/GsiZXQV7aK6Yv7eWk9pHRgshpncG5Pv8EsQxYU3GxMPX does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/GSiZXQV7aK6Yv7eWk9pHRgshpncG5Pv8EsQxYU3GxMPX
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/Gc45q3UMxaLaG1hQMVLy7wQ3zKZgiPFBEee7Cd9YQRpk: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/GC45q3UMxaLaG1hQMVLy7wQ3zKZgiPFBEee7Cd9YQRpk does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/Gc45q3UMxaLaG1hQMVLy7wQ3zKZgiPFBEee7Cd9YQRpk
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/GdLyFwJDhx8baN3wC11VdUTCPEr6SW7jCQtJBTfgpmNF: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/GDLyFwJDhx8baN3wC11VdUTCPEr6SW7jCQtJBTfgpmNF does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/GdLyFwJDhx8baN3wC11VdUTCPEr6SW7jCQtJBTfgpmNF
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/Geohu8qp8Sw1FAvN2qkwFN1NUUWqJAiPtwtETEN5XRfK: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/GEohu8qp8Sw1FAvN2qkwFN1NUUWqJAiPtwtETEN5XRfK does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/Geohu8qp8Sw1FAvN2qkwFN1NUUWqJAiPtwtETEN5XRfK
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/HS8scWo7h1XWd37sKrKU7xN7NefWVGHEVw5UKZPSsHha: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/Hs8scWo7h1XWd37sKrKU7xN7NefWVGHEVw5UKZPSsHha does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/HS8scWo7h1XWd37sKrKU7xN7NefWVGHEVw5UKZPSsHha
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/HZD5u9U4v5RK73QozASvStVZVUAtGH9dcF1ANkDZ5U75: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/HzD5u9U4v5RK73QozASvStVZVUAtGH9dcF1ANkDZ5U75 does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/HZD5u9U4v5RK73QozASvStVZVUAtGH9dcF1ANkDZ5U75
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/HkKvwouaizW6CxvmsVjtG2DtMNTG8eTs9CGUUYzC2bKX: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/HKKvwouaizW6CxvmsVjtG2DtMNTG8eTs9CGUUYzC2bKX does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/HkKvwouaizW6CxvmsVjtG2DtMNTG8eTs9CGUUYzC2bKX
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/HkinfMqGfMLgoLQ6K4e8cV1YrvLv1gi3wXzDcEWje8ea: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/HKinfMqGfMLgoLQ6K4e8cV1YrvLv1gi3wXzDcEWje8ea does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/HkinfMqGfMLgoLQ6K4e8cV1YrvLv1gi3wXzDcEWje8ea
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/PuvUBFYBYtXmMxbFukR9PWA1TuqVvzyfWXVXPTUx23G: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/puvUBFYBYtXmMxbFukR9PWA1TuqVvzyfWXVXPTUx23G does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/PuvUBFYBYtXmMxbFukR9PWA1TuqVvzyfWXVXPTUx23G
warn: object G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/mDL66HPd4dj4Va91GjheEjBzrraS5gQCEr1rCnBxnqK: unmarshalled object address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/MDL66HPd4dj4Va91GjheEjBzrraS5gQCEr1rCnBxnqK does not match expected address G2iYUXbajCYnwovSn1oLq1sK8jF6Vr43Yk7YUJDMxxGj/mDL66HPd4dj4Va91GjheEjBzrraS5gQCEr1rCnBxnqK
Metabase resync completed successfully.

STDERR:

Start / End / Elapsed	 15:33:43.170024 / 15:33:43.338465 / 0:00:00.168441
```

5. Log fstree contents from the first and second nodes, we can see our object from both nodes:

```
COMMAND: ./neofs-lens  fstree list --path '/Users/runner/work/neofs-testcases/neofs-testcases/neofs-testcases/test-run-2026-04-20-14-46-29-455129/env_files/neofs-env-2026-04-20-15-05-48-8541545024/shards/shard_fstree_cbflwkvgoi'
RETCODE: 0
...
5aWiCcpCZuyLSzuk4oUaMC1rhSycm4jcBAzv4bir9xhi/5rzTzLiNAfdhdKj8gTYDTEXxVk315jjSEdU2X6Cf1i4K

COMMAND: ./neofs-lens  fstree list --path '/Users/runner/work/neofs-testcases/neofs-testcases/neofs-testcases/test-run-2026-04-20-14-46-29-455129/env_files/neofs-env-2026-04-20-15-05-48-8541545024/shards/shard_fstree_zumahfnkve'
RETCODE: 0
...
5aWiCcpCZuyLSzuk4oUaMC1rhSycm4jcBAzv4bir9xhi/5RzTzLiNAfdhdKj8gTYDTEXxVk315jjSEdU2X6Cf1i4K
```
6. Start nodes, wait until they are ready, try to query both nodes for an object, it is now missing from one of the nodes:

```
COMMAND: ./neofs-cli --config /Users/runner/work/neofs-testcases/neofs-testcases/neofs-testcases/test-run-2026-04-20-14-46-29-455129/env_files/neofs-env-2026-04-20-15-05-48-8541545024/sn_2_fgywdhozgk/sn_2_cli_config_xgjnvnanzp.yml object head --rpc-endpoint 'localhost:52453' --wallet '/Users/runner/work/neofs-testcases/neofs-testcases/neofs-testcases/test-run-2026-04-20-14-46-29-455129/env_files/neofs-env-2026-04-20-15-05-48-8541545024/sn_2_fgywdhozgk/sn_2_wallet_uasggufulm' --cid '5aWiCcpCZuyLSzuk4oUaMC1rhSycm4jcBAzv4bir9xhi' --oid '5RzTzLiNAfdhdKj8gTYDTEXxVk315jjSEdU2X6Cf1i4K' --json --ttl 1
RETCODE: 1

STDOUT:
Error: rpc error: read object header via client: status: code = 2049 message = object not found

STDERR:

Start / End / Elapsed	 15:33:57.456374 / 15:33:57.711730 / 0:00:00.255356
```

I would expect an object to still be available after nodes restart.

Logs: 

[433f3a87d3f1872d.zip](https://github.com/user-attachments/files/26939037/433f3a87d3f1872d.zip)

https://rest.fs.neo.org/Aku38wpn2xEqfEPxmwyAa7N3VnAkMV8PEVkpLqwKM1z3/1767-1776705185/index.html#suites/295ed2e000f8fa6f3ade59cc13b98615/4d3e993705a982f/

tests.object.test_object_lock.TestObjectLockWithGrpc#test_the_object_lock_should_be_kept_after_metabase_deletion

Unfortunately, this is a flaky issue, didn't managed to reproduce it locally.

### PR DESCRIPTION
**Pull request by End-rey**
Closes #3960.

### CODE REVIEW

File: pkg/local_object_storage/blobstor/fstree/doc.go [hunk 1]
```diff
@@ -53,5 +53,13 @@ them in the FS tree, so finding a file containing some object doesn't require
 any additional effort. Finding it in the file contents however requires
 reading the prefix described above, comparing the target OID and either
 skipping the object length specified there or reading it after the prefix.
+
+Note on File Systems and Case-Sensitivity:
```
Comment (roman-khimov) [inline pkg/local_object_storage/blobstor/fstree/doc.go]: We need it somewhere in user-facing docs, no one will find it here. Add a new document if nothing else fits.

File: pkg/local_object_storage/metabase/control.go [hunk 2]
```diff
@@ -278,7 +279,17 @@ func (rh *resyncHandler) handle(addr oid.Address, data []byte) error {
...
 	if obj.Address() != addr {
-		return rh.onError(addr, fmt.Errorf("unmarshalled object address %s does not match expected address %s", obj.Address(), addr))
+		objAddrStr := obj.Address().String()
+		expectedAddrStr := addr.String()
+
+		if !strings.EqualFold(objAddrStr, expectedAddrStr) {
+			return rh.onError(addr, fmt.Errorf("unmarshalled object address %s does not match expected address %s", objAddrStr, expectedAddrStr))
+		}
+
+		rh.db.log.Warn("unmarshalled object address differs only by case",
```
Comment (roman-khimov) [inline pkg/local_object_storage/metabase/control.go]: `s/only//` and it can be Info, we're allowing it anyway.

**Comment by roman-khimov** [comment]
Whitespace check failing

**Review by roman-khimov — APPROVED** [review]
