### PR TITLE
Use iterators for container listings

### LINKED ISSUE #3045: Use iterators for container listings
https://github.com/nspcc-dev/neofs-contract/pull/300

## Expected Behavior
New container listing with no result length restriction is used.

## Current Behavior
New API is not used. [List](https://github.com/nspcc-dev/neofs-node/blob/3129bdeadc87017c95d4877b82c57e64db5539f8/cmd/neofs-node/cache.go#L322) is the only option for now.

## Possible Solution
Add new method to `morph` package, use it.

## Steps to Reproduce (for bugs)
Take a look at `morph` pkg or search for "containersOf" const.

## Context
https://github.com/nspcc-dev/neofs-contract/pull/300

## Regression
No.

## Your Environment
0.44.0

### PR DESCRIPTION
**Pull request by End-rey**
Closes #3045.

### CODE REVIEW

**Review by roman-khimov — APPROVED** [review]

File: pkg/morph/client/container/list.go [hunk 1]
```diff
@@ -15,26 +15,18 @@ import (
 // Returns the identifiers of all NeoFS containers if pointer
 // to user identifier is nil.
 func (c *Client) List(idUser *user.ID) ([]cid.ID, error) {
-	var rawID []byte
+	// neo-go's stack elements default limit
+	// is 2048, make it less a little
+	const prefetchNumber = 2000
 
+	var rawIdUser []byte
```
Comment (cthulhu-rider) [inline pkg/morph/client/container/list.go:22]: why u need this renaming?

Comment (End-rey) [reply pkg/morph/client/container/list.go:22]: Oh, I did this in another function first to distinguish it from another variable below. Should I rename it back?

Comment (cthulhu-rider) [reply pkg/morph/client/container/list.go:22]: let it be just to not rerun actions

**Review by cthulhu-rider — APPROVED** [review]
