### PR TITLE
Unify cli flags

### LINKED ISSUE #623: cli: Do not print help on any failure
Any error returned by implemented command executor leads to additional help output. It is useful when the user incorrectly formed a command, but not more.

### Solution
Replace providing the `RunE` calls of to `cobra.Command` (errors of which are actually lead to `help`) with `Run`. With this approach command misprints are still handled, but other errors are written user friendly.
For errors `cmd.PrintErr` function group, for logs - `cmd.Print*` w/o `Err`.

### PR DESCRIPTION
**Pull request by fyrchik**
Related #1574.
Related #623.

### CODE REVIEW

File: cmd/neofs-cli/modules/bearer/create.go [hunk 1]
```diff
@@ -35,14 +34,14 @@ All epoch flags can be specified relative to the current epoch with the +n synta
...
-	RunE: createToken,
+	Run: createToken,
 }
 
 func init() {
 	createCmd.Flags().StringP(eaclFlag, "e", "", "path to the extended ACL table")
 	createCmd.Flags().StringP(issuedAtFlag, "i", "", "epoch to issue token at")
 	createCmd.Flags().StringP(notValidBeforeFlag, "n", "", "not valid before epoch")
-	createCmd.Flags().StringP(expireAtFlag, "x", "", "expiration epoch")
+	createCmd.Flags().StringP(commonflags.ExpireAt, "x", "", "expiration epoch")
```
Comment (carpawell) [inline cmd/neofs-cli/modules/bearer/create.go:44]: somewhere shorthand is `x` and somewhere is `e`, lets's also sync it

File: cmd/neofs-cli/modules/bearer/create.go [hunk 2]
```diff
@@ -52,33 +51,29 @@ func init() {
...
-	if err != nil {
-		return err
-	}
-	exp, expRelative, err := common.ParseEpoch(cmd, expireAtFlag)
-	if err != nil {
-		return err
-	}
+	common.ExitOnErr(cmd, "can't parse --"+issuedAtFlag+" flag: %w", err)
+
+	exp, expRelative, err := common.ParseEpoch(cmd, commonflags.ExpireAt)
```
Comment (carpawell) [inline cmd/neofs-cli/modules/bearer/create.go:63]: does it still support a relative expiration on the `expire-at` flag?

Comment (fyrchik) [reply cmd/neofs-cli/modules/bearer/create.go:63]: Yes, i think bearer command better stay the way it is, because it has 3 similar flags. Having 6 flags can be too hard for a user.

File: cmd/neofs-cli/modules/bearer/create.go (hunk 1 above)
Comment (fyrchik) [reply cmd/neofs-cli/modules/bearer/create.go:44]: It is left so deliberatly, `e` is for `eacl` here, I think equal long names is enough.

**Comment by fyrchik** [comment]
Let's just leave 623 open.

**Review by carpawell — APPROVED** [review]
