### PR TITLE
Fix/Do not handle object concurrently by the policer

### LINKED ISSUE #1411: replication:Uunexpectedly many requests for the same object per clock
Need to be explored. Eyes caught on a large number of messages:
```
2022-05-20T10:53:30.044Z	error	policer/check.go:114	receive object header to check policy compliance	{"component": "Object Policer", "object": "HTP3MZLWsq5uzrZfh1BwGhQoC6NZW8EG12rCChoueKVN/EH3MwCPXGBpLFMR3nYzXMAqcjLTGa4FR9izcftdnuRAq", "error": "(*headsvc.RemoteHeader) could not head object in [/dns4/s03.neofs.devenv/tcp/8080]: read object header from NeoFS: write request: rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
2022-05-20T10:53:30.053Z	error	policer/check.go:114	receive object header to check policy compliance	{"component": "Object Policer", "object": "HTP3MZLWsq5uzrZfh1BwGhQoC6NZW8EG12rCChoueKVN/EH3MwCPXGBpLFMR3nYzXMAqcjLTGa4FR9izcftdnuRAq", "error": "(*headsvc.RemoteHeader) could not head object in [/dns4/s01.neofs.devenv/tcp/8080]: read object header from NeoFS: unexpected header type <nil>"}
2022-05-20T10:53:30.094Z	error	policer/check.go:114	receive object header to check policy compliance	{"component": "Object Policer", "object": "HTP3MZLWsq5uzrZfh1BwGhQoC6NZW8EG12rCChoueKVN/EH3MwCPXGBpLFMR3nYzXMAqcjLTGa4FR9izcftdnuRAq", "error": "(*headsvc.RemoteHeader) could not head object in [/dns4/s04.neofs.devenv/tcp/8082/tls /dns4/s04.neofs.devenv/tcp/8080]: read object header from NeoFS: unexpected header type <nil>"}
2022-05-20T10:53:31.044Z	error	policer/check.go:114	receive object header to check policy compliance	{"component": "Object Policer", "object": "HTP3MZLWsq5uzrZfh1BwGhQoC6NZW8EG12rCChoueKVN/EH3MwCPXGBpLFMR3nYzXMAqcjLTGa4FR9izcftdnuRAq", "error": "(*headsvc.RemoteHeader) could not head object in [/dns4/s03.neofs.devenv/tcp/8080]: read object header from NeoFS: write request: rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
2022-05-20T10:53:31.053Z	error	policer/check.go:114	receive object header to check policy compliance	{"component": "Object Policer", "object": "HTP3MZLWsq5uzrZfh1BwGhQoC6NZW8EG12rCChoueKVN/EH3MwCPXGBpLFMR3nYzXMAqcjLTGa4FR9izcftdnuRAq", "error": "(*headsvc.RemoteHeader) could not head object in [/dns4/s01.neofs.devenv/tcp/8080]: read object header from NeoFS: unexpected header type <nil>"}
2022-05-20T10:53:31.059Z	error	policer/check.go:114	receive object header to check policy compliance	{"component": "Object Policer", "object": "HTP3MZLWsq5uzrZfh1BwGhQoC6NZW8EG12rCChoueKVN/EH3MwCPXGBpLFMR3nYzXMAqcjLTGa4FR9izcftdnuRAq", "error": "(*headsvc.RemoteHeader) could not head object in [/dns4/s04.neofs.devenv/tcp/8082/tls /dns4/s04.neofs.devenv/tcp/8080]: read object header from NeoFS: unexpected header type <nil>"}
2022-05-20T10:53:32.045Z	error	policer/check.go:114	receive object header to check policy compliance	{"component": "Object Policer", "object": "HTP3MZLWsq5uzrZfh1BwGhQoC6NZW8EG12rCChoueKVN/EH3MwCPXGBpLFMR3nYzXMAqcjLTGa4FR9izcftdnuRAq", "error": "(*headsvc.RemoteHeader) could not head object in [/dns4/s03.neofs.devenv/tcp/8080]: read object header from NeoFS: write request: rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
2022-05-20T10:53:32.053Z	error	policer/check.go:114	receive object header to check policy compliance	{"component": "Object Policer", "object": "HTP3MZLWsq5uzrZfh1BwGhQoC6NZW8EG12rCChoueKVN/EH3MwCPXGBpLFMR3nYzXMAqcjLTGa4FR9izcftdnuRAq", "error": "(*headsvc.RemoteHeader) could not head object in [/dns4/s01.neofs.devenv/tcp/8080]: read object header from NeoFS: unexpected header type <nil>"}
2022-05-20T10:53:32.058Z	error	policer/check.go:114	receive object header to check policy compliance	{"component": "Object Policer", "object": "HTP3MZLWsq5uzrZfh1BwGhQoC6NZW8EG12rCChoueKVN/EH3MwCPXGBpLFMR3nYzXMAqcjLTGa4FR9izcftdnuRAq", "error": "(*headsvc.RemoteHeader) could not head object in [/dns4/s04.neofs.devenv/tcp/8082/tls /dns4/s04.neofs.devenv/tcp/8080]: read object header from NeoFS: unexpected header type <nil>"}
2022-05-20T10:53:33.046Z	error	policer/check.go:114	receive object header to check policy compliance	{"component": "Object Policer", "object": "HTP3MZLWsq5uzrZfh1BwGhQoC6NZW8EG12rCChoueKVN/EH3MwCPXGBpLFMR3nYzXMAqcjLTGa4FR9izcftdnuRAq", "error": "(*headsvc.RemoteHeader) could not head object in [/dns4/s03.neofs.devenv/tcp/8080]: read object header from NeoFS: write request: rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
2022-05-20T10:53:33.054Z	error	policer/check.go:114	receive object header to check policy compliance	{"component": "Object Policer", "object": "HTP3MZLWsq5uzrZfh1BwGhQoC6NZW8EG12rCChoueKVN/EH3MwCPXGBpLFMR3nYzXMAqcjLTGa4FR9izcftdnuRAq", "error": "(*headsvc.RemoteHeader) could not head object in [/dns4/s01.neofs.devenv/tcp/8080]: read object header from NeoFS: unexpected header type <nil>"}
2022-05-20T10:53:33.061Z	error	policer/check.go:114	receive object header to check policy compliance	{"component": "Object Policer", "object": "HTP3MZLWsq5uzrZfh1BwGhQoC6NZW8EG12rCChoueKVN/EH3MwCPXGBpLFMR3nYzXMAqcjLTGa4FR9izcftdnuRAq", "error": "(*headsvc.RemoteHeader) could not head object in [/dns4/s04.neofs.devenv/tcp/8082/tls /dns4/s04.neofs.devenv/tcp/8080]: read object header from NeoFS: unexpected header type <nil>"}
2022-05-20T10:53:34.046Z	error	policer/check.go:114	receive object header to check policy compliance	{"component": "Object Policer", "object": "HTP3MZLWsq5uzrZfh1BwGhQoC6NZW8EG12rCChoueKVN/EH3MwCPXGBpLFMR3nYzXMAqcjLTGa4FR9izcftdnuRAq", "error": "(*headsvc.RemoteHeader) could not head object in [/dns4/s03.neofs.devenv/tcp/8080]: read object header from NeoFS: write request: rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
2022-05-20T10:53:34.053Z	error	policer/check.go:114	receive object header to check policy compliance	{"component": "Object Policer", "object": "HTP3MZLWsq5uzrZfh1BwGhQoC6NZW8EG12rCChoueKVN/EH3MwCPXGBpLFMR3nYzXMAqcjLTGa4FR9izcftdnuRAq", "error": "(*headsvc.RemoteHeader) could not head object in [/dns4/s01.neofs.devenv/tcp/8080]: read object header from NeoFS: unexpected header type <nil>"}
2022-05-20T10:53:34.061Z	error	policer/check.go:114	receive object header to check policy compliance	{"component": "Object Policer", "object": "HTP3MZLWsq5uzrZfh1BwGhQoC6NZW8EG12rCChoueKVN/EH3MwCPXGBpLFMR3nYzXMAqcjLTGa4FR9izcftdnuRAq", "error": "(*headsvc.RemoteHeader) could not head object in [/dns4/s04.neofs.devenv/tcp/8082/tls /dns4/s04.neofs.devenv/tcp/8080]: read object header from NeoFS: unexpected header type <nil>"}
2022-05-20T10:53:35.047Z	error	policer/check.go:114	receive object header to check policy compliance	{"component": "Object Policer", "object": "HTP3MZLWsq5uzrZfh1BwGhQoC6NZW8EG12rCChoueKVN/EH3MwCPXGBpLFMR3nYzXMAqcjLTGa4FR9izcftdnuRAq", "error": "(*headsvc.RemoteHeader) could not head object in [/dns4/s03.neofs.devenv/tcp/8080]: read object header from NeoFS: write request: rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
2022-05-20T10:53:35.055Z	error	policer/check.go:114	receive object header to check policy compliance	{"component": "Object Policer", "object": "HTP3MZLWsq5uzrZfh1BwGhQoC6NZW8EG12rCChoueKVN/EH3MwCPXGBpLFMR3nYzXMAqcjLTGa4FR9izcftdnuRAq", "error": "(*headsvc.RemoteHeader) could not head object in [/dns4/s01.neofs.devenv/tcp/8080]: read object header from NeoFS: unexpected header type <nil>"}
2022-05-20T10:53:35.062Z	error	policer/check.go:114	receive object header to check policy compliance	{"component": "Object Policer", "object": "HTP3MZLWsq5uzrZfh1BwGhQoC6NZW8EG12rCChoueKVN/EH3MwCPXGBpLFMR3nYzXMAqcjLTGa4FR9izcftdnuRAq", "error": "(*headsvc.RemoteHeader) could not head object in [/dns4/s04.neofs.devenv/tcp/8082/tls /dns4/s04.neofs.devenv/tcp/8080]: read object header from NeoFS: unexpected header type <nil>"}
```

Note: don't pay attention to exact errors, that was a debug run.

Reason?:

- policer task selection
- placement
- ???

### PR DESCRIPTION
**Pull request by carpawell**
Put object to the cache before starting handling. That prevents concurrent
object handling when there is a few number of objects and object handling
takes more time that the policer needs for starting that object handling one
more time.

Signed-off-by: Pavel Karpy <carpawell@nspcc.ru>

Closes #1411.

### CODE REVIEW

File: pkg/services/policer/process.go [hunk 1]
```diff
@@ -55,8 +55,8 @@ func (p *Policer) shardPolicyWorker(ctx context.Context) {
 						return
 					}
 
-					p.processObject(ctx, addr)
 					p.cache.Add(addrStr, time.Now())
+					p.processObject(ctx, addr)
```
Comment (fyrchik) [inline pkg/services/policer/process.go:59]: I think it is worth to also put `time.Now()` after this line. Timeout should start after we have finished processing.

**Review by fyrchik — APPROVED** [review]

File: pkg/services/policer/process.go (hunk 1 above)
Comment (fyrchik) [reply pkg/services/policer/process.go:59]: Yes.

File: pkg/services/policer/policer.go [hunk 2]
```diff
@@ -22,12 +23,41 @@ type nodeLoader interface {
...
+	oiw.m.RLock()
+	defer oiw.m.RUnlock()
+
+	_, ok := oiw.objs[addr]
+	return ok
+}
+
+func (oiw objectsInWork) remove(addr oid.Address) {
+	oiw.m.Lock()
+	defer oiw.m.Unlock()
```
Comment (cthulhu-rider) [inline pkg/services/policer/policer.go:41]: `defer` is redundant here, isn't it?

File: pkg/services/policer/process.go (hunk 1 above)
Comment (carpawell) [reply pkg/services/policer/process.go:66]: updated a little: added the map that contains objects that are already being processed (max map size is a max pool size) while LRU cache is gonna store object that has been processed recently (200_000 MiB size). originally suggested by @cthulhu-rider 

what do you think?

File: pkg/services/policer/policer.go [hunk 3]
```diff
@@ -22,12 +23,41 @@ type nodeLoader interface {
 	ObjectServiceLoad() float64
 }
 
+type objectsInWork struct {
+	m    *sync.RWMutex
```
Comment (cthulhu-rider) [inline pkg/services/policer/policer.go:27]: Why did u decide to hold pointer instead of mutex itself? Is there any case when we set pointer to already allocated mutex somewhere else?

File: pkg/services/policer/process.go [hunk 4]
```diff
@@ -48,15 +48,25 @@ func (p *Policer) shardPolicyWorker(ctx context.Context) {
 				return
 			default:
 				addr := addrs[i]
+				if p.objsInWork.inWork(addr) {
+					// do not process an object
+					// that is in work
+					continue
+				}
+
 				addrStr := addr.EncodeToString()
```
Comment (cthulhu-rider) [inline pkg/services/policer/process.go:57]: Not related to the PR theme, but can we avoid encoding and use `oid.Address` as cache keys?

File: pkg/services/policer/policer.go (hunk 2 above)
Comment (carpawell) [reply pkg/services/policer/policer.go:41]: do you mean to move it after accessing the map?

ok, usually prefer to work with mutexes via `defer` (do not know does it add any overhead in compiled code)

File: pkg/services/policer/process.go (hunk 4 above)
Comment (carpawell) [reply pkg/services/policer/process.go]: hm, why not, changed to store the same type in cache and map

File: pkg/services/policer/policer.go (hunk 3 above)
Comment (carpawell) [reply pkg/services/policer/policer.go:27]: > Why did u decide to hold pointer instead of mutex itself?

cause i do not use a pointer to `objectsInWork` in the policer

> Is there any case when we set pointer to already allocated mutex somewhere else?

do you mean in that PR? or somewhere else in the repo?

Comment (cthulhu-rider) [reply pkg/services/policer/policer.go:27]: Then why did u decide to avoid using `objectsInWork` by a pointer?

Comment (carpawell) [reply pkg/services/policer/policer.go]: no real reason. maybe to store struct with pointers and not to have a pointer to pointer (map). changed

do you have any pros to say that one approach is better than another? thanks!

Comment (cthulhu-rider) [reply pkg/services/policer/policer.go]: In terms of source code: we don't need to remember to init pointer.
In terms of performance: I've benchmarked similar case once, it showed very close performance.

I adhere to the approach that if type's method changes value's internal state by design, then this method is called by a pointer.

**Review by cthulhu-rider — APPROVED** [review]

File: pkg/services/policer/process.go (hunk 1 above)
Comment (fyrchik) [reply pkg/services/policer/process.go:65]: To me 2 maps increase memory consumption, can we reuse the same map for this?
Like store `0` if the processing is in progress, before submitting the task and update with the actual value afterwise.

Comment (carpawell) [reply pkg/services/policer/process.go:65]: isn't it useless to prevent concurrent object handling via LRU cache? i mean if it is critical for us not to handle objects twice at a time

in fact, i am a little confused about that issue: we are trying to solve problems that we are not going to face in real use-cases (using a node for storing the only one object)

**Review by fyrchik — APPROVED** [review]

**Comment by fyrchik** [comment]
@carpawell conflicts

**Review by fyrchik — APPROVED** [review]

**Review by cthulhu-rider — APPROVED** [review]

**Comment by carpawell** [comment]
Just rebased.

**Review by cthulhu-rider — APPROVED** [review]
