### PR TITLE
[#2212] morph: Fix subscription restoration

### LINKED ISSUE #2212: Epoch hangs at one node
I have faced problem when one of the node left at 179 epoch while other nodes were at 189:
```
root@az:/etc/neofs/storage/tatlin-object-sber-tfstate/vkarakozov# neofs-cli netmap epoch -r node2:8080 -g
189
root@az:/etc/neofs/storage/tatlin-object-sber-tfstate/vkarakozov# neofs-cli netmap epoch -r node3:8080 -g
189
root@az:/etc/neofs/storage/tatlin-object-sber-tfstate/vkarakozov# neofs-cli netmap epoch -r node4:8080 -g
189
root@az:/etc/neofs/storage/tatlin-object-sber-tfstate/vkarakozov# neofs-cli netmap epoch -r node1:8080 -g
179
```

Please find output from the `netmap snapshot` command:
```
root@az:/etc/neofs/storage/tatlin-object-sber-tfstate/vkarakozov# neofs-cli netmap snapshot -g -r node1:8080
Epoch: 179
Node 1: 02183147e3d30745d3ecf402679d1378bd549f36fc77bf282fc1ffda50a865d8da ONLINE /ip4/172.26.160.150/tcp/8080
        Continent: Europe
        Country: Finland
        CountryCode: FI
        Deployed: YACZROKH
        Location: Helsinki (Helsingfors)
        Node: 172.26.160.150
        Price: 10
        SubDiv: Uusimaa
        SubDivCode: 18
        UN-LOCODE: FI HEL
Node 2: 0309c85a8be8f0a11df58a2ee440a76f37a9fbe4b82b4fd6fcfdb21c95fa8480f7 ONLINE /ip4/172.26.160.46/tcp/8080
        Continent: Europe
        Country: Russia
        CountryCode: RU
        Deployed: YACZROKH
        Location: Saint Petersburg (ex Leningrad)
        Node: 172.26.160.46
        Price: 10
        SubDiv: Sankt-Peterburg
        SubDivCode: SPE
        UN-LOCODE: RU LED
Node 3: 03736791ef911acdbc37625daf91c796e3fff63d5961e4c048368a6033699f4bfc ONLINE /ip4/172.26.160.157/tcp/8080
        Continent: Europe
        Country: Russia
        CountryCode: RU
        Deployed: YACZROKH
        Location: Moskva
        Node: 172.26.160.157
        Price: 10
        SubDiv: Moskva
        SubDivCode: MOW
        UN-LOCODE: RU MOW
Node 4: 03855b0548c4408a4d7725111c55c7346715dea8701a948046eecec7928b10cac0 ONLINE /ip4/172.26.160.205/tcp/8080
        Continent: Europe
        Country: Sweden
        CountryCode: SE
        Deployed: YACZROKH
        Location: Stockholm
        Node: 172.26.160.205
        Price: 10
        SubDiv: Stockholms l�n
        SubDivCode: AB
        UN-LOCODE: SE STO

```

Also tried to issue 'force-new-epoch' command, please find result below:
```
root@az:/etc/neofs/storage/tatlin-object-sber-tfstate/vkarakozov# neofs-cli netmap epoch -r node1:8080 -g
179
root@az:/etc/neofs/storage/tatlin-object-sber-tfstate/vkarakozov# neofs-adm morph force-new-epoch  -c configuration/config.yaml
Current epoch: 187, increase to 188.
Waiting for transactions to persist...
root@az:/etc/neofs/storage/tatlin-object-sber-tfstate/vkarakozov# neofs-cli netmap epoch -r node1:8080 -g
179
root@az:/etc/neofs/storage/tatlin-object-sber-tfstate/vkarakozov# neofs-adm morph force-new-epoch  -c configuration/config.yaml
Current epoch: 188, increase to 189.
root@az:/etc/neofs/storage/tatlin-object-sber-tfstate/vkarakozov# neofs-adm morph force-new-epoch  -c configuration/config.yaml
Current epoch: 188, increase to 189.
Waiting for transactions to persist...
root@az:/etc/neofs/storage/tatlin-object-sber-tfstate/vkarakozov# neofs-cli netmap epoch -r node1:8080 -g
179
```
## Expected Behavior
All nodes have to be at the same epoch.

## Possible Solution
Restart 3 services helped me to reach consistency between nodes epoch:
```
root@az:/etc/neofs/storage/tatlin-object-sber-tfstate/vkarakozov# systemctl restart neofs-ir; systemctl restart neofs-storage; systemctl restart neo-go
root@az:/etc/neofs/storage/tatlin-object-sber-tfstate/vkarakozov# neofs-cli netmap epoch -r node1:8080 -g
190
root@az:/etc/neofs/storage/tatlin-object-sber-tfstate/vkarakozov# neofs-cli netmap epoch -r node2:8080 -g
190
root@az:/etc/neofs/storage/tatlin-object-sber-tfstate/vkarakozov# neofs-cli netmap epoch -r node3:8080 -g
190
root@az:/etc/neofs/storage/tatlin-object-sber-tfstate/vkarakozov# neofs-cli netmap epoch -r node4:8080 -g
190
```

## Steps to Reproduce (for bugs)
Nodes had been used for failover tests  during 3 days where tests are aimed to kill each service and several "healthcheck" commands were issued against service to 100% sure that service has been restarted and ready to process.

[Logs.zip](https://github.com/nspcc-dev/neofs-node/files/10498814/epoch_hangs_full.zip)

## Your Environment

NeoFS Inner Ring node
Version: v0.35.0-11-g1a7c827a-dirty
GoVersion: go1.18.4
NeoFS Storage node
Version: v0.35.0-11-g1a7c827a-dirty
GoVersion: go1.18.4
NeoGo
Version: 0.100.1-pre-1-g0cb86f39
GoVersion: go1.18.4

### PR DESCRIPTION
**Pull request by fyrchik**
Close #2212.
Signed-off-by: Evgenii Stratonikov <e.stratonikov@yadro.com>

### CODE REVIEW

**Review by carpawell — DISMISSED** [review]

**Review by acid-ant — DISMISSED** [review]

**Comment by fyrchik** [comment]
Probably _triggered_ by neo-go update after https://github.com/nspcc-dev/neo-go/pull/2749

File: pkg/morph/client/notifications.go [hunk 1]
```diff
@@ -226,6 +226,7 @@ func (c *Client) restoreSubscriptions(cli *rpcclient.WSClient, endpoint string)
 
 	// notification events restoration
 	for contract := range c.subscribedEvents {
+		contract := contract
 		id, err = cli.SubscribeForExecutionNotifications(&contract, nil)
```
Comment (roman-khimov) [inline pkg/morph/client/notifications.go:230]: Maybe this would be better handled in WSClient itself.

File: pkg/morph/client/notifications.go [hunk 2]
```diff
@@ -226,6 +226,7 @@ func (c *Client) restoreSubscriptions(cli *rpcclient.WSClient, endpoint string)
 
 	// notification events restoration
 	for contract := range c.subscribedEvents {
+		contract := contract
```
Comment (roman-khimov) [inline pkg/morph/client/notifications.go:229]: Suppose you're seeing this line a year from now, what are your immediate thoughts?

**Comment by roman-khimov** [comment]
> Probably _triggered_ by neo-go update after [nspcc-dev/neo-go#2749](https://github.com/nspcc-dev/neo-go/pull/2749)

More likely the new Receive* APIs.

File: pkg/morph/client/notifications.go (hunk 1 above)
Comment (roman-khimov) [reply pkg/morph/client/notifications.go:230]: nspcc-dev/neo-go#2890

File: pkg/morph/client/notifications.go (hunk 2 above)
Comment (fyrchik) [reply pkg/morph/client/notifications.go:229]: My thoughts would be "`SubscribeForExecutionNotifications` does something asynchronously": I think this is a pretty common pattern, we even use the same name here to stress that we need a copy.

File: pkg/morph/client/notifications.go (hunk 1 above)
Comment (fyrchik) [reply pkg/morph/client/notifications.go:230]: Agree, but I still believe it is a bug: `SubscribeForExecutionNotifications` gives no guarantees (at least they are not obvious) and it is an external library which is harder to audit during our code reviews.
Right now it is also faster to just fix it here.

Do you think it is a bug in `WSClient` and we need to create an issue for neo-go?

File: pkg/morph/client/notifications.go (hunk 2 above)
Comment (fyrchik) [reply pkg/morph/client/notifications.go:229]: @carpawell @acid-ant does such assignment ring any bells in you?

Comment (fyrchik) [reply pkg/morph/client/notifications.go]: Added a link on neo-go issue.

Comment (carpawell) [reply pkg/morph/client/notifications.go]: i would understand the reason for that line ("this is a pretty common pattern" like u said) but i am always "for" any comments that describe some _really_ unexpected bugs (well, that was not bug before `neo-go` update (and i did not expect any pointer storing when wrote that code) but it is now)

**Review by carpawell — APPROVED** [review]

File: pkg/morph/client/notifications.go (hunk 1 above)
Comment (roman-khimov) [reply pkg/morph/client/notifications.go:230]: Already there. I agree that pointer-level guarantees are very vague in Go and of course this should be fixed in the node right away, without waiting for NeoGo fix. But it's too easy to make a mistake like this, so WSClient should be fixed (we're very likely to see similar issues with other subscribers otherwise).

**Review by roman-khimov — APPROVED** [review]

**Review by acid-ant — APPROVED** [review]
