### PR TITLE
engine: Be ready to delete objects on unexpected shards

### LINKED ISSUE #2821: Endless deletion of the same object
## Expected Behavior
Policer deletes an object. It's gone. Nothing else happens with it unless we get a new copy for some reason.

## Current Behavior
Logs grepped for 2wTgi9vrFu3yFjKe5r5hKBVfEvx3KaYD4AX5LLvMqonb:
```
Apr 21 20:06:38 titan4 neofs-node[429824]: 2024-04-21T20:06:38.730Z        info        policer/check.go:175        local replica of the object is redundant in the container, removing...        {"component": "Object Policer", "object": "cWaXnFSPr5teUdtUu8MFwsm2LJ3W7NanzBpWWmCCmeF/2wTgi9vrFu3yFjKe5r5hKBVfEvx3KaYD4AX5LLvMqonb"}
Apr 21 20:07:06 titan4 neofs-node[429824]: 2024-04-21T20:07:06.586Z        info        log/log.go:12        local object storage operation        {"shard_id": "KBFkQrEzquYQnu2uT7sL84", "address": "cWaXnFSPr5teUdtUu8MFwsm2LJ3W7NanzBpWWmCCmeF/2wTgi9vrFu3yFjKe5r5hKBVfEvx3KaYD4AX5LLvMqonb", "op": "metabase DELETE"}
Apr 21 20:20:30 titan4 neofs-node[429824]: 2024-04-21T20:20:30.377Z        info        policer/check.go:175        local replica of the object is redundant in the container, removing...        {"component": "Object Policer", "object": "cWaXnFSPr5teUdtUu8MFwsm2LJ3W7NanzBpWWmCCmeF/2wTgi9vrFu3yFjKe5r5hKBVfEvx3KaYD4AX5LLvMqonb"}
Apr 21 20:21:06 titan4 neofs-node[429824]: 2024-04-21T20:21:06.843Z        info        log/log.go:12        local object storage operation        {"shard_id": "KBFkQrEzquYQnu2uT7sL84", "address": "cWaXnFSPr5teUdtUu8MFwsm2LJ3W7NanzBpWWmCCmeF/2wTgi9vrFu3yFjKe5r5hKBVfEvx3KaYD4AX5LLvMqonb", "op": "metabase DELETE"}
Apr 21 20:34:22 titan4 neofs-node[429824]: 2024-04-21T20:34:22.064Z        info        policer/check.go:175        local replica of the object is redundant in the container, removing...        {"component": "Object Policer", "object": "cWaXnFSPr5teUdtUu8MFwsm2LJ3W7NanzBpWWmCCmeF/2wTgi9vrFu3yFjKe5r5hKBVfEvx3KaYD4AX5LLvMqonb"}
Apr 21 20:35:07 titan4 neofs-node[429824]: 2024-04-21T20:35:07.045Z        info        log/log.go:12        local object storage operation        {"shard_id": "KBFkQrEzquYQnu2uT7sL84", "address": "cWaXnFSPr5teUdtUu8MFwsm2LJ3W7NanzBpWWmCCmeF/2wTgi9vrFu3yFjKe5r5hKBVfEvx3KaYD4AX5LLvMqonb", "op": "metabase DELETE"}
Apr 21 20:48:13 titan4 neofs-node[429824]: 2024-04-21T20:48:13.786Z        info        policer/check.go:175        local replica of the object is redundant in the container, removing...        {"component": "Object Policer", "object": "cWaXnFSPr5teUdtUu8MFwsm2LJ3W7NanzBpWWmCCmeF/2wTgi9vrFu3yFjKe5r5hKBVfEvx3KaYD4AX5LLvMqonb"}
Apr 21 20:49:07 titan4 neofs-node[429824]: 2024-04-21T20:49:07.256Z        info        log/log.go:12        local object storage operation        {"shard_id": "KBFkQrEzquYQnu2uT7sL84", "address": "cWaXnFSPr5teUdtUu8MFwsm2LJ3W7NanzBpWWmCCmeF/2wTgi9vrFu3yFjKe5r5hKBVfEvx3KaYD4AX5LLvMqonb", "op": "metabase DELETE"}
Apr 21 21:02:05 titan4 neofs-node[429824]: 2024-04-21T21:02:05.502Z        info        policer/check.go:175        local replica of the object is redundant in the container, removing...        {"component": "Object Policer", "object": "cWaXnFSPr5teUdtUu8MFwsm2LJ3W7NanzBpWWmCCmeF/2wTgi9vrFu3yFjKe5r5hKBVfEvx3KaYD4AX5LLvMqonb"}
Apr 21 21:02:07 titan4 neofs-node[429824]: 2024-04-21T21:02:07.417Z        info        log/log.go:12        local object storage operation        {"shard_id": "KBFkQrEzquYQnu2uT7sL84", "address": "cWaXnFSPr5teUdtUu8MFwsm2LJ3W7NanzBpWWmCCmeF/2wTgi9vrFu3yFjKe5r5hKBVfEvx3KaYD4AX5LLvMqonb", "op": "metabase DELETE"}
```
Notice no PUTs at all, but the object still comes again and again on every policer iteration.

## Context
Testnet.

## Your Environment
* Version used: 0.41.0

### PR DESCRIPTION
**Pull request by carpawell**
It is possible to store an object on a shard that is not the first one after object address hash sorting and not-found-object-inhuming is also errorless, so the actual shard does not delete objects in such cases. Closes #2821.

### CODE REVIEW

File: pkg/local_object_storage/engine/inhume.go [hunk 1]
```diff
@@ -227,6 +234,23 @@ func (e *StorageEngine) inhumeAddr(addr oid.Address, prm shard.InhumePrm) (bool,
 
 	prm.SetTargets(append(children, addr)...)
 
+	if shardWithObject != "" {
+		sh := e.getShard(shardWithObject)
+
+		_, err := sh.Inhume(prm)
+		if err != nil {
```
Comment (roman-khimov) [inline pkg/local_object_storage/engine/inhume.go:241]: How come error handling differs from the one below here?

File: pkg/local_object_storage/engine/inhume.go [hunk 2]
```diff
@@ -227,6 +234,23 @@ func (e *StorageEngine) inhumeAddr(addr oid.Address, prm shard.InhumePrm) (bool,
...
+				e.reportShardError(hashedShard(sh), "could not inhume object in shard", err)
+			}
+
+			return false, err
+		}
+
+		return true, nil
+	}
+
+	// has not found the object on any shard, so mark it as inhumed on the most probable one
```
Comment (roman-khimov) [inline pkg/local_object_storage/engine/inhume.go:252]: How can it happen?

File: pkg/local_object_storage/engine/inhume.go [hunk 3]
```diff
@@ -227,6 +234,23 @@ func (e *StorageEngine) inhumeAddr(addr oid.Address, prm shard.InhumePrm) (bool,
...
+		_, err := sh.Inhume(prm)
+		if err != nil {
+			if !errors.Is(err, logicerr.Error) {
+				e.reportShardError(hashedShard(sh), "could not inhume object in shard", err)
+			}
+
+			return false, err
+		}
+
+		return true, nil
```
Comment (roman-khimov) [inline pkg/local_object_storage/engine/inhume.go:249]: How about root/children?

File: pkg/local_object_storage/engine/inhume.go [hunk 4]
```diff
@@ -227,6 +234,23 @@ func (e *StorageEngine) inhumeAddr(addr oid.Address, prm shard.InhumePrm) (bool,
...
+	}
+
+	// has not found the object on any shard, so mark it as inhumed on the most probable one
+
 	e.iterateOverSortedShards(addr, func(_ int, sh hashedShard) (stop bool) {
```
Comment (roman-khimov) [inline pkg/local_object_storage/engine/inhume.go:254]: Maybe it's easier to iterate over all shards here?

File: CHANGELOG.md [hunk 5]
```diff
@@ -11,6 +11,7 @@ Changelog for NeoFS Node
 - Container size estimation contract writing (#2819)
 - Custom contract deployment with custom zone via neofs-adm (#2827)
 - Errors in neofs-adm morph dump-names output (#2831)
+- Endless GC cycle if an object is stored on an unexpected shard (#2821)
```
Comment (roman-khimov) [inline CHANGELOG.md:14]: How can it be stored there? Especially if metabase was resynchronized?

Comment (carpawell) [reply CHANGELOG.md:14]: > How can it be stored there?

i don't know, shard list may change, disk may answer with error. so many cases may lead to the attempt to write an object to another shard. current code does not think that is bad, it just tries the next one

> Especially if metabase was resynchronized?'

what does it change? there is always a shard that is the most "good" for an object, if it stores it, the object is never moved. is _that shard's_ peapod stores info about, it will always refill the same (this shard's one) metabase, even if this shard is not "the best one" for this object

File: pkg/local_object_storage/engine/inhume.go (hunk 4 above)
Comment (carpawell) [reply pkg/local_object_storage/engine/inhume.go:254]: maybe, but since we know the exact one, why not?

File: pkg/local_object_storage/engine/inhume.go (hunk 3 above)
Comment (carpawell) [reply pkg/local_object_storage/engine/inhume.go:249]: root and children cases do not fill shard ID cause they do not have a shard, every shard can have info about them, this is handled below

File: pkg/local_object_storage/engine/inhume.go (hunk 2 above)
Comment (carpawell) [reply pkg/local_object_storage/engine/inhume.go:252]: tombstones to the objects that are not here (and never were)? the control service that said to mark this obj as garbage (even if you do not have it yet)?

File: pkg/local_object_storage/engine/inhume.go (hunk 1 above)
Comment (carpawell) [reply pkg/local_object_storage/engine/inhume.go:241]: here we know what exact shard has an object, no need to return `stop`, `retErr`, just `return`

if you are about why we need to compare error with smth and return that error in the code below -- i don't know, all of the cases below are logical errors anyway

Comment (roman-khimov) [reply pkg/local_object_storage/engine/inhume.go:241]: Yeah, I'm mostly about ErrLockObjectRemoval and ErrReadOnlyMode/ErrDegradedMode.

**Review by roman-khimov — APPROVED** [review]
Needs to be rebased.

File: pkg/local_object_storage/engine/inhume.go (hunk 1 above)
Comment (carpawell) [reply pkg/local_object_storage/engine/inhume.go:241]: iteration over shards can be stopped if some logical errors appear (lock(ed) object removal, degraded mode, etc), so that is why we look at some kinds of errors. if we have exact one shard, we can return `err` directly

(but this meta -> shard -> meta conversion scares me too: 
```
			case errors.Is(err, shard.ErrLockObjectRemoval):
				retErr = meta.ErrLockObjectRemoval
				return true
```
, but that is not used, and `errors.Is` will work the same)

File: pkg/local_object_storage/engine/inhume.go (hunk 4 above)
Comment (carpawell) [reply pkg/local_object_storage/engine/inhume.go:254]: tbh, still not sure about this thread. b, that is really better: less code but more work
