### PR TITLE
fix/Do not vote for the same validators list twice

### LINKED ISSUE #2365: Do not vote for the same node on IR start
## Expected Behavior
Voting should be done when it can change something.

## Current Behavior
IR node will vote for whatever key is written into its config unconditionally.

## Possible Solution
Check NEO state before voting, likely there is already a vote and likely it's for the same key.

## Steps to Reproduce (for bugs)
Restart IR node.

## Context
Related to #2363.

### PR DESCRIPTION
**Pull request by carpawell**
Closes #2365.

### CODE REVIEW

**Comment by carpawell** [comment]
@AnnaShaleva, @roman-khimov, ping me if you think that we need to make it more accurate with `GetNextBlockValidators` or even with `GetAccountState` (and check whether an alphabet contract has voted for the required validator).

File: pkg/innerring/state.go [hunk 1]
```diff
@@ -138,6 +147,28 @@ func (s *Server) voteForSidechainValidator(prm governance.VoteValidatorPrm) erro
 	return nil
 }
 
+func (s *Server) alreadyVoted(validatorsToVote keys.PublicKeys) (bool, error) {
+	// almost every part of NeoFS treats committee as validators list
+	validators, err := s.morphClient.Committee()
```
Comment (AnnaShaleva) [inline pkg/innerring/state.go:152]: Are you sure that it's safe to treat commettee as validators here? If these lists differ, then you may end up in a situation when you have to vote for some validator, but `alreadyVoted` method can return true for him (e.g. because he's a committee member, but not the validator yet).

Comment (roman-khimov) [reply pkg/innerring/state.go:152]: `len(committee) == len(validators)` is a wrong assumption which can be fixed easily. And you _must_ do `GetAccountState()`, you're just checking for a different thing otherwise.

Frankly, I was expecting a simple `GetAccountState()` (ok, a number of them) and comparison with the configured set. Then you don't even need to care about committee/validators list. You only need to care about votes here.

File: pkg/morph/client/client.go [hunk 2]
```diff
@@ -419,6 +420,30 @@ func (c *Client) IsValidScript(script []byte, signers []transaction.Signer) (res
...
+// tokens for. Nil key with no error it returned if the account has no NEO.
+func (c *Client) VotesFor(addr util.Uint160) (*keys.PublicKey, error) {
+	c.switchLock.RLock()
+	defer c.switchLock.RUnlock()
+
+	if c.inactive {
+		return nil, ErrConnectionLost
+	}
+
+	neoReader := neo.New(c.rpcActor)
```
Comment (roman-khimov) [inline pkg/morph/client/client.go:433]: Can have `nil` signers, doesn't really matter here (but a little less things to encode/decode for the request).

File: pkg/morph/client/client.go [hunk 3]
```diff
@@ -419,6 +420,30 @@ func (c *Client) IsValidScript(script []byte, signers []transaction.Signer) (res
 	return result.State == vmstate.Halt.String(), nil
 }
 
+// VotesFor returns a key the provided account has voted with its NEO
+// tokens for. Nil key with no error it returned if the account has no NEO.
+func (c *Client) VotesFor(addr util.Uint160) (*keys.PublicKey, error) {
```
Comment (roman-khimov) [inline pkg/morph/client/client.go:425]: `Votes` sound plural here, while we only have a single vote for a single account. Maybe `AccountVote`.

**Review by roman-khimov — APPROVED** [review]

File: pkg/morph/client/client.go (hunk 3 above)
Comment (carpawell) [reply pkg/morph/client/client.go:425]: a meant "`addr` votes for". was it hard to understand?

File: pkg/morph/client/client.go (hunk 2 above)
Comment (carpawell) [reply pkg/morph/client/client.go:433]: you meant `New` -> `NewReader`? fixed

Comment (roman-khimov) [reply pkg/morph/client/client.go]: Yeah, `NewReader` is faster and again, you can omit `c.rpcActor`.

File: pkg/morph/client/client.go (hunk 3 above)
Comment (roman-khimov) [reply pkg/morph/client/client.go:425]: I see what was meant, but it doesn't sound right anyway. It's not `addr.VotesFor()` also, it's `client.VotesFor`, but client doesn't vote. In general functions are verbs, so some `GetAccountVote()` is more appropriate. At the same time we often omit `get` for data accesses.

Comment (carpawell) [reply pkg/morph/client/client.go]: ok, `AccountVote`

File: pkg/morph/client/client.go (hunk 2 above)
Comment (carpawell) [reply pkg/morph/client/client.go]: oh, you meant `neoReader := neo.NewReader(invoker.New(c.client, nil))`?

Comment (carpawell) [reply pkg/morph/client/client.go]: the last push already has the `invoker` version. dont mind keeping it like that

File: pkg/morph/client/client.go [hunk 4]
```diff
@@ -419,6 +421,30 @@ func (c *Client) IsValidScript(script []byte, signers []transaction.Signer) (res
 	return result.State == vmstate.Halt.String(), nil
 }
 
+// AccountVote returns a key the provided account has voted with its NEO
+// tokens for. Nil key with no error is returned if the account has no NEO.
```
Comment (AnnaShaleva) [inline pkg/morph/client/client.go:425]: `Nil key with no error is returned if the account has no NEO` or when account has some NEO and didn't voted for anyone.

**Review by AnnaShaleva — APPROVED** [review]
