### PR TITLE
Fix/Do not use morph client in `neofs-adm`

### LINKED ISSUE #1378: WS morph client in CLIs
After #1170 morph client [uses](https://github.com/nspcc-dev/neofs-node/blob/d99800ee93bbe9b0699313ba7a5ecab85699731c/pkg/morph/client/client.go#L46) WebSocket neo-go client (and only it, it could not accept HTTP endpoints at all). Some CLI commands continued accepting HTTP addresses since they [use](https://github.com/nspcc-dev/neofs-node/blob/d99800ee93bbe9b0699313ba7a5ecab85699731c/cmd/neofs-adm/internal/modules/morph/n3client.go#L22) raw neo-go client and some CLI commands started requiring WebSocket addresses.

So, at least:
1. Sync their behavior (or discuss why is that ok to accept different endpoints);
2. Check that written documentation/usage help is actual.

### PR DESCRIPTION
**Pull request by carpawell**
Closes #1378.

### CODE REVIEW

File: cmd/neofs-adm/internal/modules/morph/local_client.go [hunk 1]
```diff
@@ -151,6 +153,36 @@ func (l *localClient) CreateTxFromScript(script []byte, acc *wallet.Account, sys
 	return tx, nil
 }
 
+func (l *localClient) GetCommittee() (keys.PublicKeys, error) {
+	//TODO implement me
```
Comment (fyrchik) [inline cmd/neofs-adm/internal/modules/morph/local_client.go:157]: We can remove this TODO and replace it with something like `not used by morph init`, because it is the only place where local client is intended to be used.

File: cmd/neofs-adm/internal/modules/morph/n3client.go [hunk 2]
```diff
@@ -31,6 +35,12 @@ type Client interface {
 	NEP17BalanceOf(util.Uint160, util.Uint160) (int64, error)
 	InvokeScript([]byte, []transaction.Signer) (*result.Invoke, error)
 	SendRawTransaction(*transaction.Transaction) (util.Uint256, error)
+	GetCommittee() (keys.PublicKeys, error)
+	InvokeFunction(util.Uint160, string, []smartcontract.Parameter, []transaction.Signer) (*result.Invoke, error)
```
Comment (fyrchik) [inline cmd/neofs-adm/internal/modules/morph/n3client.go:39]: We have `invokeFunction` helper.

File: cmd/neofs-adm/internal/modules/morph/local_client.go [hunk 3]
```diff
@@ -151,6 +153,36 @@ func (l *localClient) CreateTxFromScript(script []byte, acc *wallet.Account, sys
...
+	panic("implement me")
+}
+
+func (l *localClient) CalculateNotaryFee(u uint8) (int64, error) {
+	//TODO implement me
+	panic("implement me")
+}
+
+func (l *localClient) AddNetworkFee(t *transaction.Transaction, i int64, account ...*wallet.Account) error {
```
Comment (fyrchik) [inline cmd/neofs-adm/internal/modules/morph/local_client.go:171]: We have `addNetworkFee`, can make it public.

File: cmd/neofs-adm/internal/modules/morph/subnet.go [hunk 4]
```diff
@@ -910,3 +802,405 @@ func init() {
...
+		result.Type = smartcontract.ByteArrayType
+		result.Value = v.BytesBE()
+	case noderoles.Role:
+		result.Type = smartcontract.IntegerType
+		result.Value = big.NewInt(int64(v))
+	case keys.PublicKeys:
+		arr := make([][]byte, 0, len(v))
+		for i := range v {
+			arr = append(arr, v[i].Bytes())
+		}
```
Comment (fyrchik) [inline cmd/neofs-adm/internal/modules/morph/subnet.go:1176]: All of this is not needed if you use `invokeFunction`, which accepts `[]interface{}`.

File: cmd/neofs-adm/internal/modules/morph/subnet.go [hunk 5]
```diff
@@ -910,3 +802,405 @@ func init() {
...
+			Script: multisigScript,
+		},
+	}
+
+	bc, err := c.GetBlockCount()
+	if err != nil {
+		return fmt.Errorf("blockchain height: %w", err)
+	}
+
+	signersNumber := uint8(len(alphabet)*2/3 + 1 + 1) // alphabet multisig + key signature
```
Comment (fyrchik) [inline cmd/neofs-adm/internal/modules/morph/subnet.go:984]: `smartcontract.GetDefaultHonestNodeCount(len(alphabet))`?

File: cmd/neofs-adm/internal/modules/morph/subnet.go [hunk 6]
```diff
@@ -910,3 +802,405 @@ func init() {
...
+
+	mainTx := &transaction.Transaction{
+		Nonce:           rand.Uint32(),
+		SystemFee:       test.GasConsumed,
+		ValidUntilBlock: bc + 100,
```
Comment (fyrchik) [inline cmd/neofs-adm/internal/modules/morph/subnet.go:989]: magic constant

File: cmd/neofs-adm/internal/modules/morph/subnet.go [hunk 7]
```diff
@@ -910,3 +802,405 @@ func init() {
...
+
+	// caller's account
+	aa = append(aa, acc)
+
+	// last one is a placeholder for notary contract account
+	aa = append(aa, &wallet.Account{
+		Contract: &wallet.Contract{},
+	})
+
+	return aa
```
Comment (fyrchik) [inline cmd/neofs-adm/internal/modules/morph/subnet.go:1076]: Why not make it a `return []*wallet.Account{...}`, would be more readable IMO.

File: cmd/neofs-adm/internal/modules/morph/local_client.go (hunk 1 above)
Comment (carpawell) [reply cmd/neofs-adm/internal/modules/morph/local_client.go:157]: yeah, that was added autimatically by my IDE, wanted to see your suggestions and fix that. changed the comment, panic is kept

File: cmd/neofs-adm/internal/modules/morph/n3client.go (hunk 2 above)
Comment (carpawell) [reply cmd/neofs-adm/internal/modules/morph/n3client.go:39]: deleted, reused `invokeFunction`

File: cmd/neofs-adm/internal/modules/morph/subnet.go (hunk 6 above)
Comment (carpawell) [reply cmd/neofs-adm/internal/modules/morph/subnet.go:989]: added const

File: cmd/neofs-adm/internal/modules/morph/subnet.go (hunk 7 above)
Comment (carpawell) [reply cmd/neofs-adm/internal/modules/morph/subnet.go:1076]: agree, the only one reason i did so: comments readability

changed

**Review by fyrchik — APPROVED** [review]

**Review by cthulhu-rider — APPROVED** [review]
