### PR TITLE
Fix/fstree compressed objects buffered reading

### LINKED ISSUE #3936: Object GET interrupt
## Expected Behavior
Uninterrupted object download.

## Current Behavior
```
(00:46:46)[sergio@mona:~]% wget https://nspcc.io             
--2026-04-11 00:46:50--  https://nspcc.io/
Resolving nspcc.io (nspcc.io)... 164.92.154.194
Connecting to nspcc.io (nspcc.io)|164.92.154.194|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 51647 (50K) [text/html]
Saving to: ‘index.html’

index.html                              77%[=========================================================>                 ]  39.33K  --.-KB/s    in 0s      

2026-04-11 00:46:50 (129 MB/s) - Connection closed at byte 40278. Retrying.

--2026-04-11 00:46:51--  (try: 2)  https://nspcc.io/
Connecting to nspcc.io (nspcc.io)|164.92.154.194|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 51647 (50K), 11369 (11K) remaining [text/html]
Saving to: ‘index.html’

index.html                             100%[++++++++++++++++++++++++++++++++++++++++++++++++++++++++++================>]  50.44K  --.-KB/s    in 0s      

2026-04-11 00:46:51 (118 MB/s) - ‘index.html’ saved [51647/51647]
```

## Possible Solution
Fix something. Can be a gateway problem as well, but not likely.

## Context
Mainnet.

## Regression
Seems so, 0.51.1 was fine.

## Your Environment
* Version used: 0.52.0
* Server setup and configuration: mainnet
* Operating System and version (`uname -a`): Debian stable

### PR DESCRIPTION
**Pull request by carpawell**
Previously, if a compressed object fits pre-read buffer fully, but its uncompressed form overflows it, a broken object with lost payload was returned.
Closes #3936.

### CODE REVIEW

File: pkg/local_object_storage/blobstor/fstree/util.go [hunk 1]
```diff
@@ -4,6 +4,10 @@ import (
 	"io"
 )
 
+type readerCloser struct {
```
Comment (roman-khimov) [inline pkg/local_object_storage/blobstor/fstree/util.go:7]: Can be reused in `GetRangeStream`

File: pkg/local_object_storage/blobstor/fstree/getstream_test.go [hunk 2]
```diff
@@ -86,6 +86,24 @@ func TestGetStream(t *testing.T) {
 				testStream(t, size)
 			})
 		}
+
+		t.Run("uncopressed object overflows buffer", func(t *testing.T) {
```
Comment (roman-khimov) [inline pkg/local_object_storage/blobstor/fstree/getstream_test.go]: uncompressed

File: pkg/local_object_storage/blobstor/fstree/head.go [hunk 3]
```diff
@@ -85,7 +85,18 @@ func (t *FSTree) ReadObject(addr oid.Address, buf []byte) (int, io.ReadCloser, e
...
 	}
 
-	return copy(buf, initial), stream, nil
+	n := copy(buf, initial)
+	if len(initial) > n {
+		// data was pre-read according to the provided buffer, but its
+		// uncompressed form does not fit the buffer, reslice it, and do not
+		// lose any payload
+		return n, readerCloser{
+			io.MultiReader(bytes.NewReader(initial[n:]), stream),
```
Comment (roman-khimov) [inline pkg/local_object_storage/blobstor/fstree/head.go]: This reference to `initial` worries me somewhat, it seems to be fine now (new buffer for uncompressed data), but can be more problematic in future.

File: CHANGELOG.md [hunk 4]
```diff
@@ -13,6 +13,7 @@ Changelog for NeoFS Node
 - SearchV2 method returning zero result instead of "bad request" error for incorrect numeric filters (#3934)
 - Garbage double-counting in metrics (#3933)
 - Panic in session token storage epoch parsing (#3941)
+- Compressed object GET in some cases (#3936)
```
Comment (roman-khimov) [inline CHANGELOG.md]: ... failure in some cases

File: pkg/local_object_storage/blobstor/fstree/head.go (hunk 3 above)
Comment (carpawell) [reply pkg/local_object_storage/blobstor/fstree/head.go]: what bothers you? this branch is only executed when we have more data than we have space for

**Review by roman-khimov — APPROVED** [review]
