### PR TITLE
[SUPPORT] Fix/Lock object resync in a metabase

### LINKED ISSUE #1502: Lock objects do not fill metabase on `resync_metabase`
Seems like it is true. SE [does not](https://github.com/nspcc-dev/neofs-node/blob/68a01121936170abae893d8772bd2629e6322c5d/pkg/local_object_storage/shard/control.go#L77) call [`Lock`](https://github.com/nspcc-dev/neofs-node/blob/68a01121936170abae893d8772bd2629e6322c5d/pkg/local_object_storage/metabase/lock.go#L31).

Needed to be verified. If true, we are losing every lock relationship on every metabase dropping.

### PR DESCRIPTION
**Pull request by carpawell**
Closes #1502.

### CODE REVIEW

File: pkg/services/policer/check.go [hunk 1]
```diff
@@ -162,6 +166,12 @@ func (p *Policer) processNodes(ctx *processPlacementContext, addr oid.Address,
 		)
 	}
 
+	if typ == object.TypeLock {
+		// all nodes of a container must store the `LOCK` objects
+		// for correct object removal protection
+		shortage = uint32(len(nodes))
```
Comment (fyrchik) [inline pkg/services/policer/check.go:172]: Could you explain it a bit here?
1. We broadcast them on PUT
2. They can't be deleted anyway.

File: pkg/local_object_storage/engine/inhume.go [hunk 2]
```diff
@@ -79,6 +80,18 @@ func (e *StorageEngine) inhume(prm InhumePrm) (InhumeRes, error) {
 	}
 
 	for i := range prm.addrs {
+		if !prm.forceRemoval {
+			locked, err := e.isLocked(prm.addrs[i])
+			if err != nil {
+				return InhumeRes{}, fmt.Errorf("could not check locking status: %w", err)
```
Comment (fyrchik) [inline pkg/local_object_storage/engine/inhume.go:86]: While I agree this could be a correct behaviour, I think it is a rather big change to me merged right before the release.
Can we check what whatever is possible here and skip missing shards?
1. We do similar things for `Exists`/Tombstones in degraded mode.
2. We still check many shards, so it would be better than our current behaviour.

Comment (carpawell) [reply pkg/local_object_storage/engine/inhume.go:86]: so you mean just checking all the shards we can and removing the objects if all the _available_ objects allow doing that?

File: pkg/services/policer/check.go (hunk 1 above)
Comment (carpawell) [reply pkg/services/policer/check.go:172]: > We broadcast them on PUT

yes, but we do not check `LOCK`'s placement after creation (e.g. a node could be turned off for a while when a `LOCK` was put)

> They can't be deleted anyway.

but they would be tried to be deleted on every policer's iteration

the interesting thing about it is that the answers to both of your questions are related: we either try to keep `LOCK`s on every container node or try to remove them unsuccessfully by GC (well, ok, the 3rd option is to change the code significantly)

Comment (fyrchik) [reply pkg/services/policer/check.go:172]: I mean could you add this info to a comment?

File: pkg/local_object_storage/engine/inhume.go (hunk 2 above)
Comment (fyrchik) [reply pkg/local_object_storage/engine/inhume.go:86]: Yes

File: pkg/services/policer/check.go (hunk 1 above)
Comment (carpawell) [reply pkg/services/policer/check.go:172]: :hushed:

Comment (carpawell) [reply pkg/services/policer/check.go]: added

File: pkg/local_object_storage/engine/inhume.go (hunk 2 above)
Comment (carpawell) [reply pkg/local_object_storage/engine/inhume.go]: ok, added logging and shard error counter increment, check, please

**Review by fyrchik — APPROVED** [review]

**Review by acid-ant — APPROVED** [review]
