### PR TITLE
local_object_storage: Add a type for logical errors

### LINKED ISSUE #1588: Distinguish between logical and storage errors in the metabase
Currently all errors are returned via the `error` return value. Consider `Exists`, it can return `apistatus.ErrAlreadyRemoved` and some others. There are multiple problems with this approach:
1. Error is complicate and error-prone.
2. It doesn't reflect the reality: if the object was removed it is an expected situation, there is nothing wrong with it.

The proposal is to define local status enum in the metabase and use it for all operations. It should contain each possible logical condition and could be accessed via `res.Reason()` method. Some examples:
1. checking for existence of the removed object
2. deleting locked object
3. deleting special object

On the shard level we can have a simple routine which translates this enum to a proper status code if needed.

### PR DESCRIPTION
**Pull request by fyrchik**
Close #1588.

All logic errors are wrapped in `logicerr.Logical` type and do not affect shard error counter.
This should (1) fix all bugs about shard being unexpectedly (AND wrongly) in degraded and (2) make it easier to make some errors "logical". For example, for #1969 we could just filter `write` syscall result and wrap some of them.

Signed-off-by: Evgenii Stratonikov <evgeniy@morphbits.ru>

### CODE REVIEW

**Review by acid-ant — APPROVED** [review]

File: pkg/core/object/errors.go [hunk 1]
```diff
@@ -1,8 +1,12 @@
...
+	"errors"
+
+	"github.com/nspcc-dev/neofs-node/pkg/local_object_storage/util/logicerr"
+)
 
 // ErrObjectIsExpired is returned when the requested object's
 // epoch is less than the current one. Such objects are considered
 // as removed and should not be returned from the Storage Engine.
-var ErrObjectIsExpired = errors.New("object is expired")
+var ErrObjectIsExpired = logicerr.Wrap(errors.New("object is expired"))
```
Comment (cthulhu-rider) [inline pkg/core/object/errors.go:12]: Lets replace this eror to `local_object_storage` space (here or later)? Seems pretty strange to see it here.

File: pkg/local_object_storage/blobstor/common/errors.go [hunk 2]
```diff
@@ -1,10 +1,14 @@
...
+import (
+	"errors"
+
+	"github.com/nspcc-dev/neofs-node/pkg/local_object_storage/util/logicerr"
+)
 
 // ErrReadOnly MUST be returned for modifying operations when the storage was opened
 // in readonly mode.
-var ErrReadOnly = errors.New("opened as read-only")
+var ErrReadOnly = logicerr.Wrap(errors.New("opened as read-only"))
```
Comment (cthulhu-rider) [inline pkg/local_object_storage/blobstor/common/errors.go:11]: Maybe provide similar constructor `logicerr.New(string) error`? Otherwise, I would expect wrapping on the `return` side instead of the definition place.

**Review by cthulhu-rider — APPROVED** [review]

File: pkg/local_object_storage/blobstor/common/errors.go (hunk 2 above)
Comment (fyrchik) [reply pkg/local_object_storage/blobstor/common/errors.go:11]: The intention was to keep the package as small as possible. But I guess `New` is not big and would save us some code.

Comment (fyrchik) [reply pkg/local_object_storage/blobstor/common/errors.go:11]: Also, it is intentionally used in the definition -- this way it is harder to misuse or forget about something.
This wrapper is used only for error reporting and here the _essence_ of the error matters, not where it ocurred.

Comment (fyrchik) [reply pkg/local_object_storage/blobstor/common/errors.go]: Fixde

File: pkg/core/object/errors.go (hunk 1 above)
Comment (fyrchik) [reply pkg/core/object/errors.go]: Fixed

**Review by cthulhu-rider — APPROVED** [review]
