### PR TITLE
engine: fix flaky shard evacuate test

### LINKED ISSUE #3516: Flaky storage evacuation unit test
* FAIL https://github.com/nspcc-dev/neofs-node/actions/runs/16878125396/job/47807313711?pr=3515
* PASS https://github.com/nspcc-dev/neofs-node/actions/runs/16878125396/job/47807801597?pr=3515

### PR DESCRIPTION
**Pull request by End-rey**
Closes #3516.

### CODE REVIEW

**Review by roman-khimov — APPROVED** [review]
Can be solved with pushing as many objects as needed to get `objPerShard` for all shards (maybe other tests have some assumptions as well), but one is OK to fix the test as well.

File: pkg/local_object_storage/engine/evacuate_test.go [hunk 1]
```diff
@@ -167,11 +167,11 @@ func TestEvacuateNetwork(t *testing.T) {
 	})
 	t.Run("multiple shards, evacuate many", func(t *testing.T) {
 		e, ids, objects := newEngineEvacuate(t, 4, 5)
-		evacuateIDs := ids[0:3]
+		evacuateIDs := ids[1:4]
 
 		var totalCount int
-		for i := range evacuateIDs {
-			res, err := e.shards[ids[i].String()].List()
+		for _, id := range evacuateIDs {
```
Comment (cthulhu-rider) [inline pkg/local_object_storage/engine/evacuate_test.go:173]: unrelated

**Review by cthulhu-rider — APPROVED** [review]

File: pkg/local_object_storage/engine/evacuate_test.go (hunk 1 above)
Comment (End-rey) [reply pkg/local_object_storage/engine/evacuate_test.go:173]: Previously, slice indexes matched shard numbers, but now different numbers are used, so the iteration method needs to be changed. Therefore, I think this is related.
