### PR TITLE
Validate object attributes

### LINKED ISSUE #633: Node accepts objects with non unique attributes
## Expected Behavior
Storage nodes do not accept object put requests with non unique attributes (according to specification).

## Current Behavior
User can create object with non unique attributes in CLI and storage nodes will successfully proceed it. 

## Steps to Reproduce (for bugs)
```
$ ./bin/neofs-cli -r [...] --binary-key [...] object put --cid  [...] \
--file ./LICENSE \
--attributes FileName=ESNECIL
[./LICENSE] Object successfully stored

$ ./bin/neofs-cli -r [...] --binary-key [...] object head --cid [...] --oid [...]
...
Attributes:
  FileName=ESNECIL
  FileName=LICENSE
```

## Your Environment
neofs-node v0.21.0-77-g8fac4acd

### PR DESCRIPTION
**Pull request by cthulhu-rider**
Closes #633.

### CODE REVIEW

File: pkg/core/object/fmt.go [hunk 1]
```diff
@@ -227,6 +231,34 @@ func expirationEpochAttribute(obj *Object) (uint64, error) {
...
+	mUnique := make(map[string]struct{}, len(as))
+
+	for _, a := range as {
+		key := a.Key()
+
+		if _, was := mUnique[key]; was {
+			return errDuplAttr
+		}
+
+		val := a.Value()
```
Comment (carpawell) [inline pkg/core/object/fmt.go:251]: what are the pros of `val` variable?

**Review by carpawell — APPROVED** [review]

File: pkg/core/object/fmt.go (hunk 1 above)
Comment (cthulhu-rider) [reply pkg/core/object/fmt.go]: None for now, removed

**Review by alexvanin — APPROVED** [review]
