### PR TITLE
ir: fix not using the fee parameter

### LINKED ISSUE #3579: IR `fee.main_chain` config is unused
seems like it is unused since 8150a2e2ea85e849aeba23913a8e2b12028639ea. Better to drop it then

### PR DESCRIPTION
**Pull request by End-rey**
Closes #3579.

### CODE REVIEW

File: pkg/morph/client/neofs/client.go [hunk 1]
```diff
@@ -28,7 +28,7 @@ const (
 )
 
 // NewFromMorph wraps client to work with NeoFS contract.
-func NewFromMorph(cli *client.Client, contract util.Uint160, fee fixedn.Fixed8, opts ...Option) (*Client, error) {
+func NewFromMorph(cli *client.Client, contract util.Uint160, opts ...Option) (*Client, error) {
```
Comment (roman-khimov) [inline pkg/morph/client/neofs/client.go:31]: I think this can be kept as is, just handle client.WithStaticFeeIncrement internally.
