### PR TITLE
Iterate over all shards to return complete SplitInfoError

### LINKED ISSUE #391: Periodically a 'Linking object' is not created on a large object uploading
version: 0.14.3-110-g7560901 (0.15.0)
Periodically (not always) a 'Linking object' is not created on a large object uploading.
When requesting each of the nodes by Object ID with the keys --raw and --ttl 1, output on all copies of the object:
Result: {'Split ID': '8616e841-421e-440a-82b2-72bfa1b7bf23', 'Last object': '6aJtqCwByEBkFSuy9PH8oqC5c726kBzCs8pe9Dk3to4z'}

It is expected that at least one - in the output will return a link to the 'Linking object'.

Example output:
```
@{SPLIT_OBJ_2} = neofs . Get Split objects ${PRIV_KEY}, ${CID}, ${S_OID_2}
Start / End / Elapsed:	20210215 18:03:29.886 / 20210215 18:03:29.978 / 00:00:00.092
18:03:29.886	INFO	Collect Split objects list from Linked object.	
18:03:29.887	INFO	Storage nodes: ['s01.neofs.devenv:8080', 's02.neofs.devenv:8080', 's03.neofs.devenv:8080', 's04.neofs.devenv:8080']	
18:03:29.887	INFO	Cmd: neofs-cli --rpc-endpoint s01.neofs.devenv:8080 --key L3yMnkDRVDGPgaAhjR61kQDiu1DMajUse7GKcW3qZunuDYB42s6Q object head --cid 4U21iF9cCBqkbXvygtkmtXKGBB8QeqY5EKoF7rQxPJQP --oid AV61DB1um1ofTkT2XvrFxE1HcaFXnMV71UvKkxcY3dj4  --raw --ttl 1	
18:03:29.909	INFO	Output: Object is complex, split information received.
Split ID: 8616e841-421e-440a-82b2-72bfa1b7bf23
Last object: 6aJtqCwByEBkFSuy9PH8oqC5c726kBzCs8pe9Dk3to4z
18:03:29.909	INFO	Result: {'Split ID': '8616e841-421e-440a-82b2-72bfa1b7bf23', 'Last object': '6aJtqCwByEBkFSuy9PH8oqC5c726kBzCs8pe9Dk3to4z'}	
18:03:29.909	INFO	Cmd: neofs-cli --rpc-endpoint s02.neofs.devenv:8080 --key L3yMnkDRVDGPgaAhjR61kQDiu1DMajUse7GKcW3qZunuDYB42s6Q object head --cid 4U21iF9cCBqkbXvygtkmtXKGBB8QeqY5EKoF7rQxPJQP --oid AV61DB1um1ofTkT2XvrFxE1HcaFXnMV71UvKkxcY3dj4  --raw --ttl 1	
18:03:29.931	INFO	command 'neofs-cli --rpc-endpoint s02.neofs.devenv:8080 --key L3yMnkDRVDGPgaAhjR61kQDiu1DMajUse7GKcW3qZunuDYB42s6Q object head --cid 4U21iF9cCBqkbXvygtkmtXKGBB8QeqY5EKoF7rQxPJQP --oid AV61DB1um1ofTkT2XvrFxE1HcaFXnMV71UvKkxcY3dj4  --raw --ttl 1' return with error (code 1): Error: can't put object: could not send *object.HeadRequest: could not send head object request: rpc error: code = Unknown desc = could not handle request: could not handle request: object not found
Usage:
  neofs-cli object head [flags]

Flags:
      --cid string    Container ID
      --file string   File to write header to. Default: stdout.
  -h, --help          help for head
      --json          Marshal output in JSON
      --main-only     Return only main fields
      --oid string    Object ID
      --proto         Marshal output in Protobuf
      --raw           Set raw request option

Global Flags:
      --bearer string         File with signed JSON or binary encoded bearer token
  -c, --config string         config file (default is $HOME/.config/neofs-cli/config.yaml)
  -k, --key --key new         private key in hex, WIF or filepath (use --key new to generate key for request)
  -r, --rpc-endpoint string   remote node address (as 'multiaddr' or '<host>:<port>')
      --ttl uint32            TTL value in request meta header (default 2)
  -v, --verbose               verbose output
  -x, --xhdr strings          Request X-Headers in form of Key=Value

18:03:29.931	INFO	Result: {}	
18:03:29.931	INFO	Cmd: neofs-cli --rpc-endpoint s03.neofs.devenv:8080 --key L3yMnkDRVDGPgaAhjR61kQDiu1DMajUse7GKcW3qZunuDYB42s6Q object head --cid 4U21iF9cCBqkbXvygtkmtXKGBB8QeqY5EKoF7rQxPJQP --oid AV61DB1um1ofTkT2XvrFxE1HcaFXnMV71UvKkxcY3dj4  --raw --ttl 1	
18:03:29.951	INFO	command 'neofs-cli --rpc-endpoint s03.neofs.devenv:8080 --key L3yMnkDRVDGPgaAhjR61kQDiu1DMajUse7GKcW3qZunuDYB42s6Q object head --cid 4U21iF9cCBqkbXvygtkmtXKGBB8QeqY5EKoF7rQxPJQP --oid AV61DB1um1ofTkT2XvrFxE1HcaFXnMV71UvKkxcY3dj4  --raw --ttl 1' return with error (code 1): Error: can't put object: could not send *object.HeadRequest: could not send head object request: rpc error: code = Unknown desc = could not handle request: could not handle request: object not found
Usage:
  neofs-cli object head [flags]

Flags:
      --cid string    Container ID
      --file string   File to write header to. Default: stdout.
  -h, --help          help for head
      --json          Marshal output in JSON
      --main-only     Return only main fields
      --oid string    Object ID
      --proto         Marshal output in Protobuf
      --raw           Set raw request option

Global Flags:
      --bearer string         File with signed JSON or binary encoded bearer token
  -c, --config string         config file (default is $HOME/.config/neofs-cli/config.yaml)
  -k, --key --key new         private key in hex, WIF or filepath (use --key new to generate key for request)
  -r, --rpc-endpoint string   remote node address (as 'multiaddr' or '<host>:<port>')
      --ttl uint32            TTL value in request meta header (default 2)
  -v, --verbose               verbose output
  -x, --xhdr strings          Request X-Headers in form of Key=Value

18:03:29.951	INFO	Result: {}	
18:03:29.951	INFO	Cmd: neofs-cli --rpc-endpoint s04.neofs.devenv:8080 --key L3yMnkDRVDGPgaAhjR61kQDiu1DMajUse7GKcW3qZunuDYB42s6Q object head --cid 4U21iF9cCBqkbXvygtkmtXKGBB8QeqY5EKoF7rQxPJQP --oid AV61DB1um1ofTkT2XvrFxE1HcaFXnMV71UvKkxcY3dj4  --raw --ttl 1	
18:03:29.977	INFO	Output: Object is complex, split information received.
Split ID: 8616e841-421e-440a-82b2-72bfa1b7bf23
Last object: 6aJtqCwByEBkFSuy9PH8oqC5c726kBzCs8pe9Dk3to4z
18:03:29.977	INFO	Result: {'Split ID': '8616e841-421e-440a-82b2-72bfa1b7bf23', 'Last object': '6aJtqCwByEBkFSuy9PH8oqC5c726kBzCs8pe9Dk3to4z'}	
18:03:29.978	FAIL	Linking object has not been found.
```

### PR DESCRIPTION
**Pull request by alexvanin**
Closes #391

Issue fixed for head, get and range requests.
Unit test covers `engine.Head` invocation.

### CODE REVIEW

File: pkg/local_object_storage/metabase/put.go [hunk 1]
```diff
@@ -448,9 +448,9 @@ func splitInfoFromObject(obj *object.Object) (*objectSDK.SplitInfo, error) {
 	return info, nil
 }
 
-// mergeSplitInfo ignores conflicts and rewrites `to` with non empty values
+// MergeSplitInfo ignores conflicts and rewrites `to` with non empty values
 // from `from`.
-func mergeSplitInfo(from, to *objectSDK.SplitInfo) *objectSDK.SplitInfo {
+func MergeSplitInfo(from, to *objectSDK.SplitInfo) *objectSDK.SplitInfo {
```
Comment (carpawell) [inline pkg/local_object_storage/metabase/put.go:453]: that func started to be used somewhere in external pkg, if i understand everything right. shouldn't it be moved somewhere in more general pkg(`util`?), or this is always used with `put` context?

Comment (alexvanin) [reply pkg/local_object_storage/metabase/put.go:453]: You are right, it can be moved outside of metabase package. It is deeply connected with internal storage engine operations, so I think it should stay at `pkg/local_object_storage/common`, for example.

Comment (carpawell) [reply pkg/local_object_storage/metabase/put.go:453]: sorry, yes, i was talking about `pkg/local_object_storage/util` not about `pkg/util`

Comment (alexvanin) [reply pkg/local_object_storage/metabase/put.go]: Fixed.

**Review by carpawell — APPROVED** [review]
